export declare const SECONDS_PER_MINUTE = 60;
export declare const MINUTES_PER_HOUR = 60;
export declare const HOURS_PER_DAY = 24;
export declare const MS_PER_SECOND = 1000;
export declare const MS_PER_MINUTE: number;
export declare const MS_PER_HOUR: number;
export declare const ONE_DAY_MS: number;
export declare const DEFAULT_LRU_MAX_ENTRIES: number;
export declare const COMPONENT_LOADER_MAX_ENTRIES: number;
export declare const COMPONENT_LOADER_TTL_MS: number;
export declare const MDX_RENDERER_MAX_ENTRIES: number;
export declare const MDX_RENDERER_TTL_MS: number;
export declare const RENDERER_CORE_MAX_ENTRIES: number;
export declare const RENDERER_CORE_TTL_MS: number;
export declare const TSX_LAYOUT_MAX_ENTRIES: number;
export declare const TSX_LAYOUT_TTL_MS: number;
export declare const DATA_FETCHING_MAX_ENTRIES: number;
export declare const DATA_FETCHING_TTL_MS: number;
export declare const MDX_CACHE_TTL_PRODUCTION_MS: number;
export declare const MDX_CACHE_TTL_DEVELOPMENT_MS: number;
export declare const BUNDLE_CACHE_TTL_PRODUCTION_MS: number;
export declare const BUNDLE_CACHE_TTL_DEVELOPMENT_MS: number;
export declare const BUNDLE_MANIFEST_PROD_TTL_MS: number;
export declare const BUNDLE_MANIFEST_DEV_TTL_MS: number;
export declare const RSC_MANIFEST_CACHE_TTL_MS = 5000;
export declare const SERVER_ACTION_DEFAULT_TTL_SEC: number;
export declare const DISTRIBUTED_SSR_MODULE_TTL_PRODUCTION_SEC: number;
export declare const DISTRIBUTED_SSR_MODULE_TTL_PREVIEW_SEC: number;
export declare const DISTRIBUTED_TRANSFORM_TTL_PRODUCTION_SEC: number;
export declare const DISTRIBUTED_TRANSFORM_TTL_PREVIEW_SEC: number;
export declare const DISTRIBUTED_FILE_TTL_PRODUCTION_SEC: number;
export declare const DISTRIBUTED_FILE_TTL_PREVIEW_SEC: number;
export declare const DISTRIBUTED_CSS_TTL_PRODUCTION_SEC: number;
export declare const DISTRIBUTED_CSS_TTL_PREVIEW_SEC: number;
/** Get environment-aware distributed cache TTL in seconds */
export declare function getDistributedCacheTTL(cacheType: "ssr-module" | "transform" | "file" | "css", isProduction?: boolean): number;
export declare const DENO_KV_SAFE_SIZE_LIMIT_BYTES = 64000;
export declare const LRU_DEFAULT_MAX_ENTRIES_V2: number;
export declare const LRU_DEFAULT_MAX_SIZE_BYTES: number;
export declare const MEMORY_CACHE_MAX_ENTRIES: number;
export declare const FILE_CACHE_MAX_ENTRIES: number;
export declare const FILE_CACHE_MAX_SIZE_MB: number;
export declare const HTTP_CACHE_SHORT_MAX_AGE_SEC = 60;
export declare const HTTP_CACHE_MEDIUM_MAX_AGE_SEC = 3600;
export declare const HTTP_CACHE_LONG_MAX_AGE_SEC = 31536000;
export declare const CACHE_CLEANUP_INTERVAL_MS = 60000;
export declare const CLEANUP_INTERVAL_MULTIPLIER = 2;
export declare const MAX_CONCURRENT_REVALIDATIONS: number;
export declare const MAX_CONCURRENT_HTTP_FETCHES: number;
export declare const REVALIDATION_TIMEOUT_MS: number;
export declare const REVALIDATION_PER_PROJECT_LIMIT: number;
export declare const BUNDLE_MANIFEST_DISTRIBUTED_TTL_SEC: number;
export declare const BUNDLE_MANIFEST_LRU_MAX_ENTRIES: number;
export declare const HTTP_MODULE_CACHE_MAX_ENTRIES: number;
export declare const HTTP_MODULE_DISTRIBUTED_TTL_SEC: number;
export declare const TRANSFORM_DISTRIBUTED_TTL_SEC: number;
export declare const MODULE_CACHE_MAX_ENTRIES: number;
export declare const MODULE_CACHE_TTL_MS: number;
export declare const ESM_CACHE_MAX_ENTRIES: number;
export declare const ESM_CACHE_TTL_MS: number;
//# sourceMappingURL=cache.d.ts.map