export { MS_PER_MINUTE, MS_PER_SECOND, SECONDS_PER_MINUTE } from "./cache.js";
export declare const KB_IN_BYTES = 1024;
export declare const HTTP_MODULE_FETCH_TIMEOUT_MS = 2500;
export declare const HMR_RECONNECT_DELAY_MS = 1000;
export declare const HMR_RELOAD_DELAY_MS = 1000;
export declare const HMR_FILE_WATCHER_DEBOUNCE_MS = 100;
export declare const HMR_KEEP_ALIVE_INTERVAL_MS = 30000;
export declare const DASHBOARD_RECONNECT_DELAY_MS = 3000;
export declare const SERVER_FUNCTION_DEFAULT_TIMEOUT_MS = 30000;
/** Default timeout for HTTP module/bundle fetch operations (30 seconds) */
export declare const HTTP_FETCH_TIMEOUT_MS = 30000;
export declare const PREFETCH_MAX_SIZE_BYTES: number;
export declare const PREFETCH_DEFAULT_TIMEOUT_MS = 10000;
export declare const PREFETCH_DEFAULT_DELAY_MS = 200;
export declare const HTTP_OK = 200;
export declare const HTTP_CREATED = 201;
export declare const HTTP_NO_CONTENT = 204;
export declare const HTTP_REDIRECT_FOUND = 302;
export declare const HTTP_NOT_MODIFIED = 304;
export declare const HTTP_BAD_REQUEST = 400;
export declare const HTTP_UNAUTHORIZED = 401;
export declare const HTTP_FORBIDDEN = 403;
export declare const HTTP_NOT_FOUND = 404;
export declare const HTTP_METHOD_NOT_ALLOWED = 405;
export declare const HTTP_GONE = 410;
export declare const HTTP_PAYLOAD_TOO_LARGE = 413;
export declare const HTTP_URI_TOO_LONG = 414;
export declare const HTTP_TOO_MANY_REQUESTS = 429;
export declare const HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
export declare const HTTP_INTERNAL_SERVER_ERROR = 500;
export declare const HTTP_SERVER_ERROR = 500;
export declare const HTTP_NOT_IMPLEMENTED = 501;
export declare const HTTP_BAD_GATEWAY = 502;
export declare const HTTP_UNAVAILABLE = 503;
export declare const HTTP_NETWORK_CONNECT_TIMEOUT = 599;
export declare const HTTP_STATUS_SUCCESS_MIN = 200;
export declare const HTTP_STATUS_REDIRECT_MIN = 300;
export declare const HTTP_STATUS_CLIENT_ERROR_MIN = 400;
export declare const HTTP_STATUS_SERVER_ERROR_MIN = 500;
export declare const HTTP_CONTENT_TYPES: {
    readonly JS: "application/javascript; charset=utf-8";
    readonly JSON: "application/json; charset=utf-8";
    readonly HTML: "text/html; charset=utf-8";
    readonly CSS: "text/css; charset=utf-8";
    readonly TEXT: "text/plain; charset=utf-8";
};
export declare const HTTP_CONTENT_TYPE_IMAGE_PNG = "image/png";
export declare const HTTP_CONTENT_TYPE_IMAGE_JPEG = "image/jpeg";
export declare const HTTP_CONTENT_TYPE_IMAGE_WEBP = "image/webp";
export declare const HTTP_CONTENT_TYPE_IMAGE_AVIF = "image/avif";
export declare const HTTP_CONTENT_TYPE_IMAGE_SVG = "image/svg+xml";
export declare const HTTP_CONTENT_TYPE_IMAGE_GIF = "image/gif";
export declare const HTTP_CONTENT_TYPE_IMAGE_ICO = "image/x-icon";
//# sourceMappingURL=http.d.ts.map