export declare const DEFAULT_DEV_SERVER_PORT = 3000;
export declare const DEFAULT_REDIS_PORT = 6379;
export declare const DEFAULT_API_SERVER_PORT = 8080;
export declare const DEFAULT_PREVIEW_SERVER_PORT = 5000;
export declare const DEFAULT_METRICS_PORT = 9000;
export declare const BYTES_PER_KB = 1024;
export declare const BYTES_PER_MB: number;
export declare const DEFAULT_IMAGE_THUMBNAIL_SIZE = 256;
export declare const DEFAULT_IMAGE_SMALL_SIZE = 512;
export declare const DEFAULT_IMAGE_LARGE_SIZE = 2048;
export declare const RESPONSIVE_IMAGE_WIDTH_XS = 320;
export declare const RESPONSIVE_IMAGE_WIDTH_SM = 640;
export declare const RESPONSIVE_IMAGE_WIDTH_MD = 1024;
export declare const RESPONSIVE_IMAGE_WIDTH_LG = 1920;
export declare const RESPONSIVE_IMAGE_WIDTHS: readonly [320, 640, 1024, 1920];
export declare const MAX_CHUNK_SIZE_KB = 4096;
export declare const MIN_PORT = 1;
export declare const MAX_PORT = 65535;
export declare const DEFAULT_SERVER_PORT = 8000;
//# sourceMappingURL=network.d.ts.map