/**
 * Handler priority constants - lower numbers run first.
 * CRITICAL(0) -> VERY_HIGH(50) -> HIGH(100-300) -> MEDIUM(400-700) -> LOW(1000) -> FALLBACK(10000)
 */
export const PRIORITY_CRITICAL = 0;
export const PRIORITY_VERY_HIGH = 50;
export const PRIORITY_HIGH = 100;
export const PRIORITY_HIGH_CLIENT_LOG = 200;
export const PRIORITY_HIGH_DEV = 300;
export const PRIORITY_MEDIUM_DEV_FILES = 400;
export const PRIORITY_MEDIUM_STATIC = 500;
export const PRIORITY_MEDIUM_LIB_MODULES = 550;
export const PRIORITY_MEDIUM = 600;
export const PRIORITY_MEDIUM_API = 700;
export const PRIORITY_LOW = 1000;
export const PRIORITY_FALLBACK = 10000;
export const HANDLER_PRIORITIES = {
    CRITICAL: PRIORITY_CRITICAL,
    VERY_HIGH: PRIORITY_VERY_HIGH,
    HIGH: PRIORITY_HIGH,
    HIGH_CLIENT_LOG: PRIORITY_HIGH_CLIENT_LOG,
    HIGH_DEV: PRIORITY_HIGH_DEV,
    MEDIUM_DEV_FILES: PRIORITY_MEDIUM_DEV_FILES,
    MEDIUM_STATIC: PRIORITY_MEDIUM_STATIC,
    MEDIUM_LIB_MODULES: PRIORITY_MEDIUM_LIB_MODULES,
    MEDIUM: PRIORITY_MEDIUM,
    MEDIUM_API: PRIORITY_MEDIUM_API,
    LOW: PRIORITY_LOW,
    FALLBACK: PRIORITY_FALLBACK,
};
