/**
 * Cache Invalidation Tests
 *
 * Tests for cache key prefix matching between generation (cache-keys.ts)
 * and invalidation (adapter.ts performInvalidation/performSelectiveInvalidation).
 *
 * These tests verify that:
 * 1. Cache keys generated by the system match the patterns used for invalidation
 * 2. Full invalidation clears all cache types correctly
 * 3. Selective invalidation clears specific paths and their stat/dir caches
 */

import { assertEquals } from "@veryfront/testing/assert";
import { describe, it } from "@veryfront/testing/bdd";
import {
  buildDirCacheKeyPrefix,
  buildFileCacheKeyPrefix,
  buildFileListCacheKey,
  buildStatCacheKeyPrefix,
} from "@veryfront/platform/adapters/fs/veryfront/cache-keys.ts";
import type { ResolvedContentContext } from "@veryfront/platform/adapters/fs/veryfront/types.ts";
import { FileCache } from "@veryfront/platform/adapters/fs/cache/file-cache.ts";

function assertMatchesPrefix(key: string, prefixes: string[], label: string): void {
  const matches = prefixes.some((prefix) => key.startsWith(prefix));
  assertEquals(matches, true, `Key "${key}" should match one of ${label}`);
}

function deleteAllByPrefixes(cache: FileCache, prefixes: string[]): number {
  return prefixes.reduce((total, prefix) => total + cache.deleteByPrefix(prefix), 0);
}

function deleteAllByPrefixAndSuffix(cache: FileCache, prefixes: string[], suffix: string): number {
  return prefixes.reduce(
    (total, prefix) => total + cache.deleteByPrefixAndSuffix(prefix, suffix),
    0,
  );
}

function getParentDir(path: string): string {
  const slashIndex = path.lastIndexOf("/");
  return slashIndex > 0 ? path.substring(0, slashIndex) : "";
}

describe("Cache Invalidation - Key Prefix Matching", () => {
  // Define the prefixes used by performInvalidation() - must match adapter.ts
  const FULL_INVALIDATION_PREFIXES = {
    file: ["file:branch:", "file:release:", "file:env:"],
    stat: ["stat:branch:", "stat:release:", "stat:env:"],
    dir: ["dir:branch:", "dir:release:", "dir:env:"],
    files: ["files:branch:", "files:release:", "files:env:"],
  };

  describe("Branch mode cache keys", () => {
    const branchContext: ResolvedContentContext = {
      sourceType: "branch",
      projectSlug: "test-project",
      branch: "main",
    };

    it("file cache key matches full invalidation prefix", () => {
      const key = buildFileCacheKeyPrefix(branchContext);
      assertEquals(key, "file:branch:test-project:main");
      assertMatchesPrefix(key, FULL_INVALIDATION_PREFIXES.file, `${FULL_INVALIDATION_PREFIXES.file}`);
    });

    it("stat cache key matches full invalidation prefix", () => {
      const key = buildStatCacheKeyPrefix(branchContext);
      assertEquals(key, "stat:branch:test-project:main");
      assertMatchesPrefix(key, FULL_INVALIDATION_PREFIXES.stat, `${FULL_INVALIDATION_PREFIXES.stat}`);
    });

    it("dir cache key matches full invalidation prefix", () => {
      const key = buildDirCacheKeyPrefix(branchContext);
      assertEquals(key, "dir:branch:test-project:main");
      assertMatchesPrefix(key, FULL_INVALIDATION_PREFIXES.dir, `${FULL_INVALIDATION_PREFIXES.dir}`);
    });

    it("files list cache key matches full invalidation prefix", () => {
      const key = buildFileListCacheKey(branchContext);
      assertEquals(key, "files:branch:test-project:main");
      assertMatchesPrefix(
        key,
        FULL_INVALIDATION_PREFIXES.files,
        `${FULL_INVALIDATION_PREFIXES.files}`,
      );
    });
  });

  describe("Release mode cache keys", () => {
    const releaseContext: ResolvedContentContext = {
      sourceType: "release",
      projectSlug: "test-project",
      releaseId: "release-123",
    };

    it("file cache key matches full invalidation prefix", () => {
      const key = buildFileCacheKeyPrefix(releaseContext);
      assertEquals(key, "file:release:test-project:release-123");
      assertMatchesPrefix(key, FULL_INVALIDATION_PREFIXES.file, `${FULL_INVALIDATION_PREFIXES.file}`);
    });

    it("stat cache key matches full invalidation prefix", () => {
      const key = buildStatCacheKeyPrefix(releaseContext);
      assertEquals(key, "stat:release:test-project:release-123");
      assertMatchesPrefix(key, FULL_INVALIDATION_PREFIXES.stat, `${FULL_INVALIDATION_PREFIXES.stat}`);
    });

    it("dir cache key matches full invalidation prefix", () => {
      const key = buildDirCacheKeyPrefix(releaseContext);
      assertEquals(key, "dir:release:test-project:release-123");
      assertMatchesPrefix(key, FULL_INVALIDATION_PREFIXES.dir, `${FULL_INVALIDATION_PREFIXES.dir}`);
    });

    it("files list cache key matches full invalidation prefix", () => {
      const key = buildFileListCacheKey(releaseContext);
      assertEquals(key, "files:release:test-project:release-123");
      assertMatchesPrefix(
        key,
        FULL_INVALIDATION_PREFIXES.files,
        `${FULL_INVALIDATION_PREFIXES.files}`,
      );
    });
  });

  describe("Environment mode cache keys", () => {
    const envContext: ResolvedContentContext = {
      sourceType: "environment",
      projectSlug: "test-project",
      environmentName: "production",
      releaseId: "release-456",
    };

    it("file cache key matches full invalidation prefix", () => {
      const key = buildFileCacheKeyPrefix(envContext);
      assertEquals(key, "file:env:test-project:production:release-456");
      assertMatchesPrefix(key, FULL_INVALIDATION_PREFIXES.file, `${FULL_INVALIDATION_PREFIXES.file}`);
    });

    it("stat cache key matches full invalidation prefix", () => {
      const key = buildStatCacheKeyPrefix(envContext);
      assertEquals(key, "stat:env:test-project:production:release-456");
      assertMatchesPrefix(key, FULL_INVALIDATION_PREFIXES.stat, `${FULL_INVALIDATION_PREFIXES.stat}`);
    });

    it("dir cache key matches full invalidation prefix", () => {
      const key = buildDirCacheKeyPrefix(envContext);
      assertEquals(key, "dir:env:test-project:production:release-456");
      assertMatchesPrefix(key, FULL_INVALIDATION_PREFIXES.dir, `${FULL_INVALIDATION_PREFIXES.dir}`);
    });

    it("files list cache key matches full invalidation prefix", () => {
      const key = buildFileListCacheKey(envContext);
      assertEquals(key, "files:env:test-project:production:release-456");
      assertMatchesPrefix(
        key,
        FULL_INVALIDATION_PREFIXES.files,
        `${FULL_INVALIDATION_PREFIXES.files}`,
      );
    });
  });
});

describe("Cache Invalidation - FileCache Operations", () => {
  it("deleteByPrefix clears all matching keys", () => {
    const cache = new FileCache({ maxSize: 100, ttl: 60000 });

    cache.set("file:branch:project:main:components/Button.tsx", "content1");
    cache.set("file:branch:project:main:pages/index.mdx", "content2");
    cache.set("file:release:project:rel-1:components/Button.tsx", "content3");
    cache.set("stat:branch:project:main:components/Button.tsx", { size: 100 });
    cache.set("dir:branch:project:main:components", ["Button.tsx", "Card.tsx"]);

    const deletedCount = cache.deleteByPrefix("file:branch:");
    assertEquals(deletedCount, 2);

    assertEquals(cache.get("file:branch:project:main:components/Button.tsx"), undefined);
    assertEquals(cache.get("file:branch:project:main:pages/index.mdx"), undefined);
    assertEquals(cache.get("file:release:project:rel-1:components/Button.tsx"), "content3");
    assertEquals(cache.get("stat:branch:project:main:components/Button.tsx"), { size: 100 });
  });

  it("deleteByPrefixAndSuffix clears specific path across source types", () => {
    const cache = new FileCache({ maxSize: 100, ttl: 60000 });
    const targetPath = "components/Button.tsx";

    cache.set(`file:branch:project:main:${targetPath}`, "branch content");
    cache.set(`file:release:project:rel-1:${targetPath}`, "release content");
    cache.set(`file:env:project:prod:rel-1:${targetPath}`, "env content");
    cache.set("file:branch:project:main:pages/index.mdx", "other content");

    const deletedCount = cache.deleteByPrefixAndSuffix("file:branch:", targetPath);
    assertEquals(deletedCount, 1);

    assertEquals(cache.get(`file:branch:project:main:${targetPath}`), undefined);
    assertEquals(cache.get(`file:release:project:rel-1:${targetPath}`), "release content");
    assertEquals(cache.get("file:branch:project:main:pages/index.mdx"), "other content");
  });

  it("full invalidation clears all cache types", () => {
    const cache = new FileCache({ maxSize: 100, ttl: 60000 });

    cache.set("file:branch:project:main:test.tsx", "content");
    cache.set("file:release:project:rel:test.tsx", "content");
    cache.set("file:env:project:prod:rel:test.tsx", "content");
    cache.set("stat:branch:project:main:test.tsx", { size: 1 });
    cache.set("stat:release:project:rel:test.tsx", { size: 2 });
    cache.set("stat:env:project:prod:rel:test.tsx", { size: 3 });
    cache.set("dir:branch:project:main:components", ["a.tsx"]);
    cache.set("dir:release:project:rel:components", ["b.tsx"]);
    cache.set("dir:env:project:prod:rel:components", ["c.tsx"]);
    cache.set("files:branch:project:main", ["test.tsx"]);
    cache.set("files:release:project:rel", ["test.tsx"]);
    cache.set("files:env:project:prod:rel", ["test.tsx"]);

    assertEquals(cache.stats().size, 12);

    const prefixes = [
      "file:branch:",
      "file:release:",
      "file:env:",
      "stat:branch:",
      "stat:release:",
      "stat:env:",
      "dir:branch:",
      "dir:release:",
      "dir:env:",
      "files:branch:",
      "files:release:",
      "files:env:",
    ];

    const totalDeleted = deleteAllByPrefixes(cache, prefixes);

    assertEquals(totalDeleted, 12);
    assertEquals(cache.stats().size, 0);
  });

  it("selective invalidation clears file, stat, and parent dir for changed path", () => {
    const cache = new FileCache({ maxSize: 100, ttl: 60000 });
    const changedPath = "components/Button.tsx";
    const parentDir = "components";

    cache.set(`file:branch:project:main:${changedPath}`, "content");
    cache.set(`stat:branch:project:main:${changedPath}`, { size: 100 });
    cache.set(`dir:branch:project:main:${parentDir}`, ["Button.tsx", "Card.tsx"]);
    cache.set("file:branch:project:main:pages/index.mdx", "other file");

    const filePrefixes = ["file:branch:", "file:release:", "file:env:"];
    const statPrefixes = ["stat:branch:", "stat:release:", "stat:env:"];
    const dirPrefixes = ["dir:branch:", "dir:release:", "dir:env:"];

    let deleted = 0;
    deleted += deleteAllByPrefixAndSuffix(cache, filePrefixes, changedPath);
    deleted += deleteAllByPrefixAndSuffix(cache, statPrefixes, changedPath);
    deleted += deleteAllByPrefixAndSuffix(cache, dirPrefixes, parentDir);

    assertEquals(deleted, 3);
    assertEquals(cache.get(`file:branch:project:main:${changedPath}`), undefined);
    assertEquals(cache.get(`stat:branch:project:main:${changedPath}`), undefined);
    assertEquals(cache.get(`dir:branch:project:main:${parentDir}`), undefined);
    assertEquals(cache.get("file:branch:project:main:pages/index.mdx"), "other file");
  });

  it("selective invalidation clears root directory cache for root-level file changes", () => {
    const cache = new FileCache({ maxSize: 100, ttl: 60000 });
    const rootFile = "logo.png";

    cache.set(`file:branch:project:main:${rootFile}`, "image content");
    cache.set(`stat:branch:project:main:${rootFile}`, { size: 5000 });
    cache.set("dir:branch:project:main:", ["logo.png", "README.md"]);
    cache.set("file:branch:project:main:components/Button.tsx", "other file");

    const parentDir = getParentDir(rootFile);
    assertEquals(parentDir, "");

    let deleted = 0;
    deleted += cache.deleteByPrefixAndSuffix("file:branch:", rootFile);
    deleted += cache.deleteByPrefixAndSuffix("stat:branch:", rootFile);
    deleted += cache.deleteByPrefixAndSuffix("dir:branch:", parentDir);

    assertEquals(deleted, 3);
    assertEquals(cache.get(`file:branch:project:main:${rootFile}`), undefined);
    assertEquals(cache.get(`stat:branch:project:main:${rootFile}`), undefined);
    assertEquals(cache.get("dir:branch:project:main:"), undefined);
    assertEquals(cache.get("file:branch:project:main:components/Button.tsx"), "other file");
  });

  it("root directory parent calculation uses empty string not slash", () => {
    const testCases = [
      { path: "logo.png", expectedParent: "" },
      { path: "README.md", expectedParent: "" },
      { path: "components/Button.tsx", expectedParent: "components" },
      { path: "pages/api/health.ts", expectedParent: "pages/api" },
      { path: "a/b/c/d.ts", expectedParent: "a/b/c" },
    ];

    for (const { path, expectedParent } of testCases) {
      const parentDir = getParentDir(path);
      assertEquals(
        parentDir,
        expectedParent,
        `Path "${path}" should have parent "${expectedParent}", got "${parentDir}"`,
      );
    }
  });
});

describe("Cache Invalidation - Invalid Prefix Detection", () => {
  // These tests ensure that the OLD (incorrect) prefixes don't match any keys
  // This validates the bug fix by proving the old prefixes were wrong
  const OLD_INVALID_PREFIXES = ["file:text:", "file:content:", "file:stat:", "dir:entries:"];

  it("old invalid prefixes do not match any generated cache keys", () => {
    const contexts: ResolvedContentContext[] = [
      { sourceType: "branch", projectSlug: "test", branch: "main" },
      { sourceType: "release", projectSlug: "test", releaseId: "rel-1" },
      {
        sourceType: "environment",
        projectSlug: "test",
        environmentName: "prod",
        releaseId: "rel-1",
      },
    ];

    for (const ctx of contexts) {
      const keys = [
        { type: "File", key: buildFileCacheKeyPrefix(ctx) },
        { type: "Stat", key: buildStatCacheKeyPrefix(ctx) },
        { type: "Dir", key: buildDirCacheKeyPrefix(ctx) },
        { type: "Files", key: buildFileListCacheKey(ctx) },
      ];

      for (const invalidPrefix of OLD_INVALID_PREFIXES) {
        for (const { type, key } of keys) {
          assertEquals(
            key.startsWith(invalidPrefix),
            false,
            `${type} key "${key}" should NOT match invalid prefix "${invalidPrefix}"`,
          );
        }
      }
    }
  });

  it("deleteByPrefix with old invalid prefixes deletes nothing", () => {
    const cache = new FileCache({ maxSize: 100, ttl: 60000 });

    cache.set("file:branch:project:main:test.tsx", "content");
    cache.set("stat:branch:project:main:test.tsx", { size: 1 });
    cache.set("dir:branch:project:main:components", ["test.tsx"]);
    cache.set("files:branch:project:main", ["test.tsx"]);

    assertEquals(cache.stats().size, 4);

    const totalDeleted = deleteAllByPrefixes(cache, OLD_INVALID_PREFIXES);

    assertEquals(totalDeleted, 0);
    assertEquals(cache.stats().size, 4);
  });
});
