import "#veryfront/schemas/_test-setup.ts";
import { assertEquals } from "#veryfront/testing/assert.ts";
import { describe, it } from "#veryfront/testing/bdd.ts";
import fixture from "../../../tests/fixtures/contracts/model-call-context-run-events.v1.json" with {
  type: "json",
};
import largeManifest from "../../../tests/fixtures/contracts/model-call-context-run-events-large.v1.manifest.json" with {
  type: "json",
};
import {
  buildLargeModelCallContextContractFixture,
  buildLargeModelCallContextContractManifest,
  buildModelCallContextContractFixture,
  serializeLargeModelCallContextContractFixture,
} from "./model-call-context-contract-fixture.ts";

describe("model-call context Code to API contract fixture", () => {
  it("is generated by the real adapter with only context UUID canonicalized", async () => {
    const generated = await buildModelCallContextContractFixture();

    assertEquals<unknown>(generated, fixture);
    assertEquals((generated.scenarios[1]?.events.length ?? 0) > 1, true);
    assertEquals(generated.scenarios[2]?.events.length, 1);
    assertEquals(generated.scenarios[2]?.expectedLogicalContext, null);
  });

  it("freezes a native-compressed >2 MiB Unicode fixture at production limits", async () => {
    const compressed = await Deno.readFile(
      new URL(
        "../../../tests/fixtures/contracts/model-call-context-run-events-large.v1.json.gz",
        import.meta.url,
      ),
    );
    const decompressed = await new Response(
      new Blob([compressed]).stream().pipeThrough(new DecompressionStream("gzip")),
    ).text();
    const generated = await buildLargeModelCallContextContractFixture();

    assertEquals(JSON.parse(decompressed), generated);
    assertEquals(decompressed, serializeLargeModelCallContextContractFixture(generated));
    assertEquals(
      await buildLargeModelCallContextContractManifest(decompressed, generated),
      largeManifest,
    );
    assertEquals(generated.scenario.utf8ByteLength > 2 * 1024 * 1024, true);
    assertEquals(generated.scenario.utf8ByteLength <= 4 * 1024 * 1024, true);
    assertEquals(generated.scenario.events.length > 1, true);
  });
});
