export const DEFAULT_DEV_SERVER_PORT = 3000;
export const DEFAULT_REDIS_PORT = 6379;
export const DEFAULT_API_SERVER_PORT = 8080;
export const DEFAULT_PREVIEW_SERVER_PORT = 5000;
export const DEFAULT_METRICS_PORT = 9000;

export const BYTES_PER_KB = 1024;
export const BYTES_PER_MB = BYTES_PER_KB * BYTES_PER_KB;

export const DEFAULT_IMAGE_THUMBNAIL_SIZE = 256;
export const DEFAULT_IMAGE_SMALL_SIZE = 512;
export const DEFAULT_IMAGE_LARGE_SIZE = 2048;

export const RESPONSIVE_IMAGE_WIDTH_XS = 320;
export const RESPONSIVE_IMAGE_WIDTH_SM = 640;
export const RESPONSIVE_IMAGE_WIDTH_MD = 1024;
export const RESPONSIVE_IMAGE_WIDTH_LG = 1920;

export const RESPONSIVE_IMAGE_WIDTHS = [
  RESPONSIVE_IMAGE_WIDTH_XS,
  RESPONSIVE_IMAGE_WIDTH_SM,
  RESPONSIVE_IMAGE_WIDTH_MD,
  RESPONSIVE_IMAGE_WIDTH_LG,
] as const;

export const MAX_CHUNK_SIZE_KB = 4096;

export const MIN_PORT = 1;
export const MAX_PORT = 65535;

export const DEFAULT_SERVER_PORT = 8000;
