export declare const ErrorCode: {
    readonly CONFIG_NOT_FOUND: "VF001";
    readonly CONFIG_INVALID: "VF002";
    readonly CONFIG_PARSE_ERROR: "VF003";
    readonly CONFIG_VALIDATION_ERROR: "VF004";
    readonly CONFIG_TYPE_ERROR: "VF005";
    readonly IMPORT_MAP_INVALID: "VF006";
    readonly CORS_CONFIG_INVALID: "VF007";
    readonly BUILD_FAILED: "VF100";
    readonly BUNDLE_ERROR: "VF101";
    readonly TYPESCRIPT_ERROR: "VF102";
    readonly MDX_COMPILE_ERROR: "VF103";
    readonly ASSET_OPTIMIZATION_ERROR: "VF104";
    readonly SSG_GENERATION_ERROR: "VF105";
    readonly SOURCEMAP_ERROR: "VF106";
    readonly HYDRATION_MISMATCH: "VF200";
    readonly RENDER_ERROR: "VF201";
    readonly COMPONENT_ERROR: "VF202";
    readonly LAYOUT_NOT_FOUND: "VF203";
    readonly PAGE_NOT_FOUND: "VF204";
    readonly API_ERROR: "VF205";
    readonly MIDDLEWARE_ERROR: "VF206";
    readonly ROUTE_CONFLICT: "VF300";
    readonly INVALID_ROUTE_FILE: "VF301";
    readonly ROUTE_HANDLER_INVALID: "VF302";
    readonly DYNAMIC_ROUTE_ERROR: "VF303";
    readonly ROUTE_PARAMS_ERROR: "VF304";
    readonly API_ROUTE_ERROR: "VF305";
    readonly MODULE_NOT_FOUND: "VF400";
    readonly IMPORT_RESOLUTION_ERROR: "VF401";
    readonly CIRCULAR_DEPENDENCY: "VF402";
    readonly INVALID_IMPORT: "VF403";
    readonly DEPENDENCY_MISSING: "VF404";
    readonly VERSION_MISMATCH: "VF405";
    readonly PORT_IN_USE: "VF500";
    readonly SERVER_START_ERROR: "VF501";
    readonly HMR_ERROR: "VF502";
    readonly CACHE_ERROR: "VF503";
    readonly CACHE_PATH_MISMATCH: "VF507";
    readonly FILE_WATCH_ERROR: "VF504";
    readonly REQUEST_ERROR: "VF505";
    readonly SERVICE_OVERLOADED: "VF506";
    readonly CLIENT_BOUNDARY_VIOLATION: "VF600";
    readonly SERVER_ONLY_IN_CLIENT: "VF601";
    readonly CLIENT_ONLY_IN_SERVER: "VF602";
    readonly INVALID_USE_CLIENT: "VF603";
    readonly INVALID_USE_SERVER: "VF604";
    readonly RSC_PAYLOAD_ERROR: "VF605";
    readonly DEV_SERVER_ERROR: "VF700";
    readonly FAST_REFRESH_ERROR: "VF701";
    readonly ERROR_OVERLAY_ERROR: "VF702";
    readonly SOURCE_MAP_ERROR: "VF703";
    readonly DEPLOYMENT_ERROR: "VF800";
    readonly PLATFORM_ERROR: "VF801";
    readonly ENV_VAR_MISSING: "VF802";
    readonly PRODUCTION_BUILD_REQUIRED: "VF803";
    readonly UNKNOWN_ERROR: "VF900";
    readonly PERMISSION_DENIED: "VF901";
    readonly FILE_NOT_FOUND: "VF902";
    readonly INVALID_ARGUMENT: "VF903";
    readonly TIMEOUT_ERROR: "VF904";
};
export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
export declare function getErrorDocsUrl(code: ErrorCodeType): string;
export declare function inferErrorCode(error: Error): ErrorCodeType | null;
//# sourceMappingURL=error-codes.d.ts.map