import { join, basename, extname } from "https://deno.land/std@0.220.0/path/mod.ts";
import { ensureDir } from "https://deno.land/std@0.220.0/fs/mod.ts";

export async function generateClientSDK(projectDir: string): Promise<void> {
  const agentsDir = join(projectDir, "ai", "agents");
  const outDir = join(projectDir, ".veryfront");
  const outFile = join(outDir, "client-sdk.d.ts");

  const agents: { id: string; path: string }[] = [];

  try {
    for await (const entry of Deno.readDir(agentsDir)) {
      if (entry.isFile && (entry.name.endsWith(".ts") || entry.name.endsWith(".tsx"))) {
        const id = basename(entry.name, extname(entry.name));
        // Convert ID to camelCase if strictly needed, but let's assume filenames are identifiers for now
        // or map kebab-case to camelCase
        const camelId = id.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
        agents.push({ id: camelId, path: entry.name });
      }
    }
  } catch (e) {
    // Directory might not exist
    return;
  }

  const imports = agents
    .map((agent) => `import type Agent_${agent.id} from "../ai/agents/${agent.path}";`)
    .join("\n");

  const fields = agents
    .map((agent) => `    ${agent.id}: typeof Agent_${agent.id};`)
    .join("\n");

  const content = `/**
 * Auto-generated by Veryfront
 * Do not edit manually.
 */

import type { Agent } from "veryfront/ai";
${imports}

export interface ClientAgents {
${fields}
}

declare module "veryfront/ai/client" {
  export const client: {
    agents: ClientAgents;
  };
}
`;

  await ensureDir(outDir);
  await Deno.writeTextFile(outFile, content);
}
