/****
 * Resource Types
 *
 * Type definitions for MCP resources.
 *
 * @module veryfront/resource
 */

import type { Schema } from "#veryfront/extensions/schema/index.ts";

// Re-export schema-based types
export type { CachePolicy, McpConfig, McpContentConfig } from "./schemas/index.ts";

// Import for use in interface definitions
import type { McpConfig } from "./schemas/index.ts";

/** Per-read runtime context supplied to a resource loader. */
export interface ResourceLoadContext {
  /** Cooperative cancellation signal for the current read. */
  readonly abortSignal?: AbortSignal;
  /** Exact URI requested by the transport, when one exists. */
  readonly uri?: string;
}

/** Configuration used by resource. */
export interface ResourceConfig<TParams = unknown, TData = unknown> {
  /** URI pattern. Patterns may contain at most 8,192 characters. */
  pattern?: string;
  /** Model-facing description. Limited to 16,384 characters. */
  description: string;
  /** Optional display title. Limited to 1,024 characters. */
  title?: string;
  /** Parameter schema captured when the resource is constructed or registered. */
  paramsSchema: Schema<TParams>;
  /** Loader captured when the resource is constructed or registered. */
  load: (
    params: TParams,
    context?: Readonly<ResourceLoadContext>,
  ) => Promise<TData> | TData;
  /**
   * Optional application-level update stream.
   *
   * The Veryfront MCP transport currently exposes resource reads and URI
   * templates, but does not advertise resource subscriptions.
   */
  subscribe?: (params: TParams) => AsyncIterable<TData>;
  /**
   * MCP exposure metadata.
   *
   * `enabled: false` is enforced by list, template, and read operations.
   * `cachePolicy` is reserved for compatibility and is not currently enforced.
   */
  mcp?: McpConfig;
}

/** Authored resource definition accepted at a registry boundary. */
export interface ResourceDefinition<TParams = unknown, TData = unknown>
  extends ResourceConfig<TParams, TData> {
  /** Definition identity. Limited to 8,192 characters and no control characters. */
  id: string;
  pattern: string;
  /** Internal marker distinguishing an autogenerated placeholder pattern. */
  __veryfrontGeneratedPattern?: string;
}

/**
 * Normalized runtime resource.
 *
 * Runtime resources always return a promise because their authored loader has
 * crossed the validation, cancellation, and immutable-snapshot boundary.
 */
export interface Resource<TParams = unknown, TData = unknown>
  extends ResourceDefinition<TParams, TData> {
  load: (
    params: TParams,
    context?: Readonly<ResourceLoadContext>,
  ) => Promise<TData>;
}
