/****
 * Resource Types
 *
 * Type definitions for MCP resources.
 *
 * @module veryfront/resource
 */

import type { Schema } from "#veryfront/extensions/schema/index.ts";

// Re-export schema-based types
export type { CachePolicy, McpConfig } from "./schemas/index.ts";

// Import for use in interface definitions
import type { McpConfig } from "./schemas/index.ts";

/** Configuration used by resource. */
export interface ResourceConfig<TParams = unknown, TData = unknown> {
  pattern?: string;
  description: string;
  title?: string;
  paramsSchema: Schema<TParams>;
  load: (params: TParams) => Promise<TData> | TData;
  /**
   * Optional application-level update stream.
   *
   * The Veryfront MCP transport currently exposes resource reads and URI
   * templates, but does not advertise resource subscriptions.
   */
  subscribe?: (params: TParams) => AsyncIterable<TData>;
  /**
   * MCP exposure metadata.
   *
   * `enabled: false` is enforced by list, template, and read operations.
   * `cachePolicy` is reserved for compatibility and is not currently enforced.
   */
  mcp?: McpConfig;
}

/** Public API contract for resource. */
export interface Resource<TParams = unknown, TData = unknown> {
  id: string;
  pattern: string;
  /** Internal marker distinguishing an autogenerated placeholder pattern. */
  __veryfrontGeneratedPattern?: string;
  description: string;
  title?: string;
  paramsSchema: Schema<TParams>;
  load: (params: TParams) => Promise<TData>;
  /**
   * Optional application-level update stream.
   *
   * The Veryfront MCP transport currently exposes resource reads and URI
   * templates, but does not advertise resource subscriptions.
   */
  subscribe?: (params: TParams) => AsyncIterable<TData>;
  /**
   * MCP exposure metadata.
   *
   * `enabled: false` is enforced by list, template, and read operations.
   * `cachePolicy` is reserved for compatibility and is not currently enforced.
   */
  mcp?: McpConfig;
}
