export type {
  PromptArgument,
  PromptConfig,
  PromptGenerateFn,
  PromptMCPConfig,
  PromptRenderContext,
} from "./schemas/prompt.schema.ts";

import type { PromptMCPConfig, PromptRenderContext } from "./schemas/prompt.schema.ts";

/** Public API contract for prompt. */
export interface Prompt {
  id: string;
  /** Internal marker distinguishing an autogenerated placeholder ID from an explicit ID. */
  __veryfrontGeneratedId?: string;
  description: string;
  /** Example message text to use as a chat suggestion */
  suggestion?: string;
  /** MCP exposure and argument metadata. */
  mcp?: PromptMCPConfig;
  getContent: (
    variables?: Record<string, unknown>,
    context?: Readonly<PromptRenderContext>,
  ) => Promise<string>;
}
