export type { PromptConfig, PromptGenerateFn } from "./schemas/prompt.schema.ts";

/** Public API contract for prompt. */
export interface Prompt {
  id: string;
  /** Internal marker distinguishing an autogenerated placeholder ID from an explicit ID. */
  __veryfrontGeneratedId?: string;
  description: string;
  /** Example message text to use as a chat suggestion */
  suggestion?: string;
  getContent: (variables?: Record<string, unknown>) => Promise<string>;
}
