import { assertEquals, assertThrows } from "#veryfront/testing/assert.ts";
import { describe, it } from "#veryfront/testing/bdd.ts";
import type {
  AgentRunModelCallContextEvent,
  ModelCallMessage,
  ModelCallTool,
} from "./model-call-context.ts";
import { createTimedAgentRunEventSink } from "./model-call-context.ts";

describe("model-call-context", () => {
  it("describes only the direct provider-agnostic event", () => {
    const messages: ModelCallMessage[] = [{
      role: "assistant",
      content: [{
        type: "tool-call",
        toolCallId: "call-1",
        toolName: "search",
        input: { query: "Veryfront" },
      }],
    }];
    const tools: ModelCallTool[] = [{
      type: "provider",
      name: "web_search",
      id: "anthropic.web_search_20250305",
      args: { maxUses: 3 },
    }];
    const event: AgentRunModelCallContextEvent = {
      type: "AGENT_RUN_MODEL_CALL_CONTEXT",
      model: { id: "anthropic/claude-sonnet-4-6", modelProvider: "anthropic" },
      request: { maxOutputTokens: 4096, reasoning: { enabled: true, budgetTokens: 2048 } },
      messages,
      tools,
    };
    assertEquals(event, {
      type: "AGENT_RUN_MODEL_CALL_CONTEXT",
      model: { id: "anthropic/claude-sonnet-4-6", modelProvider: "anthropic" },
      request: { maxOutputTokens: 4096, reasoning: { enabled: true, budgetTokens: 2048 } },
      messages,
      tools,
    });

    const eventWithExtraField: AgentRunModelCallContextEvent = {
      type: "AGENT_RUN_MODEL_CALL_CONTEXT",
      messages,
      // @ts-expect-error model-call context events do not accept chunk metadata
      contextId: "context-1",
    };
    assertEquals(eventWithExtraField.type, "AGENT_RUN_MODEL_CALL_CONTEXT");

    const providerPrivateReasoning: ModelCallMessage = {
      role: "assistant",
      content: [
        // @ts-expect-error signed provider reasoning is not part of ModelCallMessage
        { type: "reasoning", text: "private", signature: "signed" },
      ],
    };
    assertEquals(providerPrivateReasoning.role, "assistant");
  });

  it("rounds generated timing and preserves valid producer timing", () => {
    const events: AgentRunModelCallContextEvent[] = [];
    let now = 100;
    const sink = createTimedAgentRunEventSink(
      (event) => {
        events.push(event);
      },
      { nowMs: () => now, epochMs: () => 1_786_866_357_364.4, startedMs: 100 },
    );
    now = 142.6;
    sink({ type: "AGENT_RUN_MODEL_CALL_CONTEXT", messages: [] });
    sink({
      type: "AGENT_RUN_MODEL_CALL_CONTEXT",
      messages: [],
      elapsedMs: 7,
      emittedAt: 8,
    });
    assertEquals(events.map(({ elapsedMs, emittedAt }) => ({ elapsedMs, emittedAt })), [
      { elapsedMs: 43, emittedAt: 1_786_866_357_364 },
      { elapsedMs: 7, emittedAt: 8 },
    ]);
  });

  it("rejects invalid present timing instead of silently replacing it", () => {
    const sink = createTimedAgentRunEventSink(() => {}, {
      nowMs: () => 100,
      epochMs: () => 1_786_866_357_364,
      startedMs: 100,
    });

    assertThrows(
      () =>
        sink({
          type: "AGENT_RUN_MODEL_CALL_CONTEXT",
          messages: [],
          elapsedMs: Number.NaN,
        }),
      TypeError,
      "elapsedMs must be a finite non-negative number",
    );
    assertThrows(
      () =>
        sink({
          type: "AGENT_RUN_MODEL_CALL_CONTEXT",
          messages: [],
          emittedAt: 1.5,
        }),
      TypeError,
      "emittedAt must be a non-negative integer",
    );
  });

  it("rejects accessor-backed timing without invoking it", () => {
    let reads = 0;
    let sinkCalls = 0;
    const sink = createTimedAgentRunEventSink(() => {
      sinkCalls += 1;
    });
    const event = Object.defineProperty(
      { type: "AGENT_RUN_MODEL_CALL_CONTEXT", messages: [] },
      "elapsedMs",
      {
        enumerable: true,
        get() {
          reads += 1;
          return 5;
        },
      },
    );

    assertThrows(
      () => sink(event as AgentRunModelCallContextEvent),
      TypeError,
      "elapsedMs must be an own enumerable data property",
    );
    assertEquals(reads, 0);
    assertEquals(sinkCalls, 0);
  });

  it("rejects timing generated by invalid clocks", () => {
    const sink = createTimedAgentRunEventSink(() => {}, {
      nowMs: () => Number.NaN,
      epochMs: () => -1,
      startedMs: 0,
    });
    assertThrows(
      () => sink({ type: "AGENT_RUN_MODEL_CALL_CONTEXT", messages: [] }),
      TypeError,
      "elapsedMs must be a finite non-negative number",
    );

    const wallClockSink = createTimedAgentRunEventSink(() => {}, {
      nowMs: () => 0,
      epochMs: () => -1,
      startedMs: 0,
    });
    assertThrows(
      () => wallClockSink({ type: "AGENT_RUN_MODEL_CALL_CONTEXT", messages: [] }),
      TypeError,
      "emittedAt must be a non-negative integer",
    );
  });
});
