export const SECONDS_PER_MINUTE = 60;

export const MINUTES_PER_HOUR = 60;

export const HOURS_PER_DAY = 24;

export const MS_PER_SECOND = 1000;

export const DEFAULT_LRU_MAX_ENTRIES = 100;

export const COMPONENT_LOADER_MAX_ENTRIES = 100;
export const COMPONENT_LOADER_TTL_MS = 10 * MINUTES_PER_HOUR * MS_PER_SECOND; // 10 minutes

export const MDX_RENDERER_MAX_ENTRIES = 200;
export const MDX_RENDERER_TTL_MS = 10 * MINUTES_PER_HOUR * MS_PER_SECOND; // 10 minutes

export const RENDERER_CORE_MAX_ENTRIES = 100;
export const RENDERER_CORE_TTL_MS = 5 * MINUTES_PER_HOUR * MS_PER_SECOND; // 5 minutes

export const TSX_LAYOUT_MAX_ENTRIES = 50;
export const TSX_LAYOUT_TTL_MS = 10 * MINUTES_PER_HOUR * MS_PER_SECOND; // 10 minutes

export const DATA_FETCHING_MAX_ENTRIES = 200;
export const DATA_FETCHING_TTL_MS = 10 * MINUTES_PER_HOUR * MS_PER_SECOND; // 10 minutes

export const MDX_CACHE_TTL_PRODUCTION_MS = HOURS_PER_DAY * MINUTES_PER_HOUR * SECONDS_PER_MINUTE *
  MS_PER_SECOND; // 24 hours
export const MDX_CACHE_TTL_DEVELOPMENT_MS = 5 * MINUTES_PER_HOUR * MS_PER_SECOND; // 5 minutes

export const BUNDLE_CACHE_TTL_PRODUCTION_MS = HOURS_PER_DAY * MINUTES_PER_HOUR *
  SECONDS_PER_MINUTE * MS_PER_SECOND; // 24 hours
export const BUNDLE_CACHE_TTL_DEVELOPMENT_MS = 5 * MINUTES_PER_HOUR * MS_PER_SECOND; // 5 minutes

export const BUNDLE_MANIFEST_PROD_TTL_MS = 7 * HOURS_PER_DAY * MINUTES_PER_HOUR *
  SECONDS_PER_MINUTE * MS_PER_SECOND; // 7 days
export const BUNDLE_MANIFEST_DEV_TTL_MS = MINUTES_PER_HOUR * SECONDS_PER_MINUTE * MS_PER_SECOND; // 1 hour

export const RSC_MANIFEST_CACHE_TTL_MS = 5000; // 5 seconds in dev

export const SERVER_ACTION_DEFAULT_TTL_SEC = MINUTES_PER_HOUR * SECONDS_PER_MINUTE; // 1 hour

export const DENO_KV_SAFE_SIZE_LIMIT_BYTES = 64_000; // ~64KB

export const HTTP_CACHE_SHORT_MAX_AGE_SEC = 60; // 1 minute
export const HTTP_CACHE_MEDIUM_MAX_AGE_SEC = 3600; // 1 hour
export const HTTP_CACHE_LONG_MAX_AGE_SEC = 31536000; // 1 year (same as HTTP_CACHE_CONTROL.IMMUTABLE)

export const ONE_DAY_MS = HOURS_PER_DAY * MINUTES_PER_HOUR * SECONDS_PER_MINUTE * MS_PER_SECOND;

export const CACHE_CLEANUP_INTERVAL_MS = 60000; // 1 minute

export const LRU_DEFAULT_MAX_ENTRIES = 1000;

export const LRU_DEFAULT_MAX_SIZE_BYTES = 50 * 1024 * 1024; // 50MB

export const CLEANUP_INTERVAL_MULTIPLIER = 2;
