/**
 * Pre-bundled Studio Bridge Script
 *
 * AUTO-GENERATED by scripts/build/prebundle-bridge.ts
 * Do not edit manually — run `deno task build` to regenerate.
 * @module
 */

export const STUDIO_BRIDGE_BUNDLE: string | undefined = undefined;
