{{- if .Values.proxy.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: veryfront-proxy
  labels:
    app: veryfront-proxy
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: veryfront-proxy
{{- end }}
