{{- if .Values.proxy.enabled }}
{{- if .Values.proxy.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "veryfront-renderer.proxy.fullname" . }}
  labels:
    {{- include "veryfront-renderer.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.proxy.ingress.entryPoints | nindent 4 }}
  routes:
    {{- range .Values.proxy.ingress.routes }}
    - kind: Rule
      match: {{ .match }}
      {{- if .priority }}
      priority: {{ .priority }}
      {{- end }}
      services:
        - name: {{ include "veryfront-renderer.proxy.fullname" $ }}
          port: {{ $.Values.proxy.service.port }}
          {{- if $.Values.proxy.ingress.sticky }}
          sticky:
            cookie: {}
          {{- end }}
      {{- if .middlewares }}
      middlewares:
        {{- range .middlewares }}
        - name: {{ .name }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- if .Values.proxy.ingress.tls.enabled }}
  tls:
    secretName: {{ .Values.proxy.ingress.tls.secretName }}
  {{- end }}
{{- end }}
{{- end }}
