{{- if .Values.renderer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "veryfront-renderer.renderer.fullname" . }}
  labels:
    {{- include "veryfront-renderer.labels" . | nindent 4 }}
    {{- include "veryfront-renderer.renderer.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.renderer.replicaCount }}
  selector:
    matchLabels:
      {{- include "veryfront-renderer.renderer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "veryfront-renderer.renderer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: renderer
          image: "{{ .Values.renderer.image.repository }}:{{ .Values.renderer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.renderer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.renderer.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.renderer.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- with .Values.renderer.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.renderer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.renderer.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.renderer.resources | nindent 12 }}
      {{- if .Values.renderer.podAntiAffinity.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "veryfront-renderer.renderer.selectorLabels" . | nindent 20 }}
                topologyKey: {{ .Values.renderer.podAntiAffinity.topologyKey }}
      {{- end }}
{{- end }}
