/**
 * Chat re-export aggregator — single import path for all chat components.
 *
 * @module react/components/chat
 */

// ---------------------------------------------------------------------------
// Core preset + compound
// ---------------------------------------------------------------------------
export { Chat, ChatComponents, type ChatProps } from "./chat/index.tsx";

// ---------------------------------------------------------------------------
// Composition building blocks
// ---------------------------------------------------------------------------
export {
  AgentAvatar,
  type AgentAvatarProps,
  ChatEmpty,
  type ChatEmptyProps,
  ChatEmptyState,
  type ChatEmptyStateAvatarProps,
  type ChatEmptyStateHeadingProps,
  type ChatEmptyStateRootProps,
  type ChatEmptyStateSuggestionProps,
  type ChatEmptyStateSuggestionsProps,
  ChatIf,
  type ChatIfProps,
  ChatInput,
  type ChatInputProps,
  ChatMessageList,
  type ChatMessageListProps,
  ChatRoot,
  type ChatRootProps,
  ErrorBanner,
  type ErrorBannerProps,
  Message,
  type MessageProps,
  type MessageRootProps,
  ModelAvatar,
  type ModelAvatarProps,
} from "./chat/index.tsx";
export {
  type Conversation,
  type ConversationPatch,
  type ConversationStore,
  type ConversationSummary,
  localConversationStore,
  memoryConversationStore,
  type StorageLike,
  useConversations,
  type UseConversationsOptions,
  type UseConversationsResult,
} from "./chat/index.tsx";

// ---------------------------------------------------------------------------
// Contexts
// ---------------------------------------------------------------------------
export {
  ChatContextProvider,
  type ChatContextValue,
  ComposerContextProvider,
  type ComposerContextValue,
  MessageContextProvider,
  type MessageContextValue,
  ThreadListContextProvider,
  type ThreadListContextValue,
  ThreadsProvider,
  type ThreadsProviderProps,
  useChatContext,
  useChatContextOptional,
  useComposerContext,
  useComposerContextOptional,
  useMessageContext,
  useMessageContextOptional,
  useThreadListContext,
  useThreadListContextOptional,
} from "./chat/index.tsx";

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------
export {
  type AttachmentInfo,
  AttachmentPill,
  type AttachmentPillContextValue,
  type AttachmentPillProps,
  AttachmentsPanel,
  type AttachmentsPanelActionProps,
  type AttachmentsPanelContextValue,
  type AttachmentsPanelEmptyProps,
  type AttachmentsPanelHeaderProps,
  type AttachmentsPanelItemProps,
  type AttachmentsPanelListProps,
  type AttachmentsPanelProps,
  BranchPicker,
  type BranchPickerProps,
  ChatMessagesSkeleton,
  type ChatMessagesSkeletonProps,
  ChatSidebar,
  type ChatSidebarComponent,
  type ChatSidebarEmptyProps,
  type ChatSidebarGroupProps,
  type ChatSidebarIcons,
  type ChatSidebarItemProps,
  type ChatSidebarListProps,
  type ChatSidebarNewButtonProps,
  type ChatSidebarProps,
  type ChatSidebarRootProps,
  type ChatSidebarThreadItemRenderOptions,
  type ChatTab,
  type CodeBlockProps,
  ConversationEmptyState,
  type ConversationEmptyStateProps,
  ConversationScrollButton,
  type ConversationScrollButtonProps,
  downloadMarkdown,
  DropZoneOverlay,
  type DropZoneOverlayProps,
  exportAsMarkdown,
  extractSourcesFromParts,
  FadeIn,
  type FeedbackValue,
  getTextContent,
  groupPartsInOrder,
  InferenceBadge,
  type InferenceBadgeProps,
  InlineCitation,
  type InlineCitationProps,
  isReasoningPart,
  isSkillToolPart,
  isToolPart,
  Loader,
  MessageActionBar,
  type MessageActionBarProps,
  MessageEditForm,
  type MessageEditFormProps,
  MessageFeedback,
  type MessageFeedbackProps,
  type PartGroup,
  type QuickAction,
  QuickActions,
  type QuickActionsProps,
  Reasoning,
  ReasoningCard,
  type ReasoningContextValue,
  type ReasoningProps,
  type ReasoningTriggerProps,
  RichCodeBlock,
  Shimmer,
  SkillBadge,
  type SkillBadgeProps,
  type Source,
  SourcePill,
  type SourcePillProps,
  Sources,
  type SourcesContextValue,
  type SourcesListProps,
  type SourcesProps,
  StepIndicator,
  type StepIndicatorContextValue,
  type StepIndicatorProps,
  Suggestion,
  type SuggestionProps,
  Suggestions,
  type SuggestionsProps,
  TabSwitcher,
  type TabSwitcherProps,
  type Thread,
  ToolCall,
  ToolCallCard,
  type ToolCallContextValue,
  type ToolCallProps,
  type ToolCallTriggerProps,
  ToolStatusBadge,
  type UploadedFile,
  useAttachmentPill,
  useAttachmentsPanel,
  useReasoning,
  useSources,
  useStepIndicator,
  useStickToBottom,
  type UseStickToBottomOptions,
  type UseStickToBottomResult,
  useThreads,
  type UseThreadsOptions,
  type UseThreadsResult,
  useToolCall,
  useUpload,
  type UseUploadOptions,
  type UseUploadResult,
  useUploadsRegistry,
  type UseUploadsRegistryOptions,
  type UseUploadsRegistryResult,
} from "./chat/index.tsx";

// ---------------------------------------------------------------------------
// Adjacent components
// ---------------------------------------------------------------------------
export {
  type ModelOption,
  ModelSelector,
  type ModelSelectorContentProps,
  type ModelSelectorContextValue,
  type ModelSelectorItemProps,
  type ModelSelectorProps,
  type ModelSelectorTriggerProps,
  useModelSelector,
} from "./model-selector.tsx";
export {
  ChatWithSidebar,
  type ChatWithSidebarAttachmentConfig,
  type ChatWithSidebarChatController,
  type ChatWithSidebarFeatureConfig,
  type ChatWithSidebarGroupedProps,
  type ChatWithSidebarMessageConfig,
  type ChatWithSidebarModelConfig,
  type ChatWithSidebarProps,
  type ChatWithSidebarQuickActionsConfig,
  type ChatWithSidebarSidebarConfig,
  type ChatWithSidebarTabsConfig,
  type ChatWithSidebarVoiceConfig,
} from "./chat-with-sidebar.tsx";
