/**
 * Chat re-export aggregator — single import path for all chat components.
 *
 * @module react/components/chat
 */

// ---------------------------------------------------------------------------
// Core preset + compound
// ---------------------------------------------------------------------------
export { Chat, type ChatAgentInfo, type ChatProps } from "./chat/index.tsx";

// ---------------------------------------------------------------------------
// Composition building blocks
// ---------------------------------------------------------------------------
export {
  AgentAvatar,
  type AgentAvatarProps,
  ChatEmpty,
  type ChatEmptyProps,
  ChatEmptyState,
  type ChatEmptyStateAvatarProps,
  type ChatEmptyStateHeadingProps,
  type ChatEmptyStateRootProps,
  type ChatEmptyStateSuggestionProps,
  type ChatEmptyStateSuggestionsProps,
  ChatIf,
  type ChatIfProps,
  ChatInput,
  type ChatInputActionProps,
  type ChatInputAttachProps,
  type ChatInputExportProps,
  type ChatInputFieldProps,
  type ChatInputModelProps,
  type ChatInputProps,
  type ChatInputRootProps,
  type ChatInputSendProps,
  type ChatInputSlottedActionProps,
  type ChatInputSlottedSubmitProps,
  type ChatInputStopProps,
  type ChatInputSubmitProps,
  type ChatInputToolbarProps,
  type ChatInputVoiceProps,
  ChatMessageList,
  type ChatMessageListContentProps,
  type ChatMessageListProps,
  ChatRoot,
  type ChatRootProps,
  ErrorBanner,
  type ErrorBannerProps,
  Message,
  type MessageProps,
  type MessageRootProps,
  type MessageTokensProps,
  ModelAvatar,
  type ModelAvatarProps,
  type TokenRowProps,
} from "./chat/index.tsx";
export {
  ChatInputAttach,
  ChatInputExport,
  ChatInputField,
  ChatInputModel,
  ChatInputRoot,
  ChatInputSend,
  ChatInputStop,
  ChatInputSubmit,
  ChatInputToolbar,
  ChatInputVoice,
} from "./chat/composition/api.tsx";
export {
  type ActiveConversationLoadFailure,
  type Conversation,
  CONVERSATION_STORAGE_LIMITS,
  type ConversationPatch,
  ConversationsContextProvider,
  type ConversationsContextValue,
  ConversationsProvider,
  type ConversationsProviderProps,
  type ConversationStorageLimits,
  type ConversationStore,
  ConversationStoreError,
  type ConversationStoreOperation,
  type ConversationSummary,
  localConversationStore,
  memoryConversationStore,
  type StorageLike,
  useConversation,
  useConversationChat,
  type UseConversationChatOptions,
  type UseConversationChatResult,
  type UseConversationOptions,
  type UseConversationPersistenceState,
  type UseConversationResult,
  useConversations,
  type UseConversationsActiveLoadState,
  useConversationsContext,
  useConversationsContextOptional,
  type UseConversationsOptions,
  type UseConversationsPersistenceState,
  type UseConversationsResult,
} from "./chat/index.tsx";

// ---------------------------------------------------------------------------
// Contexts
// ---------------------------------------------------------------------------
export {
  ChatContextProvider,
  type ChatContextValue,
  ChatInputContextProvider,
  type ChatInputContextValue,
  MessageContextProvider,
  type MessageContextValue,
  type MessagePartsData,
  useChatContext,
  useChatContextOptional,
  useChatInputContext,
  useChatInputContextOptional,
  useMessageBranches,
  type UseMessageBranchesResult,
  useMessageContext,
  useMessageContextOptional,
  useMessageParts,
} from "./chat/index.tsx";

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------
export {
  type AttachmentInfo,
  AttachmentPill,
  type AttachmentPillContextValue,
  type AttachmentPillProps,
  AttachmentsPanel,
  type AttachmentsPanelActionProps,
  type AttachmentsPanelContextValue,
  type AttachmentsPanelEmptyProps,
  type AttachmentsPanelHeaderProps,
  type AttachmentsPanelItemProps,
  type AttachmentsPanelListProps,
  type AttachmentsPanelLoadingProps,
  type AttachmentsPanelProps,
  BranchPicker,
  type BranchPickerActionProps,
  type BranchPickerCountProps,
  type BranchPickerProps,
  ChatMessagesSkeleton,
  type ChatMessagesSkeletonProps,
  ChatSidebar,
  type ChatSidebarComponent,
  type ChatSidebarEmptyProps,
  type ChatSidebarGroupProps,
  type ChatSidebarItemProps,
  type ChatSidebarItemTitleProps,
  type ChatSidebarListProps,
  type ChatSidebarNewButtonProps,
  type ChatSidebarProps,
  type ChatSidebarRootProps,
  type ChatTab,
  type CodeBlockProps,
  ConversationEmptyState,
  type ConversationEmptyStateProps,
  ConversationScrollButton,
  type ConversationScrollButtonProps,
  downloadMarkdown,
  DropZoneOverlay,
  type DropZoneOverlayProps,
  exportAsMarkdown,
  extractSourcesFromParts,
  FadeIn,
  type FeedbackValue,
  getTextContent,
  groupPartsInOrder,
  InferenceBadge,
  type InferenceBadgeProps,
  InlineCitation,
  type InlineCitationCardProps,
  type InlineCitationProps,
  type InlineCitationTriggerProps,
  isReasoningPart,
  isSkillToolPart,
  isToolPart,
  Loader,
  MessageActionBar,
  type MessageActionBarActionProps,
  type MessageActionBarProps,
  MessageEditForm,
  type MessageEditFormProps,
  MessageFeedback,
  type MessageFeedbackActionProps,
  type MessageFeedbackProps,
  type PartGroup,
  type QuickAction,
  QuickActions,
  type QuickActionsProps,
  Reasoning,
  type ReasoningContextValue,
  type ReasoningProps,
  type ReasoningTriggerProps,
  RichCodeBlock,
  Shimmer,
  SkillBadge,
  type SkillBadgeProps,
  type Source,
  SourcePill,
  type SourcePillProps,
  Sources,
  type SourcesContextValue,
  type SourcesListProps,
  type SourcesProps,
  StepIndicator,
  type StepIndicatorContextValue,
  type StepIndicatorProps,
  Suggestion,
  type SuggestionProps,
  Suggestions,
  type SuggestionsProps,
  TabSwitcher,
  type TabSwitcherProps,
  ToolCall,
  type ToolCallContextValue,
  type ToolCallProps,
  type ToolCallTriggerProps,
  ToolStatusBadge,
  type UploadedFile,
  useAttachmentPill,
  useAttachments,
  type UseAttachmentsOptions,
  useAttachmentsPanel,
  type UseAttachmentsRequestState,
  type UseAttachmentsResult,
  type UseAttachmentsStorageState,
  useChatSidebarItem,
  useReasoning,
  useSources,
  useStepIndicator,
  useToolCall,
  useUpload,
  type UseUploadOptions,
  type UseUploadResult,
} from "./chat/index.tsx";

export { mergeProps, useChatInput, type UseChatInputResult } from "./chat/hooks/use-chat-input.ts";
export {
  useChatScroll,
  type UseChatScrollOptions,
  type UseChatScrollResult,
} from "./chat/hooks/use-stick-to-bottom.ts";

// ---------------------------------------------------------------------------
// Adjacent components
// ---------------------------------------------------------------------------
export {
  type ModelOption,
  ModelSelector,
  type ModelSelectorContentProps,
  type ModelSelectorContextValue,
  type ModelSelectorItemProps,
  type ModelSelectorProps,
  type ModelSelectorSearchProps,
  type ModelSelectorTriggerProps,
  useModelSelector,
} from "./model-selector.tsx";
