import * as dntShim from "../../../_dnt.shims.js";
const noop = () => { };
const noopTrue = () => true;
const noopFalse = () => false;
const noopNull = () => null;
const noopEmptyArray = () => [];
const emptyString = "";
const createClassListStub = () => ({
    add: noop,
    remove: noop,
    contains: noopFalse,
    toggle: noopFalse,
});
export function createElementStub() {
    return {
        style: {},
        classList: createClassListStub(),
        dataset: {},
        setAttribute: noop,
        getAttribute: noopNull,
        removeAttribute: noop,
        hasAttribute: noopFalse,
        appendChild: noop,
        removeChild: noop,
        insertBefore: noop,
        replaceChild: noop,
        cloneNode: () => createElementStub(),
        addEventListener: noop,
        removeEventListener: noop,
        querySelector: noopNull,
        querySelectorAll: noopEmptyArray,
        getBoundingClientRect: () => ({
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            width: 0,
            height: 0,
        }),
        offsetWidth: 0,
        offsetHeight: 0,
        scrollWidth: 0,
        scrollHeight: 0,
        clientWidth: 0,
        clientHeight: 0,
        innerHTML: emptyString,
        outerHTML: emptyString,
        textContent: emptyString,
        innerText: emptyString,
        children: [],
        childNodes: [],
        parentNode: null,
        parentElement: null,
        nextSibling: null,
        previousSibling: null,
        firstChild: null,
        lastChild: null,
    };
}
export function createDocumentStub() {
    const classList = {
        add: noop,
        remove: noop,
        contains: noopFalse,
    };
    return {
        __veryfrontSSRStub: true,
        exitFullscreen: undefined,
        webkitExitFullscreen: undefined,
        mozCancelFullScreen: undefined,
        msExitFullscreen: undefined,
        fullscreenElement: null,
        webkitFullscreenElement: null,
        mozFullScreenElement: null,
        msFullscreenElement: null,
        createElement: () => createElementStub(),
        createElementNS: () => createElementStub(),
        createTextNode: () => ({ textContent: emptyString }),
        querySelector: noopNull,
        querySelectorAll: noopEmptyArray,
        getElementById: noopNull,
        getElementsByClassName: noopEmptyArray,
        getElementsByTagName: noopEmptyArray,
        getElementsByName: noopEmptyArray,
        documentElement: { style: {}, classList },
        body: { style: {}, classList, appendChild: noop },
        head: { appendChild: noop, removeChild: noop },
        readyState: "complete",
        cookie: emptyString,
        domain: emptyString,
        referrer: emptyString,
        title: emptyString,
        URL: emptyString,
        location: { href: emptyString, pathname: "/", search: emptyString, hash: emptyString },
        addEventListener: noop,
        removeEventListener: noop,
        dispatchEvent: noopTrue,
        styleSheets: [],
        adoptedStyleSheets: [],
    };
}
export function createWindowStub() {
    return {
        __veryfrontSSRStub: true,
        document: createDocumentStub(),
        navigator: {
            userAgent: "SSR",
            language: "en-US",
            languages: ["en-US"],
            platform: "SSR",
            vendor: emptyString,
            onLine: true,
            cookieEnabled: false,
            mediaDevices: { getUserMedia: () => Promise.reject(new Error("SSR")) },
        },
        location: {
            href: emptyString,
            pathname: "/",
            search: emptyString,
            hash: emptyString,
            origin: emptyString,
            protocol: "https:",
            host: emptyString,
            hostname: emptyString,
            port: emptyString,
            assign: noop,
            replace: noop,
            reload: noop,
        },
        history: {
            length: 0,
            state: null,
            pushState: noop,
            replaceState: noop,
            go: noop,
            back: noop,
            forward: noop,
        },
        innerWidth: 1024,
        innerHeight: 768,
        outerWidth: 1024,
        outerHeight: 768,
        screenX: 0,
        screenY: 0,
        pageXOffset: 0,
        pageYOffset: 0,
        scrollX: 0,
        scrollY: 0,
        devicePixelRatio: 1,
        setTimeout: dntShim.dntGlobalThis.setTimeout,
        clearTimeout: globalThis.clearTimeout,
        setInterval: dntShim.dntGlobalThis.setInterval,
        clearInterval: globalThis.clearInterval,
        requestAnimationFrame: (cb) => dntShim.dntGlobalThis.setTimeout(cb, 16),
        cancelAnimationFrame: globalThis.clearTimeout,
        localStorage: {
            getItem: noopNull,
            setItem: noop,
            removeItem: noop,
            clear: noop,
            length: 0,
            key: noopNull,
        },
        sessionStorage: {
            getItem: noopNull,
            setItem: noop,
            removeItem: noop,
            clear: noop,
            length: 0,
            key: noopNull,
        },
        addEventListener: noop,
        removeEventListener: noop,
        dispatchEvent: noopTrue,
        matchMedia: (query) => ({
            matches: false,
            media: query,
            onchange: null,
            addListener: noop,
            removeListener: noop,
            addEventListener: noop,
            removeEventListener: noop,
            dispatchEvent: noopTrue,
        }),
        getComputedStyle: () => ({ getPropertyValue: () => emptyString }),
        getSelection: noopNull,
        print: noop,
        alert: noop,
        confirm: noopFalse,
        prompt: noopNull,
        open: noopNull,
        close: noop,
        focus: noop,
        blur: noop,
        scroll: noop,
        scrollTo: noop,
        scrollBy: noop,
        resizeTo: noop,
        resizeBy: noop,
        moveTo: noop,
        moveBy: noop,
        crypto: dntShim.dntGlobalThis.crypto,
        performance: globalThis.performance,
        fetch: dntShim.dntGlobalThis.fetch,
        URL: globalThis.URL,
        URLSearchParams: globalThis.URLSearchParams,
        TextEncoder: globalThis.TextEncoder,
        TextDecoder: globalThis.TextDecoder,
    };
}
// deno-lint-ignore no-explicit-any
export function createElementClass(name) {
    const ElementClass = class {
    };
    Object.defineProperty(ElementClass, "name", { value: name });
    return ElementClass;
}
