import * as dntShim from "../../../_dnt.shims.js";
declare const createClassListStub: () => {
    add: () => void;
    remove: () => void;
    contains: () => false;
    toggle: () => false;
};
export declare function createElementStub(): {
    style: Record<string, unknown>;
    classList: ReturnType<typeof createClassListStub>;
    dataset: Record<string, unknown>;
    setAttribute: () => void;
    getAttribute: () => null;
    removeAttribute: () => void;
    hasAttribute: () => false;
    appendChild: () => void;
    removeChild: () => void;
    insertBefore: () => void;
    replaceChild: () => void;
    cloneNode: () => ReturnType<typeof createElementStub>;
    addEventListener: () => void;
    removeEventListener: () => void;
    querySelector: () => null;
    querySelectorAll: () => [];
    getBoundingClientRect: () => {
        top: number;
        left: number;
        right: number;
        bottom: number;
        width: number;
        height: number;
    };
    offsetWidth: number;
    offsetHeight: number;
    scrollWidth: number;
    scrollHeight: number;
    clientWidth: number;
    clientHeight: number;
    innerHTML: string;
    outerHTML: string;
    textContent: string;
    innerText: string;
    children: [];
    childNodes: [];
    parentNode: null;
    parentElement: null;
    nextSibling: null;
    previousSibling: null;
    firstChild: null;
    lastChild: null;
};
export declare function createDocumentStub(): {
    __veryfrontSSRStub: true;
    exitFullscreen: undefined;
    webkitExitFullscreen: undefined;
    mozCancelFullScreen: undefined;
    msExitFullscreen: undefined;
    fullscreenElement: null;
    webkitFullscreenElement: null;
    mozFullScreenElement: null;
    msFullscreenElement: null;
    createElement: () => ReturnType<typeof createElementStub>;
    createElementNS: () => ReturnType<typeof createElementStub>;
    createTextNode: () => {
        textContent: string;
    };
    querySelector: () => null;
    querySelectorAll: () => [];
    getElementById: () => null;
    getElementsByClassName: () => [];
    getElementsByTagName: () => [];
    getElementsByName: () => [];
    documentElement: {
        style: Record<string, unknown>;
        classList: Omit<ReturnType<typeof createClassListStub>, "toggle">;
    };
    body: {
        style: Record<string, unknown>;
        classList: Omit<ReturnType<typeof createClassListStub>, "toggle">;
        appendChild: () => void;
    };
    head: {
        appendChild: () => void;
        removeChild: () => void;
    };
    readyState: "complete";
    cookie: string;
    domain: string;
    referrer: string;
    title: string;
    URL: string;
    location: {
        href: string;
        pathname: string;
        search: string;
        hash: string;
    };
    addEventListener: () => void;
    removeEventListener: () => void;
    dispatchEvent: () => true;
    styleSheets: [];
    adoptedStyleSheets: [];
};
export declare function createWindowStub(): {
    __veryfrontSSRStub: true;
    document: ReturnType<typeof createDocumentStub>;
    navigator: {
        userAgent: string;
        language: string;
        languages: string[];
        platform: string;
        vendor: string;
        onLine: true;
        cookieEnabled: false;
        mediaDevices: {
            getUserMedia: () => Promise<never>;
        };
    };
    location: {
        href: string;
        pathname: string;
        search: string;
        hash: string;
        origin: string;
        protocol: string;
        host: string;
        hostname: string;
        port: string;
        assign: () => void;
        replace: () => void;
        reload: () => void;
    };
    history: {
        length: number;
        state: null;
        pushState: () => void;
        replaceState: () => void;
        go: () => void;
        back: () => void;
        forward: () => void;
    };
    innerWidth: number;
    innerHeight: number;
    outerWidth: number;
    outerHeight: number;
    screenX: number;
    screenY: number;
    pageXOffset: number;
    pageYOffset: number;
    scrollX: number;
    scrollY: number;
    devicePixelRatio: number;
    setTimeout: typeof dntShim.setTimeout;
    clearTimeout: typeof globalThis.clearTimeout;
    setInterval: typeof dntShim.setInterval;
    clearInterval: typeof globalThis.clearInterval;
    requestAnimationFrame: (cb: () => void) => ReturnType<typeof dntShim.setTimeout>;
    cancelAnimationFrame: typeof globalThis.clearTimeout;
    localStorage: {
        getItem: () => null;
        setItem: () => void;
        removeItem: () => void;
        clear: () => void;
        length: number;
        key: () => null;
    };
    sessionStorage: {
        getItem: () => null;
        setItem: () => void;
        removeItem: () => void;
        clear: () => void;
        length: number;
        key: () => null;
    };
    addEventListener: () => void;
    removeEventListener: () => void;
    dispatchEvent: () => true;
    matchMedia: (query: string) => {
        matches: false;
        media: string;
        onchange: null;
        addListener: () => void;
        removeListener: () => void;
        addEventListener: () => void;
        removeEventListener: () => void;
        dispatchEvent: () => true;
    };
    getComputedStyle: () => {
        getPropertyValue: () => string;
    };
    getSelection: () => null;
    print: () => void;
    alert: () => void;
    confirm: () => false;
    prompt: () => null;
    open: () => null;
    close: () => void;
    focus: () => void;
    blur: () => void;
    scroll: () => void;
    scrollTo: () => void;
    scrollBy: () => void;
    resizeTo: () => void;
    resizeBy: () => void;
    moveTo: () => void;
    moveBy: () => void;
    crypto: typeof dntShim.crypto;
    performance: typeof globalThis.performance;
    fetch: typeof dntShim.fetch;
    URL: typeof globalThis.URL;
    URLSearchParams: typeof globalThis.URLSearchParams;
    TextEncoder: typeof globalThis.TextEncoder;
    TextDecoder: typeof globalThis.TextDecoder;
};
export declare function createElementClass(name: string): any;
export {};
//# sourceMappingURL=dom-stubs.d.ts.map