/**
 * The Runs target contract types (veryfront-issue-inbox#2233) are generated by
 * veryfront-api from its shared Zod schemas and pinned by content hash
 * (tests/integration/contracts/runs-target-types.test.ts). SDK and CLI code types its
 * Runs calls against them instead of hand-written copies.
 */
import { assertEquals } from "#veryfront/testing/assert.ts";
import { describe, it } from "#veryfront/testing/bdd.ts";
import type { components } from "./runs-api.generated.ts";

type Schemas = components["schemas"];
type Lacks<T, K extends PropertyKey> = K extends keyof T ? false : true;
type Expect<T extends true> = T;
type PayloadOf<T extends string> = Extract<Schemas["RunEvent"], { event_type: T }>["payload"];
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true
  : false;
type NotNever<T> = [T] extends [never] ? false : true;

// Compile-time checks: `deno test` type-checks this file.
export type RunsContractTypeChecks = [
  Expect<Lacks<Schemas["Run"], "run_id">>,
  Expect<Lacks<Schemas["Run"], "source">>,
  // A missing event would make the payload `never`, which every type extends.
  Expect<NotNever<PayloadOf<"MODEL_CALL_COMPLETED">>>,
  Expect<Equal<PayloadOf<"MODEL_CALL_COMPLETED">, Schemas["ModelCallCompletedPayload"]>>,
];

describe("Runs target contract types", () => {
  it("type a child run request by the contract", () => {
    const child = {
      project_id: "00000000-0000-4000-8000-000000000001",
      target: { type: "agent", id: "coordinator" },
      parent_run_id: "11111111-1111-4111-8111-111111111111",
      node_id: "research",
    } satisfies Schemas["CreateRunRequest"];
    assertEquals(child.target.type, "agent");
  });
});
