// Generated by scripts/generate-runs-fixtures.ts. Do not edit.
import type { RunsOperationId } from "../target/client.ts";
import type { RunsOperationFixture } from "../target/client.test-helpers.ts";

export const RUNS_OPERATION_FIXTURES: { [K in RunsOperationId]: RunsOperationFixture<K> } = {
  "listRuns": {
    input: {},
    url: "/runs",
    response: {
      status: 200,
      body: {
        "data": [
          {
            "id": "11111111-1111-4111-8111-111111111111",
            "status": "completed",
            "project_id": "00000000-0000-4000-8000-000000000001",
            "target": {
              "type": "task",
              "id": "summarize",
            },
            "input": {
              "text": "A short document.",
            },
            "output": {
              "summary": "A short summary.",
            },
            "title": "Summarize text",
            "created_at": "2026-10-02T10:00:00Z",
            "updated_at": "2026-10-02T10:00:02Z",
            "trigger": {
              "type": "api_key",
              "id": "key_example",
            },
            "started_at": "2026-10-02T10:00:00Z",
            "finished_at": "2026-10-02T10:00:02Z",
          },
        ],
        "page_info": {
          "next": null,
        },
      },
    },
  },
  "createRun": {
    input: {
      "headers": {
        "Idempotency-Key": "example-request-1",
      },
      "body": {
        "project_id": "00000000-0000-4000-8000-000000000001",
        "target": {
          "type": "task",
          "id": "health-check",
        },
      },
    },
    url: "/runs",
    response: {
      status: 202,
      body: {
        "id": "11111111-1111-4111-8111-111111111111",
        "status": "pending",
        "project_id": "00000000-0000-4000-8000-000000000001",
        "target": {
          "type": "task",
          "id": "health-check",
        },
        "input": null,
        "output": null,
        "created_at": "2026-10-02T10:00:00Z",
        "updated_at": "2026-10-02T10:00:02Z",
        "trigger": {
          "type": "api_key",
          "id": "key_example",
        },
      },
    },
  },
  "getRun": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111",
    response: {
      status: 200,
      body: {
        "id": "11111111-1111-4111-8111-111111111111",
        "status": "completed",
        "project_id": "00000000-0000-4000-8000-000000000001",
        "target": {
          "type": "task",
          "id": "summarize",
        },
        "input": {
          "text": "A short document.",
        },
        "output": {
          "summary": "A short summary.",
        },
        "title": "Summarize text",
        "created_at": "2026-10-02T10:00:00Z",
        "updated_at": "2026-10-02T10:00:02Z",
        "trigger": {
          "type": "api_key",
          "id": "key_example",
        },
        "started_at": "2026-10-02T10:00:00Z",
        "finished_at": "2026-10-02T10:00:02Z",
      },
    },
  },
  "updateRun": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
      "headers": {
        "If-Match": '"run-version-1"',
      },
      "body": {
        "title": "Summarize text",
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111",
    response: {
      status: 200,
      body: {
        "id": "11111111-1111-4111-8111-111111111111",
        "status": "completed",
        "project_id": "00000000-0000-4000-8000-000000000001",
        "target": {
          "type": "task",
          "id": "summarize",
        },
        "input": {
          "text": "A short document.",
        },
        "output": {
          "summary": "A short summary.",
        },
        "title": "Summarize text",
        "created_at": "2026-10-02T10:00:00Z",
        "updated_at": "2026-10-02T10:00:02Z",
        "trigger": {
          "type": "api_key",
          "id": "key_example",
        },
        "started_at": "2026-10-02T10:00:00Z",
        "finished_at": "2026-10-02T10:00:02Z",
      },
    },
  },
  "deleteRun": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111",
    response: { status: 204, body: undefined },
  },
  "cancelRun": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
      "headers": {
        "Idempotency-Key": "example-request-1",
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/cancel",
    response: {
      status: 202,
      body: {
        "id": "11111111-1111-4111-8111-111111111111",
        "status": "running",
        "project_id": "00000000-0000-4000-8000-000000000001",
        "target": {
          "type": "task",
          "id": "summarize",
        },
        "input": {
          "text": "A short document.",
        },
        "output": null,
        "title": "Summarize text",
        "created_at": "2026-10-02T10:00:00Z",
        "updated_at": "2026-10-02T10:00:02Z",
        "trigger": {
          "type": "api_key",
          "id": "key_example",
        },
        "started_at": "2026-10-02T10:00:00Z",
        "control": {
          "cancellation": {
            "requested_at": "2026-10-02T10:00:00Z",
            "stopped_at": null,
          },
        },
      },
    },
  },
  "resumeRun": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
      "headers": {
        "Idempotency-Key": "example-request-1",
      },
      "body": {
        "type": "manual",
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/resume",
    response: {
      status: 202,
      body: {
        "id": "11111111-1111-4111-8111-111111111111",
        "status": "pending",
        "project_id": "00000000-0000-4000-8000-000000000001",
        "target": {
          "type": "task",
          "id": "summarize",
        },
        "input": {
          "text": "A short document.",
        },
        "output": null,
        "title": "Summarize text",
        "created_at": "2026-10-02T10:00:00Z",
        "updated_at": "2026-10-02T10:00:02Z",
        "trigger": {
          "type": "api_key",
          "id": "key_example",
        },
      },
    },
  },
  "listProjectRuns": {
    input: {
      "path": {
        "project_reference": "example",
      },
    },
    url: "/projects/example/runs",
    response: {
      status: 200,
      body: {
        "data": [
          {
            "id": "11111111-1111-4111-8111-111111111111",
            "status": "completed",
            "project_id": "00000000-0000-4000-8000-000000000001",
            "target": {
              "type": "task",
              "id": "summarize",
            },
            "input": {
              "text": "A short document.",
            },
            "output": {
              "summary": "A short summary.",
            },
            "title": "Summarize text",
            "created_at": "2026-10-02T10:00:00Z",
            "updated_at": "2026-10-02T10:00:02Z",
            "trigger": {
              "type": "api_key",
              "id": "key_example",
            },
            "started_at": "2026-10-02T10:00:00Z",
            "finished_at": "2026-10-02T10:00:02Z",
          },
        ],
        "page_info": {
          "next": null,
        },
      },
    },
  },
  "listConversationRuns": {
    input: {
      "path": {
        "conversation_id": "00000000-0000-4000-8000-000000000001",
      },
    },
    url: "/conversations/00000000-0000-4000-8000-000000000001/runs",
    response: {
      status: 200,
      body: {
        "data": [
          {
            "id": "11111111-1111-4111-8111-111111111111",
            "status": "completed",
            "project_id": "00000000-0000-4000-8000-000000000001",
            "target": {
              "type": "task",
              "id": "summarize",
            },
            "input": {
              "text": "A short document.",
            },
            "output": {
              "summary": "A short summary.",
            },
            "title": "Summarize text",
            "created_at": "2026-10-02T10:00:00Z",
            "updated_at": "2026-10-02T10:00:02Z",
            "trigger": {
              "type": "api_key",
              "id": "key_example",
            },
            "started_at": "2026-10-02T10:00:00Z",
            "finished_at": "2026-10-02T10:00:02Z",
          },
        ],
        "page_info": {
          "next": null,
        },
      },
    },
  },
  "getAccountRunAnalytics": {
    input: {},
    url: "/account/analytics/runs",
    response: {
      status: 200,
      body: {
        "summary": {
          "total_runs": 0,
          "completed_runs": 0,
          "failed_runs": 0,
          "average_duration_ms": null,
          "p95_duration_ms": null,
          "last_run_at": null,
        },
        "timeframe": {
          "from": "2026-10-01T00:00:00Z",
          "to": "2026-10-02T00:00:00Z",
          "granularity": "day",
          "timezone": "UTC",
          "bucket_count": 1,
        },
        "series": [],
        "statuses": [],
        "models": [],
        "tools": [],
        "projects": [],
        "recent_runs": [],
      },
    },
  },
  "listRunEvents": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/events",
    response: {
      status: 200,
      body: {
        "data": [
          {
            "event_id": 42,
            "event_type": "MODEL_CALL_COMPLETED",
            "payload": {
              "type": "MODEL_CALL_COMPLETED",
              "provider": "example-provider",
              "model": "example-model",
              "inputTokens": 120,
              "outputTokens": 30,
              "cacheCreationTokens": 0,
              "cacheReadTokens": 0,
              "totalTokens": 150,
              "costCredits": "0.001",
              "latencyMs": 800,
              "usageCaptureStatus": "complete",
              "providerRequestId": "request_example",
              "modelCallContextEventId": null,
            },
            "is_error": false,
            "created_at": "2026-10-02T10:00:00Z",
            "run_id": "11111111-1111-4111-8111-111111111111",
            "event_class": "fact",
            "span_id": "span_example",
            "parent_span_id": null,
            "turn_id": null,
            "origin_event_type": "MODEL_CALL_COMPLETED",
            "origin_custom_name": null,
            "unrecoverable_fields": [],
          },
        ],
        "page_info": {
          "next": null,
        },
      },
    },
  },
  "appendRunEvents": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
      "body": {
        "events": [
          {
            "type": "MODEL_CALL_COMPLETED",
            "provider": "example-provider",
            "model": "example-model",
            "inputTokens": 120,
            "outputTokens": 30,
            "cacheCreationTokens": 0,
            "cacheReadTokens": 0,
            "totalTokens": 150,
            "costCredits": "0.001",
            "latencyMs": 800,
            "usageCaptureStatus": "complete",
            "providerRequestId": "request_example",
            "modelCallContextEventId": null,
          },
        ],
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/events",
    response: {
      status: 200,
      body: {
        "run_id": "11111111-1111-4111-8111-111111111111",
        "latest_event_id": 42,
        "appended_count": 1,
      },
    },
  },
  "getRunEvent": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
        "event_id": 1,
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/events/1",
    response: {
      status: 200,
      body: {
        "event_id": 42,
        "event_type": "MODEL_CALL_COMPLETED",
        "payload": {
          "type": "MODEL_CALL_COMPLETED",
          "provider": "example-provider",
          "model": "example-model",
          "inputTokens": 120,
          "outputTokens": 30,
          "cacheCreationTokens": 0,
          "cacheReadTokens": 0,
          "totalTokens": 150,
          "costCredits": "0.001",
          "latencyMs": 800,
          "usageCaptureStatus": "complete",
          "providerRequestId": "request_example",
          "modelCallContextEventId": null,
        },
        "is_error": false,
        "created_at": "2026-10-02T10:00:00Z",
        "run_id": "11111111-1111-4111-8111-111111111111",
        "event_class": "fact",
        "span_id": "span_example",
        "parent_span_id": null,
        "turn_id": null,
        "origin_event_type": "MODEL_CALL_COMPLETED",
        "origin_custom_name": null,
        "unrecoverable_fields": [],
      },
    },
  },
  "getRunEventsSummary": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/events/summary",
    response: {
      status: 200,
      body: {
        "run_id": "11111111-1111-4111-8111-111111111111",
        "total": 0,
        "error_count": 0,
        "first_event_id": null,
        "last_event_id": null,
        "first_event_at": null,
        "last_event_at": null,
        "by_event_class": {
          "fact": 0,
          "delta": 0,
        },
        "by_event_type": [],
        "buckets": [],
      },
    },
  },
  "getRunSnapshot": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/snapshot",
    response: {
      status: 200,
      body: {
        "after_event_id": 42,
        "events": [
          {
            "event_id": 42,
            "event_type": "MODEL_CALL_COMPLETED",
            "payload": {
              "type": "MODEL_CALL_COMPLETED",
              "provider": "example-provider",
              "model": "example-model",
              "inputTokens": 120,
              "outputTokens": 30,
              "cacheCreationTokens": 0,
              "cacheReadTokens": 0,
              "totalTokens": 150,
              "costCredits": "0.001",
              "latencyMs": 800,
              "usageCaptureStatus": "complete",
              "providerRequestId": "request_example",
              "modelCallContextEventId": null,
            },
            "is_error": false,
            "created_at": "2026-10-02T10:00:00Z",
            "run_id": "11111111-1111-4111-8111-111111111111",
            "event_class": "fact",
            "span_id": "span_example",
            "parent_span_id": null,
            "turn_id": null,
            "origin_event_type": "MODEL_CALL_COMPLETED",
            "origin_custom_name": null,
            "unrecoverable_fields": [],
          },
        ],
      },
    },
  },
  "streamRunEvents": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
      "headers": {
        "Last-Event-ID": "example",
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/stream",
    response: {
      status: 200,
      body:
        'id: 42\ndata: {"type":"MODEL_CALL_COMPLETED","provider":"example-provider","model":"example-model","inputTokens":120,"outputTokens":30,"cacheCreationTokens":0,"cacheReadTokens":0,"totalTokens":150,"costCredits":"0.001","latencyMs":800,"usageCaptureStatus":"complete","providerRequestId":"request_example","modelCallContextEventId":null}\n\n',
    },
  },
  "listRunEventTypes": {
    input: {},
    url: "/runs/event-types",
    response: {
      status: 200,
      body: {
        "data": [
          {
            "type": "MODEL_CALL_COMPLETED",
            "name": "Model call completed",
            "group": "Model",
            "scope": "ag-ui",
            "event_class": "fact",
            "status": "active",
            "viewer_visibility": "full",
            "description": "Records model usage after a completed call.",
            "fields": [
              "provider",
              "model",
              "inputTokens",
              "outputTokens",
              "cacheCreationTokens",
              "cacheReadTokens",
              "totalTokens",
              "costCredits",
              "latencyMs",
              "usageCaptureStatus",
              "providerRequestId",
              "modelCallContextEventId",
            ],
          },
        ],
      },
    },
  },
  "listRunInputRequests": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/input-requests",
    response: {
      status: 200,
      body: {
        "data": [
          {
            "input_request_id": "00000000-0000-4000-8000-000000000001",
            "project_id": "00000000-0000-4000-8000-000000000001",
            "run_id": "11111111-1111-4111-8111-111111111111",
            "title": "Approve the result",
            "fields": [
              {
                "name": "approved",
                "type": "confirm",
                "label": "Approve the result?",
                "required": true,
              },
            ],
            "status": "open",
            "requested_responder_type": "human",
            "response": null,
            "created_at": "2026-10-02T10:00:00Z",
          },
        ],
        "page_info": {
          "next": null,
        },
      },
    },
  },
  "createRunInputRequest": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
      "headers": {
        "Idempotency-Key": "example-request-1",
      },
      "body": {
        "title": "Approve the result",
        "fields": [
          {
            "name": "approved",
            "type": "confirm",
            "required": false,
          },
        ],
        "requested_responder_type": "human",
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/input-requests",
    response: {
      status: 201,
      body: {
        "input_request_id": "00000000-0000-4000-8000-000000000001",
        "project_id": "00000000-0000-4000-8000-000000000001",
        "run_id": "11111111-1111-4111-8111-111111111111",
        "title": "Approve the result",
        "fields": [
          {
            "required": false,
            "name": "approved",
            "type": "confirm",
          },
        ],
        "status": "open",
        "requested_responder_type": "human",
        "response": null,
        "created_at": "2026-10-02T10:00:00Z",
      },
    },
  },
  "listConversationInputRequests": {
    input: {
      "path": {
        "conversation_id": "00000000-0000-4000-8000-000000000001",
      },
    },
    url: "/conversations/00000000-0000-4000-8000-000000000001/input-requests",
    response: {
      status: 200,
      body: {
        "data": [
          {
            "input_request_id": "00000000-0000-4000-8000-000000000001",
            "project_id": "00000000-0000-4000-8000-000000000001",
            "run_id": "11111111-1111-4111-8111-111111111111",
            "title": "Approve the result",
            "fields": [
              {
                "name": "approved",
                "type": "confirm",
                "label": "Approve the result?",
                "required": true,
              },
            ],
            "status": "open",
            "requested_responder_type": "human",
            "response": null,
            "created_at": "2026-10-02T10:00:00Z",
          },
        ],
        "page_info": {
          "next": null,
        },
      },
    },
  },
  "listProjectWebhookRuns": {
    input: {
      "path": {
        "project_reference": "example",
        "webhook_definition_id": "00000000-0000-4000-8000-000000000001",
      },
    },
    url: "/projects/example/webhooks/00000000-0000-4000-8000-000000000001/runs",
    response: {
      status: 200,
      body: {
        "data": [
          {
            "id": "11111111-1111-4111-8111-111111111111",
            "status": "completed",
            "project_id": "00000000-0000-4000-8000-000000000001",
            "target": {
              "type": "task",
              "id": "summarize",
            },
            "input": {
              "text": "A short document.",
            },
            "output": {
              "summary": "A short summary.",
            },
            "title": "Summarize text",
            "created_at": "2026-10-02T10:00:00Z",
            "updated_at": "2026-10-02T10:00:02Z",
            "trigger": {
              "type": "webhook",
              "id": "webhook_definition_example",
            },
            "started_at": "2026-10-02T10:00:00Z",
            "finished_at": "2026-10-02T10:00:02Z",
          },
        ],
        "page_info": {
          "next": null,
        },
      },
    },
  },
  "listEvalRuns": {
    input: {
      "path": {
        "project_reference": "example",
        "eval_id": "eval_example",
      },
    },
    url: "/projects/example/evals/eval_example/runs",
    response: {
      status: 200,
      body: {
        "data": [
          {
            "id": "11111111-1111-4111-8111-111111111111",
            "status": "completed",
            "project_id": "00000000-0000-4000-8000-000000000001",
            "target": {
              "type": "task",
              "id": "eval",
            },
            "input": {
              "text": "A short document.",
            },
            "output": {
              "report_storage": "inline",
              "report": {
                "schema_version": 1,
                "run_id": "11111111-1111-4111-8111-111111111111",
                "eval_id": "eval_example",
                "target": "summarize",
                "started_at": "2026-10-02T10:00:00Z",
                "completed_at": "2026-10-02T10:00:02Z",
                "summary": {
                  "records": 0,
                  "passed": 0,
                  "failed": 0,
                  "skipped": 0,
                  "pass_rate": 0,
                },
                "records": [],
              },
            },
            "title": "Summarize text",
            "created_at": "2026-10-02T10:00:00Z",
            "updated_at": "2026-10-02T10:00:02Z",
            "trigger": {
              "type": "api_key",
              "id": "key_example",
            },
            "started_at": "2026-10-02T10:00:00Z",
            "finished_at": "2026-10-02T10:00:02Z",
          },
        ],
        "page_info": {
          "next": null,
        },
      },
    },
  },
  "getInputRequest": {
    input: {
      "path": {
        "input_request_id": "00000000-0000-4000-8000-000000000001",
      },
    },
    url: "/input-requests/00000000-0000-4000-8000-000000000001",
    response: {
      status: 200,
      body: {
        "input_request_id": "00000000-0000-4000-8000-000000000001",
        "project_id": "00000000-0000-4000-8000-000000000001",
        "run_id": "11111111-1111-4111-8111-111111111111",
        "title": "Approve the result",
        "fields": [
          {
            "name": "approved",
            "type": "confirm",
            "label": "Approve the result?",
            "required": true,
          },
        ],
        "status": "open",
        "requested_responder_type": "human",
        "response": null,
        "created_at": "2026-10-02T10:00:00Z",
      },
    },
  },
  "createInputResponse": {
    input: {
      "path": {
        "input_request_id": "00000000-0000-4000-8000-000000000001",
      },
      "headers": {
        "Idempotency-Key": "example-request-1",
      },
      "body": {
        "values": {
          "approved": true,
        },
      },
    },
    url: "/input-requests/00000000-0000-4000-8000-000000000001/responses",
    response: {
      status: 200,
      body: {
        "input_request_id": "00000000-0000-4000-8000-000000000001",
        "project_id": "00000000-0000-4000-8000-000000000001",
        "run_id": "11111111-1111-4111-8111-111111111111",
        "title": "Approve the result",
        "fields": [
          {
            "name": "approved",
            "type": "confirm",
            "label": "Approve the result?",
            "required": true,
          },
        ],
        "status": "submitted",
        "requested_responder_type": "human",
        "response": {
          "response_id": "00000000-0000-4000-8000-000000000002",
          "values": {
            "approved": true,
          },
          "actor": {
            "type": "user",
            "id": "user_example",
          },
          "created_at": "2026-10-02T10:00:00Z",
        },
        "created_at": "2026-10-02T10:00:00Z",
        "resolved_at": "2026-10-02T10:00:00Z",
      },
    },
  },
  "cancelInputRequest": {
    input: {
      "path": {
        "input_request_id": "00000000-0000-4000-8000-000000000001",
      },
      "headers": {
        "Idempotency-Key": "example-request-1",
      },
    },
    url: "/input-requests/00000000-0000-4000-8000-000000000001/cancel",
    response: {
      status: 200,
      body: {
        "input_request_id": "00000000-0000-4000-8000-000000000001",
        "project_id": "00000000-0000-4000-8000-000000000001",
        "run_id": "11111111-1111-4111-8111-111111111111",
        "title": "Approve the result",
        "fields": [
          {
            "name": "approved",
            "type": "confirm",
            "label": "Approve the result?",
            "required": true,
          },
        ],
        "status": "cancelled",
        "requested_responder_type": "human",
        "response": null,
        "created_at": "2026-10-02T10:00:00Z",
        "resolved_at": "2026-10-02T10:00:00Z",
      },
    },
  },
  "pauseRun": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
      "headers": {
        "Idempotency-Key": "example-request-1",
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/pause",
    response: {
      status: 202,
      body: {
        "id": "11111111-1111-4111-8111-111111111111",
        "status": "running",
        "project_id": "00000000-0000-4000-8000-000000000001",
        "target": {
          "type": "task",
          "id": "summarize",
        },
        "input": {
          "text": "A short document.",
        },
        "output": null,
        "title": "Summarize text",
        "created_at": "2026-10-02T10:00:00Z",
        "updated_at": "2026-10-02T10:00:02Z",
        "trigger": {
          "type": "api_key",
          "id": "key_example",
        },
        "started_at": "2026-10-02T10:00:00Z",
        "control": {
          "pause": {
            "requested_at": "2026-10-02T10:00:00Z",
          },
        },
      },
    },
  },
  "finalizeRun": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
      "headers": {
        "Idempotency-Key": "example-request-1",
      },
      "body": {
        "status": "completed",
        "output": {
          "summary": "A short summary.",
        },
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/finalize",
    response: {
      status: 200,
      body: {
        "id": "11111111-1111-4111-8111-111111111111",
        "status": "completed",
        "project_id": "00000000-0000-4000-8000-000000000001",
        "target": {
          "type": "task",
          "id": "summarize",
        },
        "input": {
          "text": "A short document.",
        },
        "output": {
          "summary": "A short summary.",
        },
        "title": "Summarize text",
        "created_at": "2026-10-02T10:00:00Z",
        "updated_at": "2026-10-02T10:00:02Z",
        "trigger": {
          "type": "api_key",
          "id": "key_example",
        },
        "started_at": "2026-10-02T10:00:00Z",
        "finished_at": "2026-10-02T10:00:02Z",
      },
    },
  },
  "createRunHeartbeat": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
      "body": {
        "lease_duration_seconds": 60,
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/heartbeats",
    response: {
      status: 200,
      body: {
        "run_id": "11111111-1111-4111-8111-111111111111",
        "expires_at": "2026-10-02T10:01:00Z",
      },
    },
  },
  "createRunEventToken": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/event-tokens",
    response: {
      status: 201,
      body: {
        "token": "example-token",
        "token_type": "Bearer",
        "expires_at": "2026-10-02T10:05:00Z",
        "run_id": "11111111-1111-4111-8111-111111111111",
        "permissions": [
          "run.events.append",
        ],
      },
    },
  },
  "listRunChildRuns": {
    input: {
      "path": {
        "run_id": "11111111-1111-4111-8111-111111111111",
      },
    },
    url: "/runs/11111111-1111-4111-8111-111111111111/child-runs",
    response: {
      status: 200,
      body: {
        "data": [
          {
            "id": "44444444-4444-4444-8444-444444444444",
            "status": "completed",
            "project_id": "00000000-0000-4000-8000-000000000001",
            "target": {
              "type": "task",
              "id": "summarize",
            },
            "input": {
              "text": "A short document.",
            },
            "output": {
              "summary": "A short summary.",
            },
            "title": "Summarize text",
            "parent_run_id": "11111111-1111-4111-8111-111111111111",
            "root_run_id": "11111111-1111-4111-8111-111111111111",
            "created_at": "2026-10-02T10:00:00Z",
            "updated_at": "2026-10-02T10:00:02Z",
            "trigger": {
              "type": "api_key",
              "id": "key_example",
            },
            "started_at": "2026-10-02T10:00:00Z",
            "finished_at": "2026-10-02T10:00:02Z",
          },
        ],
        "page_info": {
          "next": null,
        },
      },
    },
  },
  "listConversationChildRuns": {
    input: {
      "path": {
        "conversation_id": "00000000-0000-4000-8000-000000000001",
      },
    },
    url: "/conversations/00000000-0000-4000-8000-000000000001/child-runs",
    response: {
      status: 200,
      body: {
        "data": [
          {
            "id": "44444444-4444-4444-8444-444444444444",
            "status": "completed",
            "project_id": "00000000-0000-4000-8000-000000000001",
            "target": {
              "type": "task",
              "id": "summarize",
            },
            "input": {
              "text": "A short document.",
            },
            "output": {
              "summary": "A short summary.",
            },
            "title": "Summarize text",
            "parent_run_id": "11111111-1111-4111-8111-111111111111",
            "root_run_id": "11111111-1111-4111-8111-111111111111",
            "created_at": "2026-10-02T10:00:00Z",
            "updated_at": "2026-10-02T10:00:02Z",
            "trigger": {
              "type": "api_key",
              "id": "key_example",
            },
            "started_at": "2026-10-02T10:00:00Z",
            "finished_at": "2026-10-02T10:00:02Z",
          },
        ],
        "page_info": {
          "next": null,
        },
      },
    },
  },
};
