export const MAX_ANTHROPIC_RAW_ASSISTANT_MESSAGES = 6;
export const MAX_PROVIDER_REPLAY_RAW_METADATA_DEPTH = 64;
export const MAX_PROVIDER_REPLAY_RAW_METADATA_NODES = 65_536;
export const MAX_PROVIDER_REPLAY_RAW_METADATA_STRING_CHARS = 8 * 1024 * 1024;
export const MAX_PROVIDER_REPLAY_REQUEST_BODY_BYTES = 10 * 1024 * 1024;
