type MessageLike = {
  role?: unknown;
  metadata?: unknown;
};

const ArrayIsArray = Array.isArray;
const ObjectGetOwnPropertyDescriptor = Object.getOwnPropertyDescriptor;
const ObjectPrototypeHasOwnProperty = Object.prototype.hasOwnProperty;
const ReflectApply = Reflect.apply;
const WeakSetPrototypeAdd = WeakSet.prototype.add;
const WeakSetPrototypeHas = WeakSet.prototype.has;
const runtimeGeneratedUserMessages = new WeakSet<object>();

function readOwnDataProperty(value: unknown, key: string): unknown {
  try {
    if (value === null || typeof value !== "object" || ArrayIsArray(value)) {
      return undefined;
    }
    const descriptor = ReflectApply(ObjectGetOwnPropertyDescriptor, undefined, [
      value,
      key,
    ]) as PropertyDescriptor | undefined;
    return descriptor &&
        ReflectApply(ObjectPrototypeHasOwnProperty, descriptor, ["value"])
      ? descriptor.value
      : undefined;
  } catch {
    return undefined;
  }
}

function hasUserRole(message: MessageLike): boolean {
  return readOwnDataProperty(message, "role") === "user";
}

/** Mark a framework-created user-role continuation for this runtime execution only. */
export function markRuntimeGeneratedUserMessage<T extends MessageLike>(message: T): T {
  ReflectApply(WeakSetPrototypeAdd, runtimeGeneratedUserMessages, [message]);
  return message;
}

/** Identify a user-role message generated by the runtime for model continuation. */
export function isRuntimeGeneratedUserMessage(message: MessageLike): boolean {
  return hasUserRole(message) &&
    ReflectApply(WeakSetPrototypeHas, runtimeGeneratedUserMessages, [message]);
}

/** Identify a genuine human/API user-turn boundary rather than a runtime retry note. */
export function isGenuineUserTurnMessage(message: MessageLike): boolean {
  return hasUserRole(message) &&
    !ReflectApply(WeakSetPrototypeHas, runtimeGeneratedUserMessages, [message]);
}
