import * as dntShim from "../../../../_dnt.shims.js";
import type { ResponseBuilderConfig, SecurityConfig } from "./types.js";
import * as fluentMethods from "./fluent-methods.js";
import type { FluentMethodsContext } from "./fluent-methods.js";
import * as responseMethods from "./response-methods.js";
import type { ResponseMethodsContext } from "./response-methods.js";
import * as staticHelpers from "./static-helpers.js";
export declare class ResponseBuilder implements FluentMethodsContext, ResponseMethodsContext {
    headers: dntShim.Headers;
    status: number;
    securityConfig: SecurityConfig | null;
    isDev: boolean;
    nonce: string;
    cspUserHeader: string | null;
    adapter: import("../../../platform/adapters/base.js").RuntimeAdapter | undefined;
    isVeryfrontDomain: boolean;
    constructor(config?: ResponseBuilderConfig);
    withCORS: typeof fluentMethods.withCORS;
    withCORSAsync: typeof fluentMethods.withCORSAsync;
    withSecurity: typeof fluentMethods.withSecurity;
    withCache: typeof fluentMethods.withCache;
    withETag: typeof fluentMethods.withETag;
    withHeaders: typeof fluentMethods.withHeaders;
    withStatus: typeof fluentMethods.withStatus;
    withAllow: typeof fluentMethods.withAllow;
    withClientHints: typeof fluentMethods.withClientHints;
    json: typeof responseMethods.json;
    text: typeof responseMethods.text;
    html: typeof responseMethods.html;
    javascript: typeof responseMethods.javascript;
    withContentType: typeof responseMethods.withContentType;
    build: typeof responseMethods.build;
    notModified: typeof responseMethods.notModified;
    static error: typeof staticHelpers.error;
    static json: typeof staticHelpers.json;
    static html: typeof staticHelpers.html;
    static preflight: typeof staticHelpers.preflight;
    static stream: typeof staticHelpers.stream;
}
export declare function createResponseBuilder(config?: ResponseBuilderConfig): ResponseBuilder;
//# sourceMappingURL=builder.d.ts.map