import type { OAuthServiceConfig } from "../types.js";
export declare const githubConfig: OAuthServiceConfig;
export declare const slackConfig: OAuthServiceConfig;
export declare const notionConfig: OAuthServiceConfig;
export declare const figmaConfig: OAuthServiceConfig;
export declare const discordConfig: OAuthServiceConfig;
export declare const linearConfig: OAuthServiceConfig;
export declare const gitlabConfig: OAuthServiceConfig;
export declare const airtableConfig: OAuthServiceConfig;
export declare const dropboxConfig: OAuthServiceConfig;
export declare const hubspotConfig: OAuthServiceConfig;
export declare const salesforceConfig: OAuthServiceConfig;
export declare const twitterConfig: OAuthServiceConfig;
export declare const asanaConfig: OAuthServiceConfig;
export declare const mondayConfig: OAuthServiceConfig;
export declare const zoomConfig: OAuthServiceConfig;
export declare const intercomConfig: OAuthServiceConfig;
export declare const freshdeskConfig: OAuthServiceConfig;
export declare const mailchimpConfig: OAuthServiceConfig;
export declare const shopifyConfig: OAuthServiceConfig;
export declare const quickbooksConfig: OAuthServiceConfig;
export declare const xeroConfig: OAuthServiceConfig;
export declare const boxConfig: OAuthServiceConfig;
export declare const webexConfig: OAuthServiceConfig;
export declare const trelloConfig: OAuthServiceConfig;
export declare const clickupConfig: OAuthServiceConfig;
export declare const pipedriveConfig: OAuthServiceConfig;
export declare const commonServices: {
    github: OAuthServiceConfig;
    slack: OAuthServiceConfig;
    notion: OAuthServiceConfig;
    figma: OAuthServiceConfig;
    discord: OAuthServiceConfig;
    linear: OAuthServiceConfig;
    gitlab: OAuthServiceConfig;
    airtable: OAuthServiceConfig;
    dropbox: OAuthServiceConfig;
    hubspot: OAuthServiceConfig;
    salesforce: OAuthServiceConfig;
    twitter: OAuthServiceConfig;
    asana: OAuthServiceConfig;
    monday: OAuthServiceConfig;
    zoom: OAuthServiceConfig;
    intercom: OAuthServiceConfig;
    freshdesk: OAuthServiceConfig;
    mailchimp: OAuthServiceConfig;
    shopify: OAuthServiceConfig;
    quickbooks: OAuthServiceConfig;
    xero: OAuthServiceConfig;
    box: OAuthServiceConfig;
    webex: OAuthServiceConfig;
    trello: OAuthServiceConfig;
    clickup: OAuthServiceConfig;
    pipedrive: OAuthServiceConfig;
};
//# sourceMappingURL=common.d.ts.map