/**
 * Agent Testing Utilities
 *
 * @module veryfront/agent/testing
 */

export {
  assertCompleted,
  assertContains,
  assertToolCalled,
  printTestResults,
  testAgent,
  type TestCase,
  type TestResult,
  type TestSuite,
} from "./agent-tester.ts";

export {
  assertCompleted as assertDurableRunCanaryCompleted,
  assertNoMalformedCreateFileToolCalls,
  collectAssistantText,
  createDurableRunCanaryApiClient,
  createDurableRunCanaryRunner,
  DEFAULT_DURABLE_RUN_CANARY_TIMEOUT_MS,
  type DurableRunCanaryApiClient,
  type DurableRunCanaryApiConfig,
  type DurableRunCanaryCase,
  type DurableRunCanaryCliCaseFactoryInput,
  type DurableRunCanaryCreateRootRunInput,
  type DurableRunCanaryEnvironment,
  type DurableRunCanaryMessage,
  type DurableRunCanaryPreparedCase,
  type DurableRunCanaryResult,
  type DurableRunCanaryRunnerConfig,
  durableRunCanaryRunnerInternals,
  type DurableRunCanaryRunSummary,
  type DurableRunCanarySendUserMessageInput,
  type DurableRunCanaryStartRunInput,
  findAssistantMessage,
  getDurableRunCanaryMessageSchema,
  parseDurableRunCanaryRunSummary,
  resolveDurableRunCanaryEnvironment,
  runDurableRunCanaryCli,
  type RunDurableRunCanaryCliInput,
  stringifyUnknown,
} from "./durable-run-canaries/index.ts";

export {
  buildFailureSuffix,
  buildLiveEvalCaseMetadata,
  type BuildLiveEvalCaseMetadataInput,
  buildLiveEvalCaseTagSummary,
  buildLiveEvalRequestBody,
  type BuildLiveEvalRequestBodyInput,
  buildLiveEvalRuntimeSummary,
  buildLiveEvalStatusSummary,
  buildProgressLine,
  buildRuntimePerformanceSummary,
  cancelLiveEvalInputRequest,
  containsOrderedSubsequence,
  containsSkillLoad,
  countStepStartedEvents,
  createFailedEvalResult,
  createLiveEvalApiClient,
  createLiveEvalCaseSupport,
  createLiveEvalConversation,
  createLiveEvalProjectUploadFixture,
  createLiveEvalRelease,
  createPassedEvalResult,
  createPlainTextPdf,
  createSkippedEvalResult,
  DEFAULT_LIVE_EVAL_AREA_TAG_RULES,
  DEFAULT_LIVE_EVAL_ENDPOINT,
  DEFAULT_LIVE_EVAL_OPTIONAL_JUDGE_CASE_PREFIXES,
  deleteLiveEvalConversation,
  deleteLiveEvalProjectFile,
  evaluateRuntimeConfidenceEnv,
  getLiveEvalProjectFile,
  hasEveryLiveEvalTag,
  hasFinished,
  listOpenLiveEvalInputRequests,
  type LiveEvalApiClient,
  type LiveEvalApiContext,
  type LiveEvalCase,
  type LiveEvalCaseMetadata,
  type LiveEvalCaseMetadataOptions,
  type LiveEvalCaseSelectionInput,
  type LiveEvalCaseSurface,
  type LiveEvalCaseTagRule,
  type LiveEvalCliCaseFactoryInput,
  type LiveEvalCliCaseGroups,
  type LiveEvalContext,
  type LiveEvalConversationInput,
  type LiveEvalCreateConversationInput,
  type LiveEvalCreateReleaseInput,
  type LiveEvalEnvironment,
  type LiveEvalInputRequestInput,
  type LiveEvalInputRequestRecord,
  type LiveEvalInputResponseValues,
  type LiveEvalProjectFile,
  type LiveEvalProjectFileInput,
  type LiveEvalProjectFileReaderInput,
  type LiveEvalProjectUploadFixtureInput,
  type LiveEvalRequestBody,
  type LiveEvalRequestTimeoutInput,
  type LiveEvalResultForPerformance,
  type LiveEvalResultForReport,
  type LiveEvalResultRecord,
  type LiveEvalRunnerConfig,
  liveEvalRunnerInternals,
  type LiveEvalRuntime,
  type LiveEvalSubmitInputResponseInput,
  type LiveEvalWaitForOpenInputRequestInput,
  type PreparedLiveEvalInput,
  printRuntimeConfidencePreflight,
  resolveLiveEvalEnvironment,
  resolveLiveEvalRequestedCaseIds,
  runLiveEvalCli,
  type RunLiveEvalCliInput,
  type RuntimeConfidencePreflightResult,
  type RuntimePerformanceSummary,
  selectLiveEvalCases,
  submitLiveEvalInputResponse,
  waitForOpenLiveEvalInputRequest,
  withLiveEvalMetadata,
} from "./live-evals/index.ts";
