#!/usr/bin/env -S deno run -A

import { MAX_DEV_UI_BUNDLE_BYTES } from "veryfront/extensions/dev-ui";

const checkOnly = Deno.args.length === 1 && Deno.args[0] === "--check";
if (Deno.args.length !== (checkOnly ? 1 : 0)) {
  throw new TypeError("Usage: prebundle.ts [--check]");
}

const repositoryRoot = new URL("../../../", import.meta.url);
const configPath = "extensions/ext-dev-ui-react/deno.json";
const browserImportMapPath = "extensions/ext-dev-ui-react/scripts/browser-import-map.json";
const sourcePath = "extensions/ext-dev-ui-react/src/browser-entry.tsx";
const outputPath = new URL("../src/dev-ui-bundle.generated.ts", import.meta.url);
const MAX_PRODUCTION_BUNDLE_BYTES = Math.min(
  MAX_DEV_UI_BUNDLE_BYTES,
  512 * 1024,
);

const command = new Deno.Command(Deno.execPath(), {
  args: [
    "bundle",
    "--quiet",
    "--frozen",
    "--lock=deno.lock",
    "--minify",
    "--platform=browser",
    "--conditions=production",
    "--config",
    configPath,
    "--import-map",
    browserImportMapPath,
    sourcePath,
  ],
  cwd: repositoryRoot,
  stdout: "piped",
  stderr: "piped",
});
const result = await command.output();
if (!result.success) {
  const diagnostic = new TextDecoder().decode(result.stderr).trim();
  throw new Error(diagnostic || "Failed to build the offline Dev UI bundle");
}

const bundle = new TextDecoder("utf-8", { fatal: true }).decode(result.stdout);
const bundleBytes = new TextEncoder().encode(bundle);
if (bundleBytes.length === 0 || bundle.trim().length === 0) {
  throw new Error("The offline Dev UI bundle is empty");
}
if (bundleBytes.length > MAX_PRODUCTION_BUNDLE_BYTES) {
  throw new RangeError(
    `The production Dev UI bundle exceeds ${MAX_PRODUCTION_BUNDLE_BYTES} bytes`,
  );
}
if (/\besm\.sh\b/i.test(bundle)) {
  throw new Error("The offline Dev UI bundle contains an esm.sh dependency");
}
if (/(?:^|[;}])\s*import\s*(?:[({*]|[\w$])/m.test(bundle)) {
  throw new Error("The offline Dev UI bundle contains an unresolved import");
}
if (
  /\b(?:react(?:-jsx-runtime)?|react-dom(?:-client)?|scheduler)\.development\.js\b/i
    .test(bundle)
) {
  throw new Error("The offline Dev UI bundle contains a React development build");
}

const digest = new Uint8Array(
  await crypto.subtle.digest("SHA-256", bundleBytes),
).toHex();
const generated = `/**
 * Extension-owned offline React development UI bundle.
 *
 * AUTO-GENERATED by extensions/ext-dev-ui-react/scripts/prebundle.ts.
 * Do not edit manually.
 */

// deno-fmt-ignore - preserve the generated JavaScript as one JSON string.
export const DEV_UI_BROWSER_BUNDLE: string = ${JSON.stringify(bundle)};
export const DEV_UI_BROWSER_BUNDLE_SHA256 = ${JSON.stringify(digest)};
`;

if (checkOnly) {
  const current = await Deno.readTextFile(outputPath);
  if (current !== generated) {
    throw new Error(
      "Offline Dev UI bundle is stale; run deno task generate",
    );
  }
} else {
  await Deno.writeTextFile(outputPath, generated);
  console.log(
    `[ext-dev-ui-react] Wrote ${outputPath.pathname} (${bundleBytes.length} bytes, sha256:${digest})`,
  );
}
