import type { RuntimeAdapter } from "../../platform/adapters/base.js";
import { metricsManager } from "./manager.js";
export type { MemoryUsage, MetricsConfig } from "./types.js";
export { getMemoryUsage, loadConfig } from "./config.js";
export { MetricsRecorder } from "./recorder.js";
export declare function initMetrics(config?: Parameters<typeof metricsManager.initialize>[0], adapter?: RuntimeAdapter): Promise<void>;
export declare function isMetricsEnabled(): boolean;
export declare function shutdownMetrics(): Promise<void>;
export declare function getMetricsState(): ReturnType<typeof metricsManager.getState>;
export declare function recordHttpRequest(attributes?: Record<string, string>): void;
export declare function recordHttpRequestComplete(durationMs: number, attributes?: Record<string, string>): void;
export declare function recordCacheGet(hit: boolean, attributes?: Record<string, string>): void;
export declare function recordCacheSet(attributes?: Record<string, string>): void;
export declare function recordCacheInvalidate(count: number, attributes?: Record<string, string>): void;
export declare function setCacheSize(size: number): void;
export declare function recordRender(durationMs: number, attributes?: Record<string, string>): void;
export declare function recordRenderError(attributes?: Record<string, string>): void;
export declare function recordRSCRender(durationMs: number, attributes?: Record<string, string>): void;
export declare function recordRSCStream(durationMs: number, attributes?: Record<string, string>): void;
export declare function recordRSCRequest(type: "manifest" | "page" | "stream" | "action", attributes?: Record<string, string>): void;
export declare function recordRSCError(attributes?: Record<string, string>): void;
export declare function recordBuild(durationMs: number, attributes?: Record<string, string>): void;
export declare function recordBundle(sizeKb: number, attributes?: Record<string, string>): void;
export declare function recordDataFetch(durationMs: number, attributes?: Record<string, string>): void;
export declare function recordDataFetchError(attributes?: Record<string, string>): void;
export declare function recordCorsRejection(attributes?: Record<string, string>): void;
export declare function recordSecurityHeaders(attributes?: Record<string, string>): void;
export { metricsManager } from "./manager.js";
export { MetricsManager } from "./manager.js";
//# sourceMappingURL=index.d.ts.map