/** Remove credentials and provider routing from the real test-process environment. */
const TEST_SENSITIVE_ENV_KEYS = [
  "VERYFRONT_API_TOKEN",
  "VERYFRONT_API_BASE_URL",
  "VERYFRONT_API_URL",
  "VERYFRONT_PUBLIC_API_BASE_URL",
  "VERYFRONT_PROJECT_SLUG",
  "AG_UI_EVAL_PROJECT_SLUG",
  "TENANT_PROJECT_SLUG",
  "OPENAI_API_KEY",
  "OPENAI_BASE_URL",
  "ANTHROPIC_API_KEY",
  "ANTHROPIC_BASE_URL",
  "GOOGLE_API_KEY",
  "GOOGLE_GENERATIVE_AI_API_KEY",
  "GOOGLE_GEMINI_BASE_URL",
  "MISTRAL_API_KEY",
  "MISTRAL_BASE_URL",
  "GROQ_API_KEY",
  "GROQ_BASE_URL",
  "DEEPSEEK_API_KEY",
  "DEEPSEEK_BASE_URL",
  "OPENROUTER_API_KEY",
  "OPENROUTER_BASE_URL",
  "CONTEXT7_API_KEY",
] as const;

for (const key of TEST_SENSITIVE_ENV_KEYS) Deno.env.delete(key);
