#!/usr/bin/env -S deno run -A

import { dirname, fromFileUrl, join } from "../../../src/platform/compat/path/index.ts";
import type { BundlerPlugin } from "../../../src/extensions/bundler/index.ts";
import { buildStudioBridgeBundle } from "../../../scripts/build/prebundle-bridge.ts";

const scriptDirectory = dirname(fromFileUrl(import.meta.url));
const extensionRoot = join(scriptDirectory, "..");
const repositoryRoot = join(extensionRoot, "..", "..");
const outputPath = join(extensionRoot, "src", "studio-bridge-bundle.generated.ts");
const bridgeContractPath = join(repositoryRoot, "src", "studio", "bridge", "index.ts");

const aliasPlugin: BundlerPlugin = {
  name: "veryfront-studio-bridge-contract",
  setup(build) {
    build.onResolve({ filter: /^veryfront\/studio\/bridge$/ }, () => ({
      path: bridgeContractPath,
    }));
  },
};

const bundle = await buildStudioBridgeBundle({
  entryPoint: "extensions/ext-studio-capture-html2canvas/src/browser-entry.ts",
  plugins: [aliasPlugin],
});

const output = `/**
 * Extension-owned html2canvas Studio bridge bundle.
 *
 * AUTO-GENERATED by extensions/ext-studio-capture-html2canvas/scripts/prebundle.ts.
 * Do not edit manually.
 */

// deno-fmt-ignore - preserve the generated JavaScript as one JSON string.
export const HTML2CANVAS_STUDIO_BRIDGE_BUNDLE: string = ${JSON.stringify(bundle)};
`;

await Deno.writeTextFile(outputPath, output);
console.log(
  `[ext-studio-capture-html2canvas] Wrote ${outputPath} (${bundle.length} bytes)`,
);
