// Auto-generated — do not edit
import type { IntegrationEndpointHistoricalSummary } from "./schema.ts";

export const historicalToolSummaries: Record<string, IntegrationEndpointHistoricalSummary> = {
  "gmail__list_emails": {
    "collectionKeys": ["messages", "data"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "threadId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "to" },
      { "name": "subject" },
      { "name": "date" },
      { "name": "internalDate" },
      { "name": "snippet", "maxLength": 300 },
      { "name": "labelIds", "kind": "string-array" },
      { "name": "isUnread" },
      { "name": "unread" },
    ],
    "outputFields": [{ "name": "nextPageToken" }, { "name": "resultSizeEstimate" }],
    "omitted": "large email bodies and provider-specific payload fields",
  },
  "gmail__search_emails": {
    "collectionKeys": ["messages", "data"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "threadId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "to" },
      { "name": "subject" },
      { "name": "date" },
      { "name": "internalDate" },
      { "name": "snippet", "maxLength": 300 },
      { "name": "labelIds", "kind": "string-array" },
      { "name": "isUnread" },
      { "name": "unread" },
    ],
    "outputFields": [{ "name": "nextPageToken" }, { "name": "resultSizeEstimate" }],
    "omitted": "large email bodies and provider-specific payload fields",
  },
  "outlook__list_emails": {
    "collectionKeys": ["value", "data", "messages"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "conversationId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "toRecipients", "kind": "contact-array" },
      { "name": "subject" },
      { "name": "receivedDateTime" },
      { "name": "sentDateTime" },
      { "name": "bodyPreview", "maxLength": 300 },
      { "name": "categories", "kind": "string-array" },
      { "name": "isRead" },
      { "name": "importance" },
      { "name": "hasAttachments" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "large email bodies and provider-specific message fields",
  },
  "outlook__search_emails": {
    "collectionKeys": ["value", "data", "messages"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "conversationId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "toRecipients", "kind": "contact-array" },
      { "name": "subject" },
      { "name": "receivedDateTime" },
      { "name": "sentDateTime" },
      { "name": "bodyPreview", "maxLength": 300 },
      { "name": "categories", "kind": "string-array" },
      { "name": "isRead" },
      { "name": "importance" },
      { "name": "hasAttachments" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "large email bodies and provider-specific message fields",
  },
};
