// Auto-generated — do not edit
import type { IntegrationEndpointHistoricalSummary } from "./schema.ts";

export const historicalToolSummaries: Record<string, IntegrationEndpointHistoricalSummary> = {
  "asana__list_projects": {
    "collectionKeys": ["data", "projects"],
    "collectionName": "projects",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "projects details and provider-specific payload fields",
  },
  "asana__list_task_comments": {
    "collectionKeys": ["data", "comments", "stories"],
    "collectionName": "comments",
    "itemFields": [{ "name": "gid" }, { "name": "type" }, { "name": "text", "maxLength": 300 }, {
      "name": "created_at",
    }, { "name": "created_by", "kind": "contact" }],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "full comment story payloads and provider-specific fields",
  },
  "asana__list_tasks": {
    "collectionKeys": ["data", "tasks"],
    "collectionName": "tasks",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "tasks details and provider-specific payload fields",
  },
  "asana__list_teams": {
    "collectionKeys": ["data", "teams"],
    "collectionName": "teams",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "teams details and provider-specific payload fields",
  },
  "asana__list_users": {
    "collectionKeys": ["data", "users"],
    "collectionName": "users",
    "itemFields": [{ "name": "gid" }, { "name": "name" }, { "name": "email" }],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "user profile details and provider-specific payload fields",
  },
  "asana__list_workspaces": {
    "collectionKeys": ["data", "workspaces"],
    "collectionName": "workspaces",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "workspaces details and provider-specific payload fields",
  },
  "github__get_issue": {
    "collectionKeys": ["issue", "data"],
    "collectionName": "issues",
    "itemFields": [
      { "name": "id" },
      { "name": "node_id" },
      { "name": "number" },
      { "name": "title" },
      { "name": "state" },
      { "name": "html_url" },
      { "name": "url" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "closed_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
    ],
    "singleItem": true,
    "omitted": "issue body, comments, timeline, and provider-specific payload fields",
  },
  "github__get_pr": {
    "collectionKeys": ["pullRequest", "data"],
    "collectionName": "pullRequests",
    "itemFields": [
      { "name": "id" },
      { "name": "node_id" },
      { "name": "number" },
      { "name": "title" },
      { "name": "state" },
      { "name": "html_url" },
      { "name": "url" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "closed_at" },
      { "name": "merged_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "draft" },
      { "name": "mergeable" },
    ],
    "singleItem": true,
    "omitted": "pull request body, diff, reviews, and provider-specific payload fields",
  },
  "github__list_commits": {
    "collectionKeys": ["commits", "data"],
    "collectionName": "commits",
    "itemFields": [{ "name": "sha" }, { "name": "node_id" }, { "name": "html_url" }, {
      "name": "author",
      "kind": "contact",
    }, { "name": "committer", "kind": "contact" }],
    "omitted": "full commit messages, verification payloads, and file details",
  },
  "github__list_issues": {
    "collectionKeys": ["issues", "nodes", "data"],
    "collectionName": "issues",
    "itemFields": [
      { "name": "id" },
      { "name": "node_id" },
      { "name": "number" },
      { "name": "title" },
      { "name": "state" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "author", "kind": "contact" },
      { "name": "user", "kind": "contact" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "created_at" },
      { "name": "updated_at" },
    ],
    "outputFields": [{ "name": "pageInfo", "kind": "object" }],
    "omitted": "issue bodies, comments, and provider-specific payload fields",
  },
  "github__list_prs": {
    "collectionKeys": ["pullRequests", "data"],
    "collectionName": "pullRequests",
    "itemFields": [
      { "name": "id" },
      { "name": "node_id" },
      { "name": "number" },
      { "name": "title" },
      { "name": "state" },
      { "name": "html_url" },
      { "name": "user", "kind": "contact" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "closed_at" },
      { "name": "merged_at" },
      { "name": "draft" },
    ],
    "omitted": "pull request bodies, diff details, and provider-specific payload fields",
  },
  "github__list_repos": {
    "collectionKeys": ["repositories", "data"],
    "collectionName": "repositories",
    "itemFields": [
      { "name": "id" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "full_name" },
      { "name": "owner", "kind": "contact" },
      { "name": "html_url" },
      { "name": "private" },
      { "name": "archived" },
      { "name": "open_issues_count" },
      { "name": "default_branch" },
      { "name": "updated_at" },
      { "name": "pushed_at" },
    ],
    "omitted": "repository descriptions and provider-specific payload fields",
  },
  "gmail__list_drafts": {
    "collectionKeys": ["drafts", "data"],
    "collectionName": "drafts",
    "itemFields": [{ "name": "id" }, { "name": "message", "kind": "object" }],
    "outputFields": [{ "name": "nextPageToken" }, { "name": "resultSizeEstimate" }],
    "omitted": "draft message bodies and provider-specific payload fields",
  },
  "gmail__list_emails": {
    "collectionKeys": ["messages", "data"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "threadId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "to" },
      { "name": "subject" },
      { "name": "date" },
      { "name": "internalDate" },
      { "name": "snippet", "maxLength": 300 },
      { "name": "labelIds", "kind": "string-array" },
      { "name": "isUnread" },
      { "name": "unread" },
    ],
    "outputFields": [{ "name": "nextPageToken" }, { "name": "resultSizeEstimate" }],
    "omitted": "large email bodies and provider-specific payload fields",
  },
  "gmail__list_history": {
    "collectionKeys": ["history", "data"],
    "collectionName": "history",
    "itemFields": [{ "name": "id" }, { "name": "messages", "kind": "object" }, {
      "name": "messagesAdded",
      "kind": "object",
    }, { "name": "messagesDeleted", "kind": "object" }],
    "outputFields": [{ "name": "nextPageToken" }, { "name": "historyId" }],
    "omitted": "history details and provider-specific payload fields",
  },
  "gmail__list_labels": {
    "collectionKeys": ["labels", "data"],
    "collectionName": "labels",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "type" }],
    "omitted": "label counters and provider-specific payload fields",
  },
  "gmail__list_threads": {
    "collectionKeys": ["threads", "data"],
    "collectionName": "threads",
    "itemFields": [{ "name": "id" }, { "name": "snippet", "maxLength": 300 }, {
      "name": "historyId",
    }],
    "outputFields": [{ "name": "nextPageToken" }, { "name": "resultSizeEstimate" }],
    "omitted": "large thread payloads and provider-specific fields",
  },
  "gmail__search_emails": {
    "collectionKeys": ["messages", "data"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "threadId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "to" },
      { "name": "subject" },
      { "name": "date" },
      { "name": "internalDate" },
      { "name": "snippet", "maxLength": 300 },
      { "name": "labelIds", "kind": "string-array" },
      { "name": "isUnread" },
      { "name": "unread" },
    ],
    "outputFields": [{ "name": "nextPageToken" }, { "name": "resultSizeEstimate" }],
    "omitted": "large email bodies and provider-specific payload fields",
  },
  "harvest__invoice_report": {
    "collectionKeys": ["results", "data"],
    "collectionName": "invoiceReports",
    "itemFields": [
      { "name": "client_id" },
      { "name": "client_name" },
      { "name": "invoice_id" },
      { "name": "invoice_number" },
      { "name": "amount" },
      { "name": "currency" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "invoice report details and provider-specific payload fields",
  },
  "harvest__list_accounts": {
    "collectionKeys": ["accounts", "data"],
    "collectionName": "accounts",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "product" }],
    "omitted": "account auth policy and provider-specific fields",
  },
  "harvest__list_clients": {
    "collectionKeys": ["clients", "data"],
    "collectionName": "clients",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "currency" }, {
      "name": "is_active",
    }, { "name": "updated_at" }],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "client addresses, statement keys, and provider-specific payload fields",
  },
  "harvest__list_invoice_payments": {
    "collectionKeys": ["invoice_payments", "data"],
    "collectionName": "invoicePayments",
    "itemFields": [{ "name": "id" }, { "name": "amount" }, { "name": "paid_at" }, {
      "name": "created_at",
    }, { "name": "updated_at" }],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "payment notes and provider-specific payload fields",
  },
  "harvest__list_invoices": {
    "collectionKeys": ["invoices", "data"],
    "collectionName": "invoices",
    "itemFields": [
      { "name": "id" },
      { "name": "number" },
      { "name": "state" },
      { "name": "amount" },
      { "name": "due_date" },
      { "name": "client", "kind": "object" },
      { "name": "updated_at" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "invoice notes, line items, and provider-specific payload fields",
  },
  "harvest__list_project_task_assignments": {
    "collectionKeys": ["task_assignments", "data"],
    "collectionName": "taskAssignments",
    "itemFields": [
      { "name": "id" },
      { "name": "task", "kind": "object" },
      { "name": "project", "kind": "object" },
      { "name": "is_active" },
      { "name": "updated_at" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "task assignment rates and provider-specific payload fields",
  },
  "harvest__list_projects": {
    "collectionKeys": ["projects", "data"],
    "collectionName": "projects",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "code" },
      { "name": "is_active" },
      { "name": "client", "kind": "object" },
      { "name": "updated_at" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "project budgets, notes, rates, and provider-specific payload fields",
  },
  "harvest__list_tasks": {
    "collectionKeys": ["tasks", "data"],
    "collectionName": "tasks",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "is_active" }, {
      "name": "is_default",
    }, { "name": "updated_at" }],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "task rates and provider-specific payload fields",
  },
  "harvest__list_time_entries": {
    "collectionKeys": ["time_entries", "data"],
    "collectionName": "timeEntries",
    "itemFields": [
      { "name": "id" },
      { "name": "spent_date" },
      { "name": "hours" },
      { "name": "billable" },
      { "name": "user", "kind": "contact" },
      { "name": "client", "kind": "object" },
      { "name": "project", "kind": "object" },
      { "name": "task", "kind": "object" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "notes, rates, invoice details, and provider-specific payload fields",
  },
  "harvest__list_users": {
    "collectionKeys": ["users", "data"],
    "collectionName": "users",
    "itemFields": [
      { "name": "id" },
      { "name": "email" },
      { "name": "first_name" },
      { "name": "last_name" },
      { "name": "is_active" },
      { "name": "timezone" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "user rates, avatars, and provider-specific payload fields",
  },
  "harvest__time_report_by_client": {
    "collectionKeys": ["results", "data"],
    "collectionName": "clientTimeReports",
    "itemFields": [
      { "name": "client_id" },
      { "name": "client_name" },
      { "name": "total_hours" },
      { "name": "billable_hours" },
      { "name": "billable_amount" },
      { "name": "currency" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "client report details and provider-specific payload fields",
  },
  "harvest__time_report_by_project": {
    "collectionKeys": ["results", "data"],
    "collectionName": "projectTimeReports",
    "itemFields": [
      { "name": "project_id" },
      { "name": "project_name" },
      { "name": "client_id" },
      { "name": "client_name" },
      { "name": "total_hours" },
      { "name": "billable_hours" },
      { "name": "billable_amount" },
      { "name": "currency" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "report breakdown details and provider-specific payload fields",
  },
  "harvest__time_report_by_task": {
    "collectionKeys": ["results", "data"],
    "collectionName": "taskTimeReports",
    "itemFields": [
      { "name": "task_id" },
      { "name": "task_name" },
      { "name": "total_hours" },
      { "name": "billable_hours" },
      { "name": "billable_amount" },
      { "name": "currency" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "task report details and provider-specific payload fields",
  },
  "harvest__time_report_by_team": {
    "collectionKeys": ["results", "data"],
    "collectionName": "teamTimeReports",
    "itemFields": [
      { "name": "user_id" },
      { "name": "user_name" },
      { "name": "total_hours" },
      { "name": "billable_hours" },
      { "name": "billable_amount" },
      { "name": "currency" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "team report details and provider-specific payload fields",
  },
  "jira__list_comments": {
    "collectionKeys": ["comments", "data"],
    "collectionName": "comments",
    "itemFields": [
      { "name": "id" },
      { "name": "body", "kind": "object" },
      { "name": "author", "kind": "contact" },
      { "name": "created" },
      { "name": "updated" },
    ],
    "outputFields": [{ "name": "total" }, { "name": "startAt" }, { "name": "maxResults" }],
    "omitted": "full comment payloads and provider-specific fields",
  },
  "jira__list_projects": {
    "collectionKeys": ["values", "projects", "data"],
    "collectionName": "projects",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "projects details and provider-specific payload fields",
  },
  "jira__list_sites": {
    "collectionKeys": ["values", "sites", "data"],
    "collectionName": "sites",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "sites details and provider-specific payload fields",
  },
  "jira__search_issues": {
    "collectionKeys": ["issues", "data"],
    "collectionName": "issues",
    "itemFields": [
      { "name": "id" },
      { "name": "key" },
      { "name": "summary" },
      { "name": "status", "kind": "object" },
      { "name": "assignee", "kind": "contact" },
      { "name": "created" },
      { "name": "updated" },
    ],
    "outputFields": [{ "name": "total" }, { "name": "startAt" }, { "name": "maxResults" }],
    "omitted": "issue descriptions, comments, changelog, and provider-specific payload fields",
  },
  "linear__list_projects": {
    "collectionKeys": ["projects", "nodes", "data"],
    "collectionName": "projects",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "projects details and provider-specific payload fields",
  },
  "linear__list_teams": {
    "collectionKeys": ["teams", "nodes", "data"],
    "collectionName": "teams",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "teams details and provider-specific payload fields",
  },
  "linear__list_users": {
    "collectionKeys": ["users", "nodes", "data"],
    "collectionName": "users",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "email" },
      { "name": "active" },
      { "name": "displayName" },
    ],
    "outputFields": [{ "name": "pageInfo", "kind": "object" }],
    "omitted": "user avatars and provider-specific payload fields",
  },
  "linear__list_workflow_states": {
    "collectionKeys": ["states", "nodes", "data"],
    "collectionName": "workflowStates",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "workflowStates details and provider-specific payload fields",
  },
  "linear__search_issues": {
    "collectionKeys": ["searchIssues", "issues", "nodes", "data"],
    "collectionName": "issues",
    "itemFields": [
      { "name": "id" },
      { "name": "identifier" },
      { "name": "title" },
      { "name": "state", "kind": "object" },
      { "name": "assignee", "kind": "contact" },
      { "name": "url" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
    ],
    "outputFields": [{ "name": "pageInfo", "kind": "object" }],
    "omitted": "issue descriptions, comments, and provider-specific payload fields",
  },
  "outlook__find_free_time": {
    "collectionKeys": ["value", "schedules", "data"],
    "collectionName": "schedules",
    "itemFields": [
      { "name": "scheduleId" },
      { "name": "availabilityView" },
      { "name": "scheduleItems", "kind": "object" },
      { "name": "workingHours", "kind": "object" },
      { "name": "error", "kind": "object" },
    ],
    "omitted": "provider-specific schedule diagnostics and expanded free/busy payload fields",
  },
  "outlook__find_meeting_times": {
    "collectionKeys": ["meetingTimeSuggestions", "value", "data"],
    "collectionName": "meetingTimeSuggestions",
    "itemFields": [
      { "name": "confidence" },
      { "name": "organizerAvailability" },
      { "name": "attendeeAvailability", "kind": "object" },
      { "name": "meetingTimeSlot", "kind": "object" },
      { "name": "locations", "kind": "object" },
      { "name": "suggestionReason", "maxLength": 300 },
    ],
    "omitted": "provider-specific meeting suggestion diagnostics",
  },
  "outlook__get_event_instances": {
    "collectionKeys": ["value", "events", "data"],
    "collectionName": "events",
    "itemFields": [
      { "name": "id" },
      { "name": "subject" },
      { "name": "organizer", "kind": "contact" },
      { "name": "attendees", "kind": "contact-array" },
      { "name": "start", "kind": "object" },
      { "name": "end", "kind": "object" },
      { "name": "location", "kind": "object" },
      { "name": "showAs" },
      { "name": "responseStatus", "kind": "object" },
      { "name": "isOnlineMeeting" },
      { "name": "webLink" },
      { "name": "bodyPreview", "maxLength": 300 },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "full event bodies and provider-specific payload fields",
  },
  "outlook__get_schedule": {
    "collectionKeys": ["value", "schedules", "data"],
    "collectionName": "schedules",
    "itemFields": [
      { "name": "scheduleId" },
      { "name": "availabilityView" },
      { "name": "scheduleItems", "kind": "object" },
      { "name": "workingHours", "kind": "object" },
      { "name": "error", "kind": "object" },
    ],
    "omitted": "provider-specific schedule diagnostics and expanded free/busy payload fields",
  },
  "outlook__list_attachments": {
    "collectionKeys": ["value", "attachments", "data"],
    "collectionName": "attachments",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "contentType" },
      { "name": "size" },
      { "name": "isInline" },
      { "name": "lastModifiedDateTime" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "attachment binary content and provider-specific payload fields",
  },
  "outlook__list_calendar_view": {
    "collectionKeys": ["value", "events", "data"],
    "collectionName": "events",
    "itemFields": [
      { "name": "id" },
      { "name": "subject" },
      { "name": "organizer", "kind": "contact" },
      { "name": "attendees", "kind": "contact-array" },
      { "name": "start", "kind": "object" },
      { "name": "end", "kind": "object" },
      { "name": "location", "kind": "object" },
      { "name": "showAs" },
      { "name": "responseStatus", "kind": "object" },
      { "name": "isOnlineMeeting" },
      { "name": "webLink" },
      { "name": "bodyPreview", "maxLength": 300 },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "full event bodies and provider-specific payload fields",
  },
  "outlook__list_calendars": {
    "collectionKeys": ["value", "calendars", "data"],
    "collectionName": "calendars",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "color" },
      { "name": "isDefaultCalendar" },
      { "name": "canEdit" },
      { "name": "canShare" },
      { "name": "owner", "kind": "object" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "calendar provider-specific payload fields",
  },
  "outlook__list_categories": {
    "collectionKeys": ["value", "categories", "data"],
    "collectionName": "categories",
    "itemFields": [{ "name": "id" }, { "name": "displayName" }, { "name": "color" }],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "category provider-specific payload fields",
  },
  "outlook__list_conversation_messages": {
    "collectionKeys": ["value", "data", "messages"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "conversationId" },
      { "name": "internetMessageId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "toRecipients", "kind": "contact-array" },
      { "name": "ccRecipients", "kind": "contact-array" },
      { "name": "subject" },
      { "name": "receivedDateTime" },
      { "name": "sentDateTime" },
      { "name": "bodyPreview", "maxLength": 300 },
      { "name": "categories", "kind": "string-array" },
      { "name": "isRead" },
      { "name": "importance" },
      { "name": "hasAttachments" },
      { "name": "webLink" },
      { "name": "flag", "kind": "object" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "large email bodies and provider-specific message fields",
  },
  "outlook__list_drafts": {
    "collectionKeys": ["value", "data", "messages"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "conversationId" },
      { "name": "internetMessageId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "toRecipients", "kind": "contact-array" },
      { "name": "ccRecipients", "kind": "contact-array" },
      { "name": "subject" },
      { "name": "receivedDateTime" },
      { "name": "sentDateTime" },
      { "name": "bodyPreview", "maxLength": 300 },
      { "name": "categories", "kind": "string-array" },
      { "name": "isRead" },
      { "name": "importance" },
      { "name": "hasAttachments" },
      { "name": "webLink" },
      { "name": "flag", "kind": "object" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "large email bodies and provider-specific message fields",
  },
  "outlook__list_emails": {
    "collectionKeys": ["value", "data", "messages"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "conversationId" },
      { "name": "internetMessageId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "toRecipients", "kind": "contact-array" },
      { "name": "ccRecipients", "kind": "contact-array" },
      { "name": "subject" },
      { "name": "receivedDateTime" },
      { "name": "sentDateTime" },
      { "name": "bodyPreview", "maxLength": 300 },
      { "name": "categories", "kind": "string-array" },
      { "name": "isRead" },
      { "name": "importance" },
      { "name": "hasAttachments" },
      { "name": "webLink" },
      { "name": "flag", "kind": "object" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "large email bodies and provider-specific message fields",
  },
  "outlook__list_event_attachments": {
    "collectionKeys": ["value", "attachments", "data"],
    "collectionName": "attachments",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "contentType" },
      { "name": "size" },
      { "name": "isInline" },
      { "name": "lastModifiedDateTime" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "attachment binary content and provider-specific payload fields",
  },
  "outlook__list_events": {
    "collectionKeys": ["value", "events", "data"],
    "collectionName": "events",
    "itemFields": [
      { "name": "id" },
      { "name": "subject" },
      { "name": "organizer", "kind": "contact" },
      { "name": "attendees", "kind": "contact-array" },
      { "name": "start", "kind": "object" },
      { "name": "end", "kind": "object" },
      { "name": "location", "kind": "object" },
      { "name": "showAs" },
      { "name": "responseStatus", "kind": "object" },
      { "name": "isOnlineMeeting" },
      { "name": "webLink" },
      { "name": "bodyPreview", "maxLength": 300 },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "full event bodies and provider-specific payload fields",
  },
  "outlook__list_folders": {
    "collectionKeys": ["value", "folders", "data"],
    "collectionName": "folders",
    "itemFields": [
      { "name": "id" },
      { "name": "displayName" },
      { "name": "parentFolderId" },
      { "name": "childFolderCount" },
      { "name": "unreadItemCount" },
      { "name": "totalItemCount" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "folder provider-specific payload fields",
  },
  "outlook__search_emails": {
    "collectionKeys": ["value", "data", "messages"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "conversationId" },
      { "name": "internetMessageId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "toRecipients", "kind": "contact-array" },
      { "name": "ccRecipients", "kind": "contact-array" },
      { "name": "subject" },
      { "name": "receivedDateTime" },
      { "name": "sentDateTime" },
      { "name": "bodyPreview", "maxLength": 300 },
      { "name": "categories", "kind": "string-array" },
      { "name": "isRead" },
      { "name": "importance" },
      { "name": "hasAttachments" },
      { "name": "webLink" },
      { "name": "flag", "kind": "object" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "large email bodies and provider-specific message fields",
  },
  "slack__list_channels": {
    "collectionKeys": ["channels", "data"],
    "collectionName": "channels",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "is_channel" },
      { "name": "is_group" },
      { "name": "is_im" },
      { "name": "is_private" },
      { "name": "is_archived" },
      { "name": "num_members" },
    ],
    "outputFields": [{ "name": "response_metadata", "kind": "object" }],
    "omitted": "channel topics, purposes, and provider-specific payload fields",
  },
  "slack__list_users": {
    "collectionKeys": ["members", "users", "data"],
    "collectionName": "users",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "real_name" },
      { "name": "team_id" },
      { "name": "is_bot" },
      { "name": "deleted" },
    ],
    "outputFields": [{ "name": "response_metadata", "kind": "object" }],
    "omitted": "user profiles, avatars, and provider-specific payload fields",
  },
};
