// Auto-generated — do not edit
import type { IntegrationEndpointHistoricalSummary } from "./schema.ts";

export const historicalToolSummaries: Record<string, IntegrationEndpointHistoricalSummary> = {
  "activecampaign__list_contacts": {
    "collectionKeys": ["contacts"],
    "collectionName": "contacts",
    "itemFields": [
      { "name": "id" },
      { "name": "email" },
      { "name": "firstName" },
      { "name": "lastName" },
      { "name": "phone" },
      { "name": "cdate" },
      { "name": "udate" },
    ],
    "outputFields": [{ "name": "meta", "kind": "object" }],
    "omitted": "contact field values, scores, and provider-specific payload fields",
  },
  "algolia__list_indices": {
    "collectionKeys": ["items", "indices"],
    "collectionName": "indices",
    "itemFields": [{ "name": "name" }, { "name": "entries" }, { "name": "dataSize" }, {
      "name": "createdAt",
    }, { "name": "updatedAt" }],
    "outputFields": [{ "name": "nbPages" }],
    "omitted": "index settings and provider-specific payload fields",
  },
  "amplitude__list_events": {
    "collectionKeys": ["data", "events"],
    "collectionName": "events",
    "itemFields": [{ "name": "id" }, { "name": "value" }, { "name": "display" }, {
      "name": "totals",
    }, { "name": "non_active" }],
    "omitted": "event property details and provider-specific payload fields",
  },
  "anthropic__list_api_keys": {
    "collectionKeys": ["data"],
    "collectionName": "api_keys",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "status" },
      { "name": "workspace_id" },
      { "name": "created_at" },
      { "name": "partial_key_hint" },
    ],
    "outputFields": [{ "name": "has_more" }, { "name": "last_id" }],
    "omitted": "key creator details and provider-specific payload fields",
  },
  "anthropic__list_members": {
    "collectionKeys": ["data"],
    "collectionName": "members",
    "itemFields": [{ "name": "id" }, { "name": "email" }, { "name": "name" }, { "name": "role" }, {
      "name": "added_at",
    }],
    "outputFields": [{ "name": "has_more" }, { "name": "last_id" }],
    "omitted": "provider-specific payload fields",
  },
  "anthropic__list_workspaces": {
    "collectionKeys": ["data"],
    "collectionName": "workspaces",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "created_at" }, {
      "name": "archived_at",
    }],
    "outputFields": [{ "name": "has_more" }, { "name": "last_id" }],
    "omitted": "workspace display colors and provider-specific payload fields",
  },
  "apollo__search_people": {
    "collectionKeys": ["people", "contacts"],
    "collectionName": "people",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "title" }, { "name": "email" }, {
      "name": "linkedin_url",
    }, { "name": "organization", "kind": "object" }],
    "outputFields": [{ "name": "pagination", "kind": "object" }],
    "omitted": "employment history and provider-specific payload fields",
  },
  "asana__list_projects": {
    "collectionKeys": ["data", "projects"],
    "collectionName": "projects",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "projects details and provider-specific payload fields",
  },
  "asana__list_task_comments": {
    "collectionKeys": ["data", "comments", "stories"],
    "collectionName": "comments",
    "itemFields": [{ "name": "gid" }, { "name": "type" }, { "name": "text", "maxLength": 300 }, {
      "name": "created_at",
    }, { "name": "created_by", "kind": "contact" }],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "full comment story payloads and provider-specific fields",
  },
  "asana__list_tasks": {
    "collectionKeys": ["data", "tasks"],
    "collectionName": "tasks",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "tasks details and provider-specific payload fields",
  },
  "asana__list_teams": {
    "collectionKeys": ["data", "teams"],
    "collectionName": "teams",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "teams details and provider-specific payload fields",
  },
  "asana__list_users": {
    "collectionKeys": ["data", "users"],
    "collectionName": "users",
    "itemFields": [{ "name": "gid" }, { "name": "name" }, { "name": "email" }],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "user profile details and provider-specific payload fields",
  },
  "asana__list_workspaces": {
    "collectionKeys": ["data", "workspaces"],
    "collectionName": "workspaces",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "workspaces details and provider-specific payload fields",
  },
  "ashby__list_candidates": {
    "collectionKeys": ["results", "candidates"],
    "collectionName": "candidates",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "primaryEmailAddress", "kind": "object" },
      { "name": "position" },
      { "name": "company" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
    ],
    "outputFields": [{ "name": "nextCursor" }, { "name": "moreDataAvailable" }],
    "omitted": "resume file handles, social links, and custom field values",
  },
  "attio__query_records": {
    "collectionKeys": ["data", "records"],
    "collectionName": "records",
    "itemFields": [{ "name": "id", "kind": "object" }, { "name": "values", "kind": "object" }, {
      "name": "web_url",
    }, { "name": "created_at" }],
    "omitted": "full attribute value histories and provider-specific payload fields",
  },
  "basecamp__list_projects": {
    "collectionKeys": ["projects"],
    "collectionName": "projects",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "description" },
      { "name": "status" },
      { "name": "app_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
    ],
    "outputFields": [{ "name": "page" }],
    "omitted": "project dock tool references and provider-specific payload fields",
  },
  "basecamp__list_todolists": {
    "collectionKeys": ["todolists"],
    "collectionName": "todolists",
    "itemFields": [
      { "name": "id" },
      { "name": "title" },
      { "name": "completed" },
      { "name": "completed_ratio" },
      { "name": "app_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
    ],
    "outputFields": [{ "name": "page" }],
    "omitted": "list descriptions and provider-specific payload fields",
  },
  "basecamp__list_todos": {
    "collectionKeys": ["todos"],
    "collectionName": "todos",
    "itemFields": [
      { "name": "id" },
      { "name": "content" },
      { "name": "completed" },
      { "name": "due_on" },
      { "name": "app_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "assignees", "kind": "contact-array" },
    ],
    "outputFields": [{ "name": "page" }],
    "omitted": "to-do descriptions, comment counts, and provider-specific payload fields",
  },
  "bitbucket__list_pull_requests": {
    "collectionKeys": ["values", "pull_requests"],
    "collectionName": "pull_requests",
    "itemFields": [
      { "name": "id" },
      { "name": "title" },
      { "name": "state" },
      { "name": "created_on" },
      { "name": "updated_on" },
      { "name": "author", "kind": "contact" },
    ],
    "outputFields": [{ "name": "next" }, { "name": "page" }, { "name": "pagelen" }, {
      "name": "size",
    }],
    "omitted": "pull request descriptions, diffs, links, and provider-specific payload fields",
  },
  "bitbucket__list_repositories": {
    "collectionKeys": ["values", "repositories"],
    "collectionName": "repositories",
    "itemFields": [
      { "name": "uuid" },
      { "name": "name" },
      { "name": "full_name" },
      { "name": "slug" },
      { "name": "is_private" },
      { "name": "language" },
      { "name": "created_on" },
      { "name": "updated_on" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [{ "name": "next" }, { "name": "page" }, { "name": "pagelen" }, {
      "name": "size",
    }],
    "omitted": "repository links, clone URLs, and provider-specific payload fields",
  },
  "brevo__list_contacts": {
    "collectionKeys": ["contacts"],
    "collectionName": "contacts",
    "itemFields": [
      { "name": "id" },
      { "name": "email" },
      { "name": "emailBlacklisted" },
      { "name": "createdAt" },
      { "name": "modifiedAt" },
      { "name": "attributes", "kind": "object" },
    ],
    "outputFields": [{ "name": "count" }],
    "omitted": "SMS details, list membership, and custom attribute values",
  },
  "calendly__list_event_invitees": {
    "collectionKeys": ["collection", "invitees"],
    "collectionName": "invitees",
    "itemFields": [
      { "name": "uri" },
      { "name": "name" },
      { "name": "email" },
      { "name": "status" },
      { "name": "created_at" },
    ],
    "outputFields": [{ "name": "next_page_token" }],
    "omitted": "invitee questions/answers and provider-specific payload fields",
  },
  "calendly__list_event_types": {
    "collectionKeys": ["collection", "event_types"],
    "collectionName": "event_types",
    "itemFields": [
      { "name": "uri" },
      { "name": "name" },
      { "name": "slug" },
      { "name": "duration" },
      { "name": "active" },
      { "name": "scheduling_url" },
    ],
    "outputFields": [{ "name": "next_page_token" }],
    "omitted": "event type descriptions and provider-specific payload fields",
  },
  "calendly__list_scheduled_events": {
    "collectionKeys": ["collection", "events"],
    "collectionName": "events",
    "itemFields": [
      { "name": "uri" },
      { "name": "name" },
      { "name": "status" },
      { "name": "start_time" },
      { "name": "end_time" },
      { "name": "event_type" },
    ],
    "outputFields": [{ "name": "next_page_token" }],
    "omitted": "location details and provider-specific payload fields",
  },
  "circleci__list_pipelines": {
    "collectionKeys": ["items"],
    "collectionName": "pipelines",
    "itemFields": [
      { "name": "id" },
      { "name": "number" },
      { "name": "state" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "vcs", "kind": "object" },
    ],
    "outputFields": [{ "name": "next_page_token" }],
    "omitted": "trigger details, pipeline parameters, and provider-specific payload fields",
  },
  "circleci__list_workflows": {
    "collectionKeys": ["items"],
    "collectionName": "workflows",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "status" },
      { "name": "created_at" },
      { "name": "stopped_at" },
      { "name": "pipeline_number" },
    ],
    "outputFields": [{ "name": "next_page_token" }],
    "omitted": "workflow tags and provider-specific payload fields",
  },
  "close__list_leads": {
    "collectionKeys": ["data"],
    "collectionName": "leads",
    "itemFields": [
      { "name": "id" },
      { "name": "display_name" },
      { "name": "name" },
      { "name": "status_label" },
      { "name": "url" },
      { "name": "date_created" },
      { "name": "date_updated" },
    ],
    "outputFields": [{ "name": "has_more" }, { "name": "total_results" }],
    "omitted": "lead contacts, addresses, custom fields, and provider-specific payload fields",
  },
  "cloudflare__list_dns_records": {
    "collectionKeys": ["result"],
    "collectionName": "dns_records",
    "itemFields": [
      { "name": "id" },
      { "name": "type" },
      { "name": "name" },
      { "name": "content" },
      { "name": "proxied" },
      { "name": "ttl" },
      { "name": "modified_on" },
    ],
    "outputFields": [{ "name": "result_info", "kind": "object" }],
    "omitted": "record metadata and provider-specific payload fields",
  },
  "cloudflare__list_zones": {
    "collectionKeys": ["result"],
    "collectionName": "zones",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "status" },
      { "name": "paused" },
      { "name": "created_on" },
      { "name": "modified_on" },
    ],
    "outputFields": [{ "name": "result_info", "kind": "object" }],
    "omitted": "name servers, plan details, and provider-specific payload fields",
  },
  "coda__list_docs": {
    "collectionKeys": ["items"],
    "collectionName": "docs",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "browserLink" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [{ "name": "nextPageToken" }, { "name": "nextPageLink" }],
    "omitted": "doc icon, workspace, and provider-specific payload fields",
  },
  "coda__list_pages": {
    "collectionKeys": ["items"],
    "collectionName": "pages",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "browserLink" },
      { "name": "contentType" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
    ],
    "outputFields": [{ "name": "nextPageToken" }, { "name": "nextPageLink" }],
    "omitted": "page icon, parent/children references, and provider-specific payload fields",
  },
  "datadog__list_dashboards": {
    "collectionKeys": ["dashboards"],
    "collectionName": "dashboards",
    "itemFields": [{ "name": "id" }, { "name": "title" }, { "name": "url" }, {
      "name": "layout_type",
    }, { "name": "modified_at" }],
    "omitted": "dashboard widget definitions and provider-specific payload fields",
  },
  "datadog__list_monitors": {
    "collectionKeys": ["monitors"],
    "collectionName": "monitors",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "type" }, {
      "name": "overall_state",
    }, { "name": "tags", "kind": "string-array" }],
    "omitted": "monitor query definitions and provider-specific payload fields",
  },
  "dialpad__list_contacts": {
    "collectionKeys": ["items"],
    "collectionName": "contacts",
    "itemFields": [
      { "name": "id" },
      { "name": "display_name" },
      { "name": "first_name" },
      { "name": "last_name" },
      { "name": "emails", "kind": "string-array" },
      { "name": "phones", "kind": "string-array" },
      { "name": "company_name" },
    ],
    "outputFields": [{ "name": "cursor" }],
    "omitted": "contact details and provider-specific payload fields",
  },
  "digitalocean__list_databases": {
    "collectionKeys": ["databases"],
    "collectionName": "databases",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "engine" },
      { "name": "version" },
      { "name": "status" },
      { "name": "created_at" },
      { "name": "tags", "kind": "string-array" },
    ],
    "outputFields": [],
    "omitted": "connection credentials, maintenance windows, and provider-specific payload fields",
  },
  "digitalocean__list_droplets": {
    "collectionKeys": ["droplets"],
    "collectionName": "droplets",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "status" },
      { "name": "memory" },
      { "name": "vcpus" },
      { "name": "created_at" },
      { "name": "tags", "kind": "string-array" },
    ],
    "outputFields": [{ "name": "links", "kind": "object" }, { "name": "meta", "kind": "object" }],
    "omitted": "network interfaces, image details, and provider-specific payload fields",
  },
  "exa__search": {
    "collectionKeys": ["results"],
    "collectionName": "results",
    "itemFields": [{ "name": "id" }, { "name": "title" }, { "name": "url" }, {
      "name": "publishedDate",
    }, { "name": "author" }],
    "omitted": "page text, highlights, and provider-specific payload fields",
  },
  "fathom__list_meetings": {
    "collectionKeys": ["items", "meetings"],
    "collectionName": "meetings",
    "itemFields": [
      { "name": "title" },
      { "name": "meeting_title" },
      { "name": "recording_id" },
      { "name": "url" },
      { "name": "created_at" },
      { "name": "recording_start_time" },
      { "name": "recording_end_time" },
      { "name": "calendar_invitees", "kind": "contact-array" },
    ],
    "outputFields": [{ "name": "next_cursor" }, { "name": "limit" }],
    "omitted": "transcripts, summaries, action items, and CRM matches",
  },
  "firecrawl__search": {
    "collectionKeys": ["data.web", "data"],
    "collectionName": "results",
    "itemFields": [{ "name": "title" }, { "name": "url" }, {
      "name": "description",
      "maxLength": 300,
    }],
    "outputFields": [{ "name": "creditsUsed" }],
    "omitted": "scraped page content and provider-specific payload fields",
  },
  "fireflies__list_transcripts": {
    "collectionKeys": ["transcripts", "data"],
    "collectionName": "transcripts",
    "itemFields": [
      { "name": "id" },
      { "name": "title" },
      { "name": "date" },
      { "name": "duration" },
      { "name": "organizer_email", "kind": "contact" },
      { "name": "participants", "kind": "contact-array" },
      { "name": "transcript_url" },
    ],
    "outputFields": [{ "name": "skip" }],
    "omitted": "sentences, summaries, and audio/video URLs",
  },
  "folk__list_people": {
    "collectionKeys": ["items"],
    "collectionName": "people",
    "itemFields": [
      { "name": "id" },
      { "name": "fullName" },
      { "name": "firstName" },
      { "name": "lastName" },
      { "name": "jobTitle" },
      { "name": "emails", "kind": "string-array" },
    ],
    "outputFields": [{ "name": "pagination", "kind": "object" }],
    "omitted": "custom fields, group memberships, and provider-specific payload fields",
  },
  "gemini__list_models": {
    "collectionKeys": ["models"],
    "collectionName": "models",
    "itemFields": [{ "name": "name" }, { "name": "displayName" }, { "name": "inputTokenLimit" }, {
      "name": "outputTokenLimit",
    }],
    "outputFields": [{ "name": "nextPageToken" }],
    "omitted": "model capability details and provider-specific payload fields",
  },
  "github__get_issue": {
    "collectionKeys": ["issue", "data"],
    "collectionName": "issues",
    "itemFields": [
      { "name": "id" },
      { "name": "node_id" },
      { "name": "number" },
      { "name": "title" },
      { "name": "state" },
      { "name": "html_url" },
      { "name": "url" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "closed_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
    ],
    "singleItem": true,
    "omitted": "issue body, comments, timeline, and provider-specific payload fields",
  },
  "github__get_pr": {
    "collectionKeys": ["pullRequest", "data"],
    "collectionName": "pullRequests",
    "itemFields": [
      { "name": "id" },
      { "name": "node_id" },
      { "name": "number" },
      { "name": "title" },
      { "name": "state" },
      { "name": "html_url" },
      { "name": "url" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "closed_at" },
      { "name": "merged_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "draft" },
      { "name": "mergeable" },
    ],
    "singleItem": true,
    "omitted": "pull request body, diff, reviews, and provider-specific payload fields",
  },
  "github__list_commits": {
    "collectionKeys": ["commits", "data"],
    "collectionName": "commits",
    "itemFields": [{ "name": "sha" }, { "name": "node_id" }, { "name": "html_url" }, {
      "name": "author",
      "kind": "contact",
    }, { "name": "committer", "kind": "contact" }],
    "omitted": "full commit messages, verification payloads, and file details",
  },
  "github__list_issues": {
    "collectionKeys": ["issues", "nodes", "data"],
    "collectionName": "issues",
    "itemFields": [
      { "name": "id" },
      { "name": "node_id" },
      { "name": "number" },
      { "name": "title" },
      { "name": "state" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "author", "kind": "contact" },
      { "name": "user", "kind": "contact" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "created_at" },
      { "name": "updated_at" },
    ],
    "outputFields": [{ "name": "pageInfo", "kind": "object" }],
    "omitted": "issue bodies, comments, and provider-specific payload fields",
  },
  "github__list_prs": {
    "collectionKeys": ["pullRequests", "data"],
    "collectionName": "pullRequests",
    "itemFields": [
      { "name": "id" },
      { "name": "node_id" },
      { "name": "number" },
      { "name": "title" },
      { "name": "state" },
      { "name": "html_url" },
      { "name": "user", "kind": "contact" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "closed_at" },
      { "name": "merged_at" },
      { "name": "draft" },
    ],
    "omitted": "pull request bodies, diff details, and provider-specific payload fields",
  },
  "github__list_repos": {
    "collectionKeys": ["repositories", "data"],
    "collectionName": "repositories",
    "itemFields": [
      { "name": "id" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "full_name" },
      { "name": "owner", "kind": "contact" },
      { "name": "html_url" },
      { "name": "private" },
      { "name": "archived" },
      { "name": "open_issues_count" },
      { "name": "default_branch" },
      { "name": "updated_at" },
      { "name": "pushed_at" },
    ],
    "omitted": "repository descriptions and provider-specific payload fields",
  },
  "gmail__list_drafts": {
    "collectionKeys": ["drafts", "data"],
    "collectionName": "drafts",
    "itemFields": [{ "name": "id" }, { "name": "message", "kind": "object" }],
    "outputFields": [{ "name": "nextPageToken" }, { "name": "resultSizeEstimate" }],
    "omitted": "draft message bodies and provider-specific payload fields",
  },
  "gmail__list_emails": {
    "collectionKeys": ["messages", "data"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "threadId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "to" },
      { "name": "subject" },
      { "name": "date" },
      { "name": "internalDate" },
      { "name": "snippet", "maxLength": 300 },
      { "name": "labelIds", "kind": "string-array" },
      { "name": "isUnread" },
      { "name": "unread" },
    ],
    "outputFields": [{ "name": "nextPageToken" }, { "name": "resultSizeEstimate" }],
    "omitted": "large email bodies and provider-specific payload fields",
  },
  "gmail__list_history": {
    "collectionKeys": ["history", "data"],
    "collectionName": "history",
    "itemFields": [{ "name": "id" }, { "name": "messages", "kind": "object" }, {
      "name": "messagesAdded",
      "kind": "object",
    }, { "name": "messagesDeleted", "kind": "object" }],
    "outputFields": [{ "name": "nextPageToken" }, { "name": "historyId" }],
    "omitted": "history details and provider-specific payload fields",
  },
  "gmail__list_labels": {
    "collectionKeys": ["labels", "data"],
    "collectionName": "labels",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "type" }],
    "omitted": "label counters and provider-specific payload fields",
  },
  "gmail__list_threads": {
    "collectionKeys": ["threads", "data"],
    "collectionName": "threads",
    "itemFields": [{ "name": "id" }, { "name": "snippet", "maxLength": 300 }, {
      "name": "historyId",
    }],
    "outputFields": [{ "name": "nextPageToken" }, { "name": "resultSizeEstimate" }],
    "omitted": "large thread payloads and provider-specific fields",
  },
  "gmail__search_emails": {
    "collectionKeys": ["messages", "data"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "threadId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "to" },
      { "name": "subject" },
      { "name": "date" },
      { "name": "internalDate" },
      { "name": "snippet", "maxLength": 300 },
      { "name": "labelIds", "kind": "string-array" },
      { "name": "isUnread" },
      { "name": "unread" },
    ],
    "outputFields": [{ "name": "nextPageToken" }, { "name": "resultSizeEstimate" }],
    "omitted": "large email bodies and provider-specific payload fields",
  },
  "gong__list_calls": {
    "collectionKeys": ["calls"],
    "collectionName": "calls",
    "itemFields": [
      { "name": "id" },
      { "name": "title" },
      { "name": "started" },
      { "name": "duration" },
      { "name": "direction" },
      { "name": "primaryUserId" },
      { "name": "url" },
    ],
    "outputFields": [{ "name": "records", "kind": "object" }],
    "omitted": "media URLs, parties, and call system metadata",
  },
  "google-analytics__list_account_summaries": {
    "collectionKeys": ["accountSummaries"],
    "collectionName": "accountSummaries",
    "itemFields": [{ "name": "account" }, { "name": "displayName" }, {
      "name": "propertySummaries",
      "kind": "object",
    }],
    "outputFields": [{ "name": "nextPageToken" }],
    "omitted": "property detail fields beyond names and IDs",
  },
  "google-chat__list_messages": {
    "collectionKeys": ["messages"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "name" },
      { "name": "text", "maxLength": 300 },
      { "name": "sender", "kind": "contact" },
      { "name": "createTime" },
      { "name": "thread", "kind": "object" },
    ],
    "outputFields": [{ "name": "nextPageToken" }],
    "omitted": "cards, annotations, and provider-specific payload fields",
  },
  "google-chat__list_spaces": {
    "collectionKeys": ["spaces"],
    "collectionName": "spaces",
    "itemFields": [{ "name": "name" }, { "name": "displayName" }, { "name": "spaceType" }, {
      "name": "singleUserBotDm",
    }, { "name": "createTime" }],
    "outputFields": [{ "name": "nextPageToken" }],
    "omitted": "space details and provider-specific payload fields",
  },
  "gusto__list_employees": {
    "collectionKeys": ["employees", "data"],
    "collectionName": "employees",
    "itemFields": [
      { "name": "uuid" },
      { "name": "first_name" },
      { "name": "last_name" },
      { "name": "email" },
      { "name": "department" },
      { "name": "terminated" },
      { "name": "manager_uuid" },
    ],
    "outputFields": [{ "name": "page" }, { "name": "per" }],
    "omitted": "compensation, home address, and job history details",
  },
  "harvest__invoice_report": {
    "collectionKeys": ["results", "data"],
    "collectionName": "invoiceReports",
    "itemFields": [
      { "name": "client_id" },
      { "name": "client_name" },
      { "name": "invoice_id" },
      { "name": "invoice_number" },
      { "name": "amount" },
      { "name": "currency" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "invoice report details and provider-specific payload fields",
  },
  "harvest__list_accounts": {
    "collectionKeys": ["accounts", "data"],
    "collectionName": "accounts",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "product" }],
    "omitted": "account auth policy and provider-specific fields",
  },
  "harvest__list_clients": {
    "collectionKeys": ["clients", "data"],
    "collectionName": "clients",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "currency" }, {
      "name": "is_active",
    }, { "name": "updated_at" }],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "client addresses, statement keys, and provider-specific payload fields",
  },
  "harvest__list_invoice_payments": {
    "collectionKeys": ["invoice_payments", "data"],
    "collectionName": "invoicePayments",
    "itemFields": [{ "name": "id" }, { "name": "amount" }, { "name": "paid_at" }, {
      "name": "created_at",
    }, { "name": "updated_at" }],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "payment notes and provider-specific payload fields",
  },
  "harvest__list_invoices": {
    "collectionKeys": ["invoices", "data"],
    "collectionName": "invoices",
    "itemFields": [
      { "name": "id" },
      { "name": "number" },
      { "name": "state" },
      { "name": "amount" },
      { "name": "due_date" },
      { "name": "client", "kind": "object" },
      { "name": "updated_at" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "invoice notes, line items, and provider-specific payload fields",
  },
  "harvest__list_project_task_assignments": {
    "collectionKeys": ["task_assignments", "data"],
    "collectionName": "taskAssignments",
    "itemFields": [
      { "name": "id" },
      { "name": "task", "kind": "object" },
      { "name": "project", "kind": "object" },
      { "name": "is_active" },
      { "name": "updated_at" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "task assignment rates and provider-specific payload fields",
  },
  "harvest__list_projects": {
    "collectionKeys": ["projects", "data"],
    "collectionName": "projects",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "code" },
      { "name": "is_active" },
      { "name": "client", "kind": "object" },
      { "name": "updated_at" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "project budgets, notes, rates, and provider-specific payload fields",
  },
  "harvest__list_tasks": {
    "collectionKeys": ["tasks", "data"],
    "collectionName": "tasks",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "is_active" }, {
      "name": "is_default",
    }, { "name": "updated_at" }],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "task rates and provider-specific payload fields",
  },
  "harvest__list_time_entries": {
    "collectionKeys": ["time_entries", "data"],
    "collectionName": "timeEntries",
    "itemFields": [
      { "name": "id" },
      { "name": "spent_date" },
      { "name": "hours" },
      { "name": "billable" },
      { "name": "user", "kind": "contact" },
      { "name": "client", "kind": "object" },
      { "name": "project", "kind": "object" },
      { "name": "task", "kind": "object" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "notes, rates, invoice details, and provider-specific payload fields",
  },
  "harvest__list_users": {
    "collectionKeys": ["users", "data"],
    "collectionName": "users",
    "itemFields": [
      { "name": "id" },
      { "name": "email" },
      { "name": "first_name" },
      { "name": "last_name" },
      { "name": "is_active" },
      { "name": "timezone" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "user rates, avatars, and provider-specific payload fields",
  },
  "harvest__time_report_by_client": {
    "collectionKeys": ["results", "data"],
    "collectionName": "clientTimeReports",
    "itemFields": [
      { "name": "client_id" },
      { "name": "client_name" },
      { "name": "total_hours" },
      { "name": "billable_hours" },
      { "name": "billable_amount" },
      { "name": "currency" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "client report details and provider-specific payload fields",
  },
  "harvest__time_report_by_project": {
    "collectionKeys": ["results", "data"],
    "collectionName": "projectTimeReports",
    "itemFields": [
      { "name": "project_id" },
      { "name": "project_name" },
      { "name": "client_id" },
      { "name": "client_name" },
      { "name": "total_hours" },
      { "name": "billable_hours" },
      { "name": "billable_amount" },
      { "name": "currency" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "report breakdown details and provider-specific payload fields",
  },
  "harvest__time_report_by_task": {
    "collectionKeys": ["results", "data"],
    "collectionName": "taskTimeReports",
    "itemFields": [
      { "name": "task_id" },
      { "name": "task_name" },
      { "name": "total_hours" },
      { "name": "billable_hours" },
      { "name": "billable_amount" },
      { "name": "currency" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "task report details and provider-specific payload fields",
  },
  "harvest__time_report_by_team": {
    "collectionKeys": ["results", "data"],
    "collectionName": "teamTimeReports",
    "itemFields": [
      { "name": "user_id" },
      { "name": "user_name" },
      { "name": "total_hours" },
      { "name": "billable_hours" },
      { "name": "billable_amount" },
      { "name": "currency" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "team report details and provider-specific payload fields",
  },
  "jira__list_comments": {
    "collectionKeys": ["comments", "data"],
    "collectionName": "comments",
    "itemFields": [
      { "name": "id" },
      { "name": "body", "kind": "object" },
      { "name": "author", "kind": "contact" },
      { "name": "created" },
      { "name": "updated" },
    ],
    "outputFields": [{ "name": "total" }, { "name": "startAt" }, { "name": "maxResults" }],
    "omitted": "full comment payloads and provider-specific fields",
  },
  "jira__list_projects": {
    "collectionKeys": ["values", "projects", "data"],
    "collectionName": "projects",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "projects details and provider-specific payload fields",
  },
  "jira__list_sites": {
    "collectionKeys": ["values", "sites", "data"],
    "collectionName": "sites",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "sites details and provider-specific payload fields",
  },
  "jira__search_issues": {
    "collectionKeys": ["issues", "data"],
    "collectionName": "issues",
    "itemFields": [
      { "name": "id" },
      { "name": "key" },
      { "name": "summary" },
      { "name": "status", "kind": "object" },
      { "name": "assignee", "kind": "contact" },
      { "name": "created" },
      { "name": "updated" },
    ],
    "outputFields": [{ "name": "total" }, { "name": "startAt" }, { "name": "maxResults" }],
    "omitted": "issue descriptions, comments, changelog, and provider-specific payload fields",
  },
  "jira__search_users": {
    "collectionKeys": ["users", "values"],
    "collectionName": "users",
    "itemFields": [{ "name": "accountId" }, { "name": "displayName" }, { "name": "emailAddress" }, {
      "name": "active",
    }, { "name": "accountType" }],
    "omitted": "avatar URLs, timezone, and provider-specific profile fields",
  },
  "jotform__list_forms": {
    "collectionKeys": ["content", "forms"],
    "collectionName": "forms",
    "itemFields": [
      { "name": "id" },
      { "name": "title" },
      { "name": "status" },
      { "name": "count" },
      { "name": "new" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "url" },
    ],
    "outputFields": [{ "name": "resultSet", "kind": "object" }],
    "omitted": "form layout and per-form settings",
  },
  "klaviyo__list_lists": {
    "collectionKeys": ["data", "lists"],
    "collectionName": "lists",
    "itemFields": [{ "name": "id" }, { "name": "attributes", "kind": "object" }],
    "outputFields": [{ "name": "next" }],
    "omitted": "list metadata beyond name and created/updated timestamps",
  },
  "klaviyo__list_profiles": {
    "collectionKeys": ["data", "profiles"],
    "collectionName": "profiles",
    "itemFields": [{ "name": "id" }, { "name": "attributes", "kind": "object" }],
    "outputFields": [{ "name": "next" }],
    "omitted": "profile location/subscription detail fields",
  },
  "lever__list_opportunities": {
    "collectionKeys": ["data", "opportunities"],
    "collectionName": "opportunities",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "emails", "kind": "string-array" },
      { "name": "stage" },
      { "name": "origin" },
      { "name": "tags", "kind": "string-array" },
      { "name": "createdAt" },
      { "name": "lastInteractionAt" },
      { "name": "urls", "kind": "object" },
    ],
    "outputFields": [{ "name": "hasNext" }, { "name": "next" }],
    "omitted": "applications, resumes, and contact metadata",
  },
  "linear__list_issue_labels": {
    "collectionKeys": ["issueLabels", "nodes", "data"],
    "collectionName": "issueLabels",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "color" }, {
      "name": "description",
    }],
    "outputFields": [{ "name": "pageInfo", "kind": "object" }],
    "omitted": "label team details and provider-specific payload fields",
  },
  "linear__list_projects": {
    "collectionKeys": ["projects", "nodes", "data"],
    "collectionName": "projects",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "projects details and provider-specific payload fields",
  },
  "linear__list_teams": {
    "collectionKeys": ["teams", "nodes", "data"],
    "collectionName": "teams",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "teams details and provider-specific payload fields",
  },
  "linear__list_users": {
    "collectionKeys": ["users", "nodes", "data"],
    "collectionName": "users",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "email" },
      { "name": "active" },
      { "name": "displayName" },
    ],
    "outputFields": [{ "name": "pageInfo", "kind": "object" }],
    "omitted": "user avatars and provider-specific payload fields",
  },
  "linear__list_workflow_states": {
    "collectionKeys": ["states", "nodes", "data"],
    "collectionName": "workflowStates",
    "itemFields": [
      { "name": "id" },
      { "name": "gid" },
      { "name": "key" },
      { "name": "node_id" },
      { "name": "name" },
      { "name": "title" },
      { "name": "summary" },
      { "name": "subject" },
      { "name": "number" },
      { "name": "state" },
      { "name": "status" },
      { "name": "url" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "user", "kind": "contact" },
      { "name": "author", "kind": "contact" },
      { "name": "created_by", "kind": "contact" },
      { "name": "assignee", "kind": "contact" },
      { "name": "owner", "kind": "contact" },
    ],
    "outputFields": [
      { "name": "nextPageToken" },
      { "name": "next_page" },
      { "name": "next" },
      { "name": "offset" },
      { "name": "total" },
      { "name": "per_page" },
      { "name": "page" },
    ],
    "omitted": "workflowStates details and provider-specific payload fields",
  },
  "linear__search_issues": {
    "collectionKeys": ["searchIssues", "issues", "nodes", "data"],
    "collectionName": "issues",
    "itemFields": [
      { "name": "id" },
      { "name": "identifier" },
      { "name": "title" },
      { "name": "state", "kind": "object" },
      { "name": "assignee", "kind": "contact" },
      { "name": "url" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
    ],
    "outputFields": [{ "name": "pageInfo", "kind": "object" }],
    "omitted": "issue descriptions, comments, and provider-specific payload fields",
  },
  "metabase__list_databases": {
    "collectionKeys": ["data"],
    "collectionName": "databases",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "engine" }, {
      "name": "created_at",
    }, { "name": "updated_at" }],
    "outputFields": [{ "name": "total" }],
    "omitted": "connection details and provider-specific payload fields",
  },
  "mistral__list_models": {
    "collectionKeys": ["data", "models"],
    "collectionName": "models",
    "itemFields": [{ "name": "id" }, { "name": "owned_by" }, { "name": "created" }, {
      "name": "max_context_length",
    }],
    "omitted": "model capability details and provider-specific payload fields",
  },
  "mixpanel__list_cohorts": {
    "collectionKeys": ["cohorts"],
    "collectionName": "cohorts",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "count" },
      { "name": "created" },
      { "name": "is_visible" },
    ],
    "omitted": "cohort descriptions and provider-specific payload fields",
  },
  "neon__list_branches": {
    "collectionKeys": ["branches"],
    "collectionName": "branches",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "parent_id" },
      { "name": "default" },
      { "name": "current_state" },
      { "name": "created_at" },
    ],
    "omitted": "branch size/usage metrics and provider-specific payload fields",
  },
  "neon__list_projects": {
    "collectionKeys": ["projects"],
    "collectionName": "projects",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "region_id" },
      { "name": "pg_version" },
      { "name": "created_at" },
      { "name": "updated_at" },
    ],
    "omitted": "compute settings, quotas, and provider-specific payload fields",
  },
  "openai__list_models": {
    "collectionKeys": ["data", "models"],
    "collectionName": "models",
    "itemFields": [{ "name": "id" }, { "name": "owned_by" }, { "name": "created" }],
    "omitted": "model capability details and provider-specific payload fields",
  },
  "outlook__find_free_time": {
    "collectionKeys": ["value", "schedules", "data"],
    "collectionName": "schedules",
    "itemFields": [
      { "name": "scheduleId" },
      { "name": "availabilityView" },
      { "name": "scheduleItems", "kind": "object" },
      { "name": "workingHours", "kind": "object" },
      { "name": "error", "kind": "object" },
    ],
    "omitted": "provider-specific schedule diagnostics and expanded free/busy payload fields",
  },
  "outlook__find_meeting_times": {
    "collectionKeys": ["meetingTimeSuggestions", "value", "data"],
    "collectionName": "meetingTimeSuggestions",
    "itemFields": [
      { "name": "confidence" },
      { "name": "organizerAvailability" },
      { "name": "attendeeAvailability", "kind": "object" },
      { "name": "meetingTimeSlot", "kind": "object" },
      { "name": "locations", "kind": "object" },
      { "name": "suggestionReason", "maxLength": 300 },
    ],
    "omitted": "provider-specific meeting suggestion diagnostics",
  },
  "outlook__get_event_instances": {
    "collectionKeys": ["value", "events", "data"],
    "collectionName": "events",
    "itemFields": [
      { "name": "id" },
      { "name": "subject" },
      { "name": "organizer", "kind": "contact" },
      { "name": "attendees", "kind": "contact-array" },
      { "name": "start", "kind": "object" },
      { "name": "end", "kind": "object" },
      { "name": "location", "kind": "object" },
      { "name": "showAs" },
      { "name": "responseStatus", "kind": "object" },
      { "name": "isOnlineMeeting" },
      { "name": "webLink" },
      { "name": "bodyPreview", "maxLength": 300 },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "full event bodies and provider-specific payload fields",
  },
  "outlook__get_schedule": {
    "collectionKeys": ["value", "schedules", "data"],
    "collectionName": "schedules",
    "itemFields": [
      { "name": "scheduleId" },
      { "name": "availabilityView" },
      { "name": "scheduleItems", "kind": "object" },
      { "name": "workingHours", "kind": "object" },
      { "name": "error", "kind": "object" },
    ],
    "omitted": "provider-specific schedule diagnostics and expanded free/busy payload fields",
  },
  "outlook__list_attachments": {
    "collectionKeys": ["value", "attachments", "data"],
    "collectionName": "attachments",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "contentType" },
      { "name": "size" },
      { "name": "isInline" },
      { "name": "lastModifiedDateTime" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "attachment binary content and provider-specific payload fields",
  },
  "outlook__list_calendar_view": {
    "collectionKeys": ["value", "events", "data"],
    "collectionName": "events",
    "itemFields": [
      { "name": "id" },
      { "name": "subject" },
      { "name": "organizer", "kind": "contact" },
      { "name": "attendees", "kind": "contact-array" },
      { "name": "start", "kind": "object" },
      { "name": "end", "kind": "object" },
      { "name": "location", "kind": "object" },
      { "name": "showAs" },
      { "name": "responseStatus", "kind": "object" },
      { "name": "isOnlineMeeting" },
      { "name": "webLink" },
      { "name": "bodyPreview", "maxLength": 300 },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "full event bodies and provider-specific payload fields",
  },
  "outlook__list_calendars": {
    "collectionKeys": ["value", "calendars", "data"],
    "collectionName": "calendars",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "color" },
      { "name": "isDefaultCalendar" },
      { "name": "canEdit" },
      { "name": "canShare" },
      { "name": "owner", "kind": "object" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "calendar provider-specific payload fields",
  },
  "outlook__list_categories": {
    "collectionKeys": ["value", "categories", "data"],
    "collectionName": "categories",
    "itemFields": [{ "name": "id" }, { "name": "displayName" }, { "name": "color" }],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "category provider-specific payload fields",
  },
  "outlook__list_conversation_messages": {
    "collectionKeys": ["value", "data", "messages"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "conversationId" },
      { "name": "internetMessageId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "toRecipients", "kind": "contact-array" },
      { "name": "ccRecipients", "kind": "contact-array" },
      { "name": "subject" },
      { "name": "receivedDateTime" },
      { "name": "sentDateTime" },
      { "name": "bodyPreview", "maxLength": 300 },
      { "name": "categories", "kind": "string-array" },
      { "name": "isRead" },
      { "name": "importance" },
      { "name": "hasAttachments" },
      { "name": "webLink" },
      { "name": "flag", "kind": "object" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "large email bodies and provider-specific message fields",
  },
  "outlook__list_drafts": {
    "collectionKeys": ["value", "data", "messages"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "conversationId" },
      { "name": "internetMessageId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "toRecipients", "kind": "contact-array" },
      { "name": "ccRecipients", "kind": "contact-array" },
      { "name": "subject" },
      { "name": "receivedDateTime" },
      { "name": "sentDateTime" },
      { "name": "bodyPreview", "maxLength": 300 },
      { "name": "categories", "kind": "string-array" },
      { "name": "isRead" },
      { "name": "importance" },
      { "name": "hasAttachments" },
      { "name": "webLink" },
      { "name": "flag", "kind": "object" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "large email bodies and provider-specific message fields",
  },
  "outlook__list_emails": {
    "collectionKeys": ["value", "data", "messages"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "conversationId" },
      { "name": "internetMessageId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "toRecipients", "kind": "contact-array" },
      { "name": "ccRecipients", "kind": "contact-array" },
      { "name": "subject" },
      { "name": "receivedDateTime" },
      { "name": "sentDateTime" },
      { "name": "bodyPreview", "maxLength": 300 },
      { "name": "categories", "kind": "string-array" },
      { "name": "isRead" },
      { "name": "importance" },
      { "name": "hasAttachments" },
      { "name": "webLink" },
      { "name": "flag", "kind": "object" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "large email bodies and provider-specific message fields",
  },
  "outlook__list_event_attachments": {
    "collectionKeys": ["value", "attachments", "data"],
    "collectionName": "attachments",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "contentType" },
      { "name": "size" },
      { "name": "isInline" },
      { "name": "lastModifiedDateTime" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "attachment binary content and provider-specific payload fields",
  },
  "outlook__list_events": {
    "collectionKeys": ["value", "events", "data"],
    "collectionName": "events",
    "itemFields": [
      { "name": "id" },
      { "name": "subject" },
      { "name": "organizer", "kind": "contact" },
      { "name": "attendees", "kind": "contact-array" },
      { "name": "start", "kind": "object" },
      { "name": "end", "kind": "object" },
      { "name": "location", "kind": "object" },
      { "name": "showAs" },
      { "name": "responseStatus", "kind": "object" },
      { "name": "isOnlineMeeting" },
      { "name": "webLink" },
      { "name": "bodyPreview", "maxLength": 300 },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "full event bodies and provider-specific payload fields",
  },
  "outlook__list_folders": {
    "collectionKeys": ["value", "folders", "data"],
    "collectionName": "folders",
    "itemFields": [
      { "name": "id" },
      { "name": "displayName" },
      { "name": "parentFolderId" },
      { "name": "childFolderCount" },
      { "name": "unreadItemCount" },
      { "name": "totalItemCount" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "folder provider-specific payload fields",
  },
  "outlook__list_group_thread_posts": {
    "collectionKeys": ["value", "data", "posts"],
    "collectionName": "posts",
    "itemFields": [
      { "name": "id" },
      { "name": "conversationId" },
      { "name": "conversationThreadId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "newParticipants", "kind": "contact-array" },
      { "name": "receivedDateTime" },
      { "name": "hasAttachments" },
      { "name": "body", "kind": "object" },
      { "name": "importance" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "large group post bodies and provider-specific post fields",
  },
  "outlook__list_group_threads": {
    "collectionKeys": ["value", "data", "threads"],
    "collectionName": "threads",
    "itemFields": [
      { "name": "id" },
      { "name": "topic" },
      { "name": "hasAttachments" },
      { "name": "lastDeliveredDateTime" },
      { "name": "uniqueSenders", "kind": "string-array" },
      { "name": "preview", "maxLength": 300 },
      { "name": "isLocked" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "large group thread payload fields",
  },
  "outlook__list_shared_mailbox_emails": {
    "collectionKeys": ["value", "data", "messages"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "conversationId" },
      { "name": "internetMessageId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "toRecipients", "kind": "contact-array" },
      { "name": "ccRecipients", "kind": "contact-array" },
      { "name": "subject" },
      { "name": "receivedDateTime" },
      { "name": "sentDateTime" },
      { "name": "bodyPreview", "maxLength": 300 },
      { "name": "categories", "kind": "string-array" },
      { "name": "isRead" },
      { "name": "importance" },
      { "name": "hasAttachments" },
      { "name": "webLink" },
      { "name": "flag", "kind": "object" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "large email bodies and provider-specific message fields",
  },
  "outlook__search_emails": {
    "collectionKeys": ["value", "data", "messages"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "conversationId" },
      { "name": "internetMessageId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "toRecipients", "kind": "contact-array" },
      { "name": "ccRecipients", "kind": "contact-array" },
      { "name": "subject" },
      { "name": "receivedDateTime" },
      { "name": "sentDateTime" },
      { "name": "bodyPreview", "maxLength": 300 },
      { "name": "categories", "kind": "string-array" },
      { "name": "isRead" },
      { "name": "importance" },
      { "name": "hasAttachments" },
      { "name": "webLink" },
      { "name": "flag", "kind": "object" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "large email bodies and provider-specific message fields",
  },
  "outlook__search_shared_mailbox_emails": {
    "collectionKeys": ["value", "data", "messages"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "id" },
      { "name": "conversationId" },
      { "name": "internetMessageId" },
      { "name": "from", "kind": "contact" },
      { "name": "sender", "kind": "contact" },
      { "name": "toRecipients", "kind": "contact-array" },
      { "name": "ccRecipients", "kind": "contact-array" },
      { "name": "subject" },
      { "name": "receivedDateTime" },
      { "name": "sentDateTime" },
      { "name": "bodyPreview", "maxLength": 300 },
      { "name": "categories", "kind": "string-array" },
      { "name": "isRead" },
      { "name": "importance" },
      { "name": "hasAttachments" },
      { "name": "webLink" },
      { "name": "flag", "kind": "object" },
    ],
    "outputFields": [{ "name": "@odata.nextLink" }, { "name": "@odata.count" }],
    "omitted": "large email bodies and provider-specific message fields",
  },
  "pagerduty__list_incidents": {
    "collectionKeys": ["incidents"],
    "collectionName": "incidents",
    "itemFields": [
      { "name": "id" },
      { "name": "incident_number" },
      { "name": "title" },
      { "name": "status" },
      { "name": "urgency" },
      { "name": "html_url" },
      { "name": "created_at" },
      { "name": "service", "kind": "object" },
    ],
    "outputFields": [{ "name": "offset" }, { "name": "limit" }, { "name": "more" }, {
      "name": "total",
    }],
    "omitted": "incident bodies, alert details, and provider-specific payload fields",
  },
  "pagerduty__list_services": {
    "collectionKeys": ["services"],
    "collectionName": "services",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "status" }, {
      "name": "html_url",
    }, { "name": "created_at" }],
    "outputFields": [{ "name": "offset" }, { "name": "limit" }, { "name": "more" }, {
      "name": "total",
    }],
    "omitted":
      "integration configs, escalation policy details, and provider-specific payload fields",
  },
  "paypal__list_invoices": {
    "collectionKeys": ["items", "invoices"],
    "collectionName": "invoices",
    "itemFields": [{ "name": "id" }, { "name": "status" }, { "name": "detail", "kind": "object" }],
    "outputFields": [{ "name": "total_items" }, { "name": "total_pages" }],
    "omitted": "line items and amount breakdowns",
  },
  "paypal__list_transactions": {
    "collectionKeys": ["transaction_details", "transactions"],
    "collectionName": "transactions",
    "itemFields": [{ "name": "transaction_info", "kind": "object" }],
    "outputFields": [{ "name": "total_items" }, { "name": "total_pages" }, { "name": "page" }],
    "omitted": "payer, cart, and shipping detail blocks",
  },
  "perplexity__search_web": {
    "collectionKeys": ["results"],
    "collectionName": "results",
    "itemFields": [
      { "name": "title" },
      { "name": "url" },
      { "name": "snippet", "maxLength": 300 },
      { "name": "date" },
    ],
    "omitted": "full result snippets and provider-specific payload fields",
  },
  "posthog__list_feature_flags": {
    "collectionKeys": ["results"],
    "collectionName": "feature_flags",
    "itemFields": [{ "name": "id" }, { "name": "key" }, { "name": "name" }, { "name": "active" }, {
      "name": "created_at",
    }],
    "outputFields": [{ "name": "count" }, { "name": "next" }],
    "omitted": "rollout filters, variants, and provider-specific payload fields",
  },
  "posthog__list_persons": {
    "collectionKeys": ["results"],
    "collectionName": "persons",
    "itemFields": [{ "name": "id" }, { "name": "name" }, {
      "name": "distinct_ids",
      "kind": "string-array",
    }, { "name": "created_at" }],
    "outputFields": [{ "name": "count" }, { "name": "next" }],
    "omitted": "person properties and provider-specific payload fields",
  },
  "productboard__list_entities": {
    "collectionKeys": ["data"],
    "collectionName": "entities",
    "itemFields": [
      { "name": "id" },
      { "name": "type" },
      { "name": "fields", "kind": "object" },
      { "name": "createdAt" },
      { "name": "updatedAt" },
      { "name": "links", "kind": "object" },
    ],
    "outputFields": [{ "name": "links", "kind": "object" }],
    "omitted": "entity relationships, custom fields, and provider-specific payload fields",
  },
  "productboard__list_notes": {
    "collectionKeys": ["data"],
    "collectionName": "notes",
    "itemFields": [{ "name": "id" }, { "name": "type" }, { "name": "fields", "kind": "object" }, {
      "name": "links",
      "kind": "object",
    }],
    "outputFields": [{ "name": "links", "kind": "object" }],
    "omitted": "note content bodies, relationships, and provider-specific payload fields",
  },
  "razorpay__list_payments": {
    "collectionKeys": ["items", "payments"],
    "collectionName": "payments",
    "itemFields": [
      { "name": "id" },
      { "name": "amount" },
      { "name": "currency" },
      { "name": "status" },
      { "name": "method" },
      { "name": "order_id" },
      { "name": "email" },
      { "name": "contact" },
      { "name": "created_at" },
    ],
    "outputFields": [{ "name": "count" }],
    "omitted": "card/UPI instrument details and acquirer data",
  },
  "resend__list_domains": {
    "collectionKeys": ["data", "domains"],
    "collectionName": "domains",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "status" },
      { "name": "region" },
      { "name": "created_at" },
    ],
    "outputFields": [{ "name": "next" }],
    "omitted": "DNS records and tracking settings",
  },
  "salesflare__list_contacts": {
    "collectionKeys": ["items", "data"],
    "collectionName": "contacts",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "firstname" },
      { "name": "lastname" },
      { "name": "email" },
      { "name": "phone_number" },
      { "name": "organisation" },
    ],
    "omitted": "social profiles, addresses, and provider-specific payload fields",
  },
  "segment__list_destinations": {
    "collectionKeys": ["data.destinations", "destinations"],
    "collectionName": "destinations",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "enabled" }, {
      "name": "sourceId",
    }, { "name": "metadata", "kind": "object" }],
    "outputFields": [{ "name": "pagination", "kind": "object" }],
    "omitted": "destination settings and provider-specific payload fields",
  },
  "segment__list_sources": {
    "collectionKeys": ["data.sources", "sources"],
    "collectionName": "sources",
    "itemFields": [
      { "name": "id" },
      { "name": "slug" },
      { "name": "name" },
      { "name": "enabled" },
      { "name": "workspaceId" },
      { "name": "metadata", "kind": "object" },
    ],
    "outputFields": [{ "name": "pagination", "kind": "object" }],
    "omitted": "source settings, write keys, and provider-specific payload fields",
  },
  "sendgrid__list_contacts": {
    "collectionKeys": ["result", "contacts"],
    "collectionName": "contacts",
    "itemFields": [{ "name": "id" }, { "name": "email" }, { "name": "first_name" }, {
      "name": "last_name",
    }, { "name": "updated_at" }],
    "outputFields": [{ "name": "contact_count" }, { "name": "_metadata", "kind": "object" }],
    "omitted": "address, custom fields, and list membership details",
  },
  "shortcut__list_epics": {
    "collectionKeys": ["epics"],
    "collectionName": "epics",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "state" },
      { "name": "app_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "owner_ids", "kind": "string-array" },
    ],
    "outputFields": [],
    "omitted": "epic stats, milestone links, and provider-specific payload fields",
  },
  "shortcut__search_stories": {
    "collectionKeys": ["data"],
    "collectionName": "stories",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "story_type" },
      { "name": "workflow_state_id" },
      { "name": "epic_id" },
      { "name": "app_url" },
      { "name": "created_at" },
      { "name": "updated_at" },
      { "name": "owner_ids", "kind": "string-array" },
    ],
    "outputFields": [{ "name": "next" }, { "name": "total" }],
    "omitted": "story descriptions, tasks, comments, and provider-specific payload fields",
  },
  "slack__list_channels": {
    "collectionKeys": ["channels", "data"],
    "collectionName": "channels",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "is_channel" },
      { "name": "is_group" },
      { "name": "is_im" },
      { "name": "is_private" },
      { "name": "is_archived" },
      { "name": "num_members" },
    ],
    "outputFields": [{ "name": "response_metadata", "kind": "object" }],
    "omitted": "channel topics, purposes, and provider-specific payload fields",
  },
  "slack__list_users": {
    "collectionKeys": ["members", "users", "data"],
    "collectionName": "users",
    "itemFields": [
      { "name": "id" },
      { "name": "name" },
      { "name": "real_name" },
      { "name": "team_id" },
      { "name": "is_bot" },
      { "name": "deleted" },
    ],
    "outputFields": [{ "name": "response_metadata", "kind": "object" }],
    "omitted": "user profiles, avatars, and provider-specific payload fields",
  },
  "square__list_payments": {
    "collectionKeys": ["payments"],
    "collectionName": "payments",
    "itemFields": [
      { "name": "id" },
      { "name": "status" },
      { "name": "amount_money", "kind": "object" },
      { "name": "source_type" },
      { "name": "order_id" },
      { "name": "customer_id" },
      { "name": "created_at" },
      { "name": "updated_at" },
    ],
    "outputFields": [{ "name": "cursor" }],
    "omitted": "card details, processing fees, and risk evaluation blocks",
  },
  "stripe__list_charges": {
    "collectionKeys": ["data"],
    "collectionName": "charges",
    "itemFields": [
      { "name": "id" },
      { "name": "amount" },
      { "name": "currency" },
      { "name": "status" },
      { "name": "paid" },
      { "name": "refunded" },
      { "name": "customer" },
      { "name": "created" },
    ],
    "outputFields": [{ "name": "has_more" }],
    "omitted": "payment method details, outcome data, and provider-specific payload fields",
  },
  "stripe__list_customers": {
    "collectionKeys": ["data"],
    "collectionName": "customers",
    "itemFields": [
      { "name": "id" },
      { "name": "email" },
      { "name": "name" },
      { "name": "created" },
      { "name": "currency" },
      { "name": "delinquent" },
    ],
    "outputFields": [{ "name": "has_more" }],
    "omitted": "customer addresses, invoice settings, and provider-specific payload fields",
  },
  "stripe__list_invoices": {
    "collectionKeys": ["data"],
    "collectionName": "invoices",
    "itemFields": [
      { "name": "id" },
      { "name": "customer" },
      { "name": "status" },
      { "name": "amount_due" },
      { "name": "amount_paid" },
      { "name": "currency" },
      { "name": "created" },
    ],
    "outputFields": [{ "name": "has_more" }],
    "omitted": "invoice line items, tax details, and provider-specific payload fields",
  },
  "stripe__list_payments": {
    "collectionKeys": ["data"],
    "collectionName": "payment_intents",
    "itemFields": [
      { "name": "id" },
      { "name": "amount" },
      { "name": "currency" },
      { "name": "status" },
      { "name": "customer" },
      { "name": "created" },
      { "name": "description" },
    ],
    "outputFields": [{ "name": "has_more" }],
    "omitted": "payment method details, charge breakdowns, and provider-specific payload fields",
  },
  "stripe__list_subscriptions": {
    "collectionKeys": ["data"],
    "collectionName": "subscriptions",
    "itemFields": [
      { "name": "id" },
      { "name": "customer" },
      { "name": "status" },
      { "name": "current_period_end" },
      { "name": "cancel_at_period_end" },
      { "name": "created" },
    ],
    "outputFields": [{ "name": "has_more" }],
    "omitted": "subscription items, pricing tiers, and provider-specific payload fields",
  },
  "tavily__search": {
    "collectionKeys": ["results"],
    "collectionName": "results",
    "itemFields": [
      { "name": "title" },
      { "name": "url" },
      { "name": "content", "maxLength": 300 },
      { "name": "score" },
      { "name": "published_date" },
    ],
    "omitted": "raw page content and provider-specific payload fields",
  },
  "todoist__list_projects": {
    "collectionKeys": ["results", "projects"],
    "collectionName": "projects",
    "itemFields": [{ "name": "id" }, { "name": "name" }, { "name": "color" }, {
      "name": "is_favorite",
    }, { "name": "parent_id" }],
    "outputFields": [{ "name": "next_cursor" }],
    "omitted": "project view settings and provider-specific payload fields",
  },
  "todoist__list_tasks": {
    "collectionKeys": ["results", "tasks"],
    "collectionName": "tasks",
    "itemFields": [
      { "name": "id" },
      { "name": "content" },
      { "name": "project_id" },
      { "name": "priority" },
      { "name": "due", "kind": "object" },
      { "name": "checked" },
      { "name": "added_at" },
    ],
    "outputFields": [{ "name": "next_cursor" }],
    "omitted": "task descriptions and provider-specific payload fields",
  },
  "twilio__list_messages": {
    "collectionKeys": ["messages"],
    "collectionName": "messages",
    "itemFields": [
      { "name": "sid" },
      { "name": "to" },
      { "name": "from" },
      { "name": "status" },
      { "name": "direction" },
      { "name": "date_sent" },
      { "name": "body", "maxLength": 160 },
    ],
    "outputFields": [{ "name": "next_page_uri" }],
    "omitted": "delivery error details, pricing, and provider-specific payload fields",
  },
  "typeform__list_forms": {
    "collectionKeys": ["items", "forms"],
    "collectionName": "forms",
    "itemFields": [{ "name": "id" }, { "name": "title" }, { "name": "type" }, {
      "name": "last_updated_at",
    }, { "name": "_links", "kind": "object" }],
    "outputFields": [{ "name": "total_items" }, { "name": "page_count" }],
    "omitted": "form settings and theme details",
  },
  "typeform__list_responses": {
    "collectionKeys": ["items", "responses"],
    "collectionName": "responses",
    "itemFields": [{ "name": "response_id" }, { "name": "token" }, { "name": "submitted_at" }, {
      "name": "landed_at",
    }, { "name": "answers", "kind": "object" }],
    "outputFields": [{ "name": "total_items" }, { "name": "page_count" }],
    "omitted": "hidden fields, calculated scores, and metadata blocks",
  },
};
