export const RESPONSIVE_IMAGE_WIDTH_XS = 320;
export const RESPONSIVE_IMAGE_WIDTH_SM = 640;
export const RESPONSIVE_IMAGE_WIDTH_MD = 1024;
export const RESPONSIVE_IMAGE_WIDTH_LG = 1920;
export const RESPONSIVE_IMAGE_WIDTHS = [
  RESPONSIVE_IMAGE_WIDTH_XS,
  RESPONSIVE_IMAGE_WIDTH_SM,
  RESPONSIVE_IMAGE_WIDTH_MD,
  RESPONSIVE_IMAGE_WIDTH_LG,
] as const;
