/****
 * Tool type definitions
 */

import type { z } from "zod";
import type { JsonSchema } from "./schema/json-schema.ts";
import type { BlobStorage } from "#veryfront/workflow/blob/types.ts";
// type-only import — no runtime circular dependency (tool ↔ mcp)
import type { ToolAnnotations } from "#veryfront/mcp/types.ts";

/**
 * Tool configuration options
 */
// deno-lint-ignore no-explicit-any -- generic erasure: interface must accept any concrete ToolConfig instantiation
export interface ToolConfig<TInput = any, TOutput = any> {
  /** Tool identifier (optional, inferred from filename) */
  id?: string;

  /** Tool description for the AI model */
  description: string;

  /** Input schema (Zod schema) */
  inputSchema: z.ZodSchema<TInput>;

  /**
   * Allow unknown/non-Zod schemas to fall back to a permissive JSON schema.
   * Use only for truly dynamic tools; prefer z.unknown() or z.any() instead.
   */
  allowUnknownSchema?: boolean;

  /**
   * Tool execution function
   */
  execute: (input: TInput, context?: ToolExecutionContext) => Promise<TOutput> | TOutput;

  /** MCP configuration */
  mcp?: {
    /** Expose via MCP */
    enabled?: boolean;

    /** Require authentication */
    requiresAuth?: boolean;

    /** Cache policy */
    cachePolicy?: "no-cache" | "cache" | "cache-first";

    /** Human-readable title for display */
    title?: string;
    /** Behavioral hints for clients (MCP 2025-11-25) */
    annotations?: ToolAnnotations;
  };
}

/**
 * Context passed to tool execution
 */
export interface ToolExecutionContext {
  /** ID of the agent calling the tool (if any) */
  agentId?: string;
  /** Stable ID for the current tool call when the runtime is tracking tool lifecycles */
  toolCallId?: string;
  /** Project identity used by integration token resolution */
  projectId?: string;
  /** End-user identity for per-user token resolution in integration tools */
  endUserId?: string;
  /** Abort signal for cooperative cancellation during long-running tool execution */
  abortSignal?: AbortSignal;
  /** Progress token for sending progress notifications (MCP 2025-11-25) */
  progressToken?: string | number;
  /**
   * Optional host-provided callback for publishing generic runtime data events.
   *
   * The payload intentionally stays framework-generic so hosts can surface
   * structured runtime signals without leaking product-specific event shapes
   * into the open-core contract.
   */
  publishDataEvent?: (event: ToolExecutionDataEvent) => void | Promise<void>;
  /** Additional context */
  [key: string]: unknown;
  /** Blob storage access (if configured in workflow) */
  blobStorage?: BlobStorage;
}

export interface ToolExecutionDataEvent {
  /** Host-defined event type */
  type: string;
  /** Optional structured event payload */
  data?: unknown;
  /** Additional host-defined fields */
  [key: string]: unknown;
}

/**
 * Tool type discriminator
 * - 'function': Standard tool with known input/output types (default)
 * - 'dynamic': Dynamic tool with unknown types (MCP tools, user-defined functions)
 */
type ToolType = "function" | "dynamic";

/**
 * Tool instance (returned by tool() function)
 */
// deno-lint-ignore no-explicit-any -- generic erasure: interface must accept any concrete Tool instantiation
export interface Tool<TInput = any, TOutput = any> {
  /** Tool ID */
  id: string;
  /** Internal marker used to distinguish autogenerated placeholder ids from explicit ids. */
  __veryfrontGeneratedId?: string;

  /**
   * Tool type discriminator
   * - 'function': Standard tool with known types (default)
   * - 'dynamic': Dynamic tool for MCP, user-defined functions, etc.
   */
  type: ToolType;

  /** Tool description */
  description: string;

  /** Input schema (Zod) */
  inputSchema: z.ZodSchema<TInput>;

  /**
   * Pre-converted JSON Schema (for OpenAI/provider compatibility)
   * This is generated at tool creation time to avoid bundling issues
   */
  inputSchemaJson?: JsonSchema;

  /**
   * Execute the tool
   */
  execute: (input: TInput, context?: ToolExecutionContext) => Promise<TOutput>;

  /** MCP configuration */
  mcp?: ToolConfig["mcp"];
}

/**
 * Runtime tool map keyed by the tool name exposed to an agent.
 *
 * Hosts can use this for already-materialized framework tools, including
 * tools loaded from remote sources.
 */
export type ToolSet = Record<string, Tool<unknown, unknown>>;

/**
 * Provider-facing tool definition used for model/tool registration.
 */
export interface ToolDefinition {
  name: string;
  description: string;
  parameters: JsonSchema;
  title?: string;
  annotations?: ToolAnnotations;
}

/**
 * Remote tool source loaded dynamically at runtime.
 * Hosts can provide these to expose tools from remote MCP-compatible systems
 * without registering those tools globally inside the framework.
 */
export interface RemoteToolSource {
  id: string;
  listTools(context?: ToolExecutionContext): Promise<ToolDefinition[]>;
  executeTool(
    toolName: string,
    args: Record<string, unknown>,
    context?: ToolExecutionContext,
  ): Promise<unknown>;
}
