import { assertEquals, assertStringIncludes } from "@veryfront/testing/assert";
import { describe, it } from "@veryfront/testing/bdd";
import { getAdapter } from "@veryfront/platform";
import { isDeno } from "@veryfront/platform/compat/runtime.ts";
import { VirtualModuleSystem } from "../../../src/rendering/virtual-module-system.ts";

describe(
  "VirtualModuleSystem Smoke Tests",
  {
    sanitizeOps: false,
    sanitizeResources: false,
  },
  () => {
    it("should register and serve modules", async () => {
      const adapter = await getAdapter();
      const vms = new VirtualModuleSystem("/_veryfront/modules", adapter);

      // Test component source
      const componentSource = `
import React from 'react';

export default function TestComponent() {
  return React.createElement('div', null, 'Hello from virtual module');
}
`;

      // Register the module
      const moduleUrl = await vms.registerModule(
        "test-component",
        componentSource,
        "/test/project",
      );

      assertEquals(moduleUrl, "/_veryfront/modules/test-component", "Module URL should be correct");

      // Create a mock request
      const request = new Request("http://localhost:3002/_veryfront/modules/test-component");

      // Handle the request
      const response = await vms.handleRequest(request);

      assertEquals(response?.status, 200, "Response should be successful");

      const content = await response?.text();
      // Deno uses npm: specifiers for React, other runtimes use esm.sh URLs
      if (isDeno) {
        assertStringIncludes(
          content ?? "",
          "npm:react@",
          "Module should have transformed React import to npm: specifier (Deno)",
        );
      } else {
        assertEquals(
          content?.includes("https://esm.sh/react@19.1.1") ||
            content?.includes("https://esm.sh/react@18."),
          true,
          "Module should have transformed React import to esm.sh URL",
        );
      }
    });

    it("should handle non-virtual requests", async () => {
      const adapter = await getAdapter();
      const vms = new VirtualModuleSystem("/_veryfront/modules", adapter);

      // Request for non-virtual module
      const request = new Request("http://localhost:3002/some/other/path");
      const response = await vms.handleRequest(request);

      assertEquals(response, null, "Should return null for non-virtual module requests");
    });

    it("should transform JSX runtime imports", async () => {
      const adapter = await getAdapter();
      const vms = new VirtualModuleSystem("/_veryfront/modules", adapter);

      // Component with JSX runtime import (as generated by esbuild)
      const jsxSource = `
import { jsx, jsxs } from "react/jsx-runtime";
import * as React from "react";

export default function Component() {
  return jsx("div", { children: "Hello" });
}
`;

      const moduleUrl = await vms.registerModule("jsx-component", jsxSource, "/test/project");

      const request = new Request(`http://localhost:3002${moduleUrl}`);
      const response = await vms.handleRequest(request);
      const content = await response?.text();

      // Deno: jsx-runtime is resolved to npm: specifier
      // Other runtimes: jsx-runtime is converted back to bare specifier (for browser import map)
      if (isDeno) {
        assertStringIncludes(
          content ?? "",
          "npm:react@",
          "JSX runtime import should use npm: specifier (Deno)",
        );
        assertStringIncludes(
          content ?? "",
          "jsx-runtime",
          "Should include jsx-runtime path",
        );
      } else {
        assertStringIncludes(
          content ?? "",
          'from "react/jsx-runtime"',
          "JSX runtime import should be bare specifier (resolved by browser import map)",
        );
      }
    });
  },
);
