import { assertEquals } from "@veryfront/testing/assert";
import { describe, it } from "@veryfront/testing/bdd";
import { getAdapter } from "@veryfront/platform";
import { VirtualModuleSystem } from "../../../src/rendering/virtual-module-system.ts";

describe(
  "VirtualModuleSystem Smoke Tests",
  {
    sanitizeOps: false,
    sanitizeResources: false,
  },
  () => {
    it("should register and serve modules", async () => {
      const adapter = await getAdapter();
      const vms = new VirtualModuleSystem("/_veryfront/modules", adapter);

      // Test component source
      const componentSource = `
import React from 'react';

export default function TestComponent() {
  return React.createElement('div', null, 'Hello from virtual module');
}
`;

      // Register the module
      const moduleUrl = await vms.registerModule(
        "test-component",
        componentSource,
        "/test/project",
      );

      assertEquals(moduleUrl, "/_veryfront/modules/test-component", "Module URL should be correct");

      // Create a mock request
      const request = new Request("http://localhost:3002/_veryfront/modules/test-component");

      // Handle the request
      const response = await vms.handleRequest(request);

      assertEquals(response?.status, 200, "Response should be successful");

      const content = await response?.text();
      // Test should check for default React version (19.1.1) not hardcoded 19.1.1
      // Default version is defined in src/shared/constants/cdn.ts as REACT_DEFAULT_VERSION
      assertEquals(
        content?.includes("https://esm.sh/react@19.1.1") ||
          content?.includes("https://esm.sh/react@18."),
        true,
        "Module should have transformed React import to default version (19.1.1)",
      );
    });

    it("should handle non-virtual requests", async () => {
      const adapter = await getAdapter();
      const vms = new VirtualModuleSystem("/_veryfront/modules", adapter);

      // Request for non-virtual module
      const request = new Request("http://localhost:3002/some/other/path");
      const response = await vms.handleRequest(request);

      assertEquals(response, null, "Should return null for non-virtual module requests");
    });

    it("should transform JSX runtime imports", async () => {
      const adapter = await getAdapter();
      const vms = new VirtualModuleSystem("/_veryfront/modules", adapter);

      // Component with JSX runtime import (as generated by esbuild)
      const jsxSource = `
import { jsx, jsxs } from "react/jsx-runtime";
import * as React from "react";

export default function Component() {
  return jsx("div", { children: "Hello" });
}
`;

      const moduleUrl = await vms.registerModule("jsx-component", jsxSource, "/test/project");

      const request = new Request(`http://localhost:3002${moduleUrl}`);
      const response = await vms.handleRequest(request);
      const content = await response?.text();

      assertEquals(
        content?.includes('from "react/jsx-runtime"'),
        true,
        "JSX runtime import should be transformed to ESM URL",
      );
    });
  },
);
