import { DEFAULT_MAX_BODY_SIZE_BYTES, DEFAULT_MAX_FILE_SIZE_BYTES, DEFAULT_MAX_HEADER_SIZE_BYTES, DEFAULT_MAX_URL_LENGTH_BYTES, } from "../../utils/constants/index.js";
export const DEFAULT_LIMITS = {
    maxBodySize: DEFAULT_MAX_BODY_SIZE_BYTES,
    maxUrlLength: DEFAULT_MAX_URL_LENGTH_BYTES,
    maxHeaderSize: DEFAULT_MAX_HEADER_SIZE_BYTES,
    maxFileSize: DEFAULT_MAX_FILE_SIZE_BYTES,
};
