export const libraries = [
  {
    category: 'UI',
    projectSlug: 'veryfront-ui',
    title: 'Veryfront UI',
    lead: 'React and Tailwind CSS UI Components',
    imageSrc: 'https://cdn.veryfront.com/5b74466b-ad05-4594-82f6-8ed08ad1c37c/icons/core-logo.svg',
    href: 'https://veryfront.com/libraries/veryfront-ui',
    description: 'Build pages fast with ready-made Tailwind CSS components.',
  },
  {
    category: "UI",
    projectSlug: "vibe-ui",
    title: "Vibe UI",
    lead: "React and Chakra UI Components",
    imageSrc: "https://cdn.veryfront.com/5b74466b-ad05-4594-82f6-8ed08ad1c37c/icons/vibe-logo.svg",
    href: "https://vibe-ui.veryfront.com",
    description: "Build app UIs quickly with pre-built Chakra UI components.",
  },
  {
    category: "UI",
    projectSlug: "chakra-ui",
    title: "Chakra UI",
    lead: "React and Chakra UI Components",
    imageSrc: "https://cdn.veryfront.com/5b74466b-ad05-4594-82f6-8ed08ad1c37c/icons/chakra-logo.svg",
    href: "https://chakra-ui.veryfront.com",
    description: "Craft modern, responsive interfaces using customizable React components.",
  },
  {
    category: "Utility",
    projectSlug: "core",
    title: "Core",
    lead: "Veryfront Core Components",
    imageSrc: "https://cdn.veryfront.com/5b74466b-ad05-4594-82f6-8ed08ad1c37c/icons/core-logo.svg",
    href: "https://core.veryfront.com",
    description: "Simplify web development with a diverse set of reusable utility components.",
  },
  {
    category: "UI",
    projectSlug: "keen-slider",
    title: "Keen Slider",
    lead: "React and Keen Slider UI Components",
    imageSrc: "https://cdn.veryfront.com/5b74466b-ad05-4594-82f6-8ed08ad1c37c/icons/keen-slider-logo.svg",
    href: "https://keen-slider.veryfront.com",
    description: "Craft captivating content sliders and carousels with ease and flexibility.",
  },
  {
    category: "Experimentation",
    projectSlug: "launchdarkly",
    title: "Launch Darkly",
    lead: "React and Launch Darkly Components",
    imageSrc: "https://cdn.veryfront.com/5b74466b-ad05-4594-82f6-8ed08ad1c37c/icons/launch-darkly-logo.svg",
    href: "https://launchdarkly.veryfront.com/",
    description: "Effortlessly manage feature flags and A/B testing in web applications.",
  },
  {
    category: "Utility",
    projectSlug: "react",
    title: "React",
    lead: "React Utility Components",
    imageSrc: "https://cdn.veryfront.com/5b74466b-ad05-4594-82f6-8ed08ad1c37c/icons/react-logo.svg",
    href: "https://react.veryfront.com",
    description: "Empower React apps with versatile utility components and streamlined tools.",
  },
  {
    category: "UI",
    projectSlug: "react-hook-form",
    title: "React Hook Form",
    lead: "React Hook Form Components",
    imageSrc: "https://cdn.veryfront.com/5b74466b-ad05-4594-82f6-8ed08ad1c37c/icons/react-hook-form-logo.svg",
    href: "https://react-hook-form.veryfront.com",
    description: "Effortlessly handle form state, validation, and submission in React.",
  },
  {
    category: "API",
    projectSlug: "react-query",
    title: "React Query",
    lead: "React Query Components",
    imageSrc: "https://cdn.veryfront.com/5b74466b-ad05-4594-82f6-8ed08ad1c37c/icons/react-query-logo.svg",
    href: "https://react-query.veryfront.com",
    description: "Optimize data fetching, caching, and state management in React.",
  },
  {
    category: "UI",
    projectSlug: "responsive-image",
    title: "Responsive Image",
    lead: "React Responsive Image UI Component",
    imageSrc: "https://cdn.veryfront.com/5b74466b-ad05-4594-82f6-8ed08ad1c37c/icons/responsive-image-logo.svg",
    href: "https://responsive-image.veryfront.com",
    description: "Deliver visually appealing, optimized images across different devices and screens.",
  },
  {
    category: "Analytics",
    projectSlug: "segment",
    title: "Segment",
    lead: "React Segment Components",
    imageSrc: "https://cdn.veryfront.com/5b74466b-ad05-4594-82f6-8ed08ad1c37c/icons/segment-logo.svg",
    href: "https://segment.veryfront.com",
    description: "Effortlessly integrate powerful analytics and gain insights into user behavior.",
  },
  {
    category: "UI",
    projectSlug: "shadcn-ui",
    title: "Shadcn UI",
    lead: "React, Radix UI and Tailwind CSS UI Components",
    imageSrc: "https://cdn.veryfront.com/5b74466b-ad05-4594-82f6-8ed08ad1c37c/icons/shadcn-logo.svg",
    href: "https://shadcn-ui.veryfront.com",
    description: "Create elegant and functional interfaces with Radix UI and Tailwind CSS.",
  },
  {
    category: "Content",
    projectSlug: "storyblok",
    title: "Storyblok",
    lead: "React Storyblok Components",
    imageSrc: "https://cdn.veryfront.com/5b74466b-ad05-4594-82f6-8ed08ad1c37c/icons/storyblok-logo.svg",
    href: "https://storyblok.veryfront.com",
    description: "Simplify content management and delivery with the Storyblok headless CMS.",
  },
];


export default async function ({ req }) {
  return libraries;
}
