export const agUiPositiveFixtures = [
  {
    type: "TEXT_MESSAGE_START",
    messageId: "msg-text",
    role: "assistant",
    metadata: { phase: null },
  },
  { type: "TEXT_MESSAGE_CONTENT", messageId: "msg-text", delta: "hello" },
  { type: "TEXT_MESSAGE_END", messageId: "msg-text" },
  {
    type: "TEXT_MESSAGE_CHUNK",
    messageId: "msg-chunk",
    role: "user",
    delta: "chunk",
    name: "person",
  },
  {
    type: "TOOL_CALL_START",
    toolCallId: "tool-1",
    toolCallName: "search",
    parentMessageId: "msg-text",
  },
  { type: "TOOL_CALL_ARGS", toolCallId: "tool-1", delta: '{"q"' },
  { type: "TOOL_CALL_END", toolCallId: "tool-1" },
  {
    type: "TOOL_CALL_CHUNK",
    toolCallId: "tool-2",
    toolCallName: "lookup",
    parentMessageId: "msg-text",
    delta: '{"id":"a"}',
  },
  {
    type: "TOOL_CALL_RESULT",
    messageId: "tool-msg-1",
    toolCallId: "tool-1",
    content: [
      { type: "text", text: "done" },
      { type: "image", source: { type: "file", value: "file-abc", provider: "provider-a" } },
    ],
    role: "tool",
  },
  { type: "STATE_SNAPSHOT", snapshot: ["any-json-state", 1, true] },
  { type: "STATE_DELTA", delta: [{ op: "add", path: "", value: { ready: true } }] },
  {
    type: "MESSAGES_SNAPSHOT",
    messages: [
      { id: "dev-1", role: "developer", content: "rules" },
      { id: "sys-1", role: "system", content: "system" },
      {
        id: "asst-1",
        role: "assistant",
        content: "answer",
        toolCalls: [
          {
            id: "tool-1",
            type: "function",
            function: { name: "search", arguments: '{"q":"x"}' },
          },
        ],
      },
      { id: "user-1", role: "user", content: [{ type: "text", text: "question" }] },
      { id: "tool-msg-1", role: "tool", content: "result", toolCallId: "tool-1" },
      { id: "activity-1", role: "activity", activityType: "plan", content: { step: 1 } },
      { id: "reason-1", role: "reasoning", content: "thinking", encryptedValue: "ciphertext" },
    ],
  },
  {
    type: "ACTIVITY_SNAPSHOT",
    messageId: "activity-1",
    activityType: "plan",
    content: { items: ["a"] },
    replace: true,
  },
  {
    type: "ACTIVITY_DELTA",
    messageId: "activity-1",
    activityType: "plan",
    patch: [{ op: "replace", path: "/items/0", value: "b" }],
  },
  { type: "RAW", event: { provider: "native", payload: [1] }, source: "provider" },
  { type: "CUSTOM", name: "app.signal", value: { ok: true } },
  {
    type: "RUN_STARTED",
    threadId: "thread-1",
    runId: "run-1",
    protocolVersion: "1.0",
    parentRunId: "run-0",
    input: {
      threadId: "thread-1",
      runId: "run-1",
      protocolVersion: "1.0",
      messages: [{ id: "user-1", role: "user", content: "hi" }],
      tools: [{ name: "search", description: "Search", parameters: { type: "object" } }],
      context: [{ description: "tenant", value: "test" }],
      resume: [{ interruptId: "interrupt-1", status: "resolved", payload: { approved: true } }],
    },
  },
  {
    type: "RUN_FINISHED",
    threadId: "thread-1",
    runId: "run-1",
    result: { answer: "ok" },
    outcome: { type: "success", pendingToolCallIds: ["tool-3"] },
    usage: [{
      provider: "openai",
      model: "model",
      inputTokens: 1,
      outputTokens: 2,
      totalTokens: 3,
    }],
  },
  {
    type: "RUN_FINISHED",
    threadId: "thread-1",
    runId: "run-2",
    outcome: {
      type: "interrupt",
      interrupts: [
        {
          id: "interrupt-1",
          reason: "approval",
          message: "Approve?",
          responseSchema: { type: "object" },
        },
      ],
    },
  },
  { type: "RUN_FINISHED", threadId: "thread-1", runId: "run-3", outcome: { type: "cancelled" } },
  { type: "RUN_ERROR", message: "failed", code: "ERR", usage: [{ totalTokens: 1 }] },
  { type: "STEP_STARTED", stepName: "plan", subagentRunId: "sub-1" },
  { type: "STEP_FINISHED", stepName: "plan", subagentRunId: "sub-1" },
  { type: "REASONING_START", messageId: "reason-context-1", subagentRunId: "sub-1" },
  { type: "REASONING_MESSAGE_START", messageId: "reason-msg-1", role: "reasoning" },
  { type: "REASONING_MESSAGE_CONTENT", messageId: "reason-msg-1", delta: "thought" },
  { type: "REASONING_MESSAGE_END", messageId: "reason-msg-1" },
  { type: "REASONING_MESSAGE_CHUNK", messageId: "reason-msg-2", delta: "compact thought" },
  { type: "REASONING_END", messageId: "reason-context-1" },
  {
    type: "REASONING_ENCRYPTED_VALUE",
    subtype: "message",
    entityId: "reason-msg-1",
    encryptedValue: "opaque",
  },
  {
    type: "SUBAGENT_STARTED",
    subagentRunId: "sub-1",
    name: "researcher",
    description: "Find facts",
    parentToolCallId: "tool-1",
    parentMessageId: "msg-text",
  },
  {
    type: "SUBAGENT_FINISHED",
    subagentRunId: "sub-1",
    result: { ok: true },
    outcome: { type: "suspended", interruptIds: ["interrupt-1"] },
  },
  { type: "SUBAGENT_ERROR", subagentRunId: "sub-2", message: "child failed", code: "CHILD" },
];

export const agUiNegativeFixtures = [
  { id: "unknown-event", event: { type: "META_EVENT", message: "nope" } },
  { id: "metadata-null", event: { type: "TEXT_MESSAGE_START", messageId: "msg", metadata: null } },
  { id: "raw-event-null", event: { type: "TEXT_MESSAGE_START", messageId: "msg", rawEvent: null } },
  { id: "missing-required-message-id", event: { type: "TEXT_MESSAGE_CONTENT", delta: "x" } },
  {
    id: "state-delta-invalid-pointer",
    event: { type: "STATE_DELTA", delta: [{ op: "add", path: "bad", value: 1 }] },
  },
  {
    id: "activity-content-array",
    event: { type: "ACTIVITY_SNAPSHOT", messageId: "a", activityType: "plan", content: [] },
  },
  {
    id: "run-finished-empty-interrupts",
    event: {
      type: "RUN_FINISHED",
      threadId: "t",
      runId: "r",
      outcome: { type: "interrupt", interrupts: [] },
    },
  },
  {
    id: "reasoning-message-start-role",
    event: { type: "REASONING_MESSAGE_START", messageId: "r", role: "assistant" },
  },
  { id: "subagent-start-missing-name", event: { type: "SUBAGENT_STARTED", subagentRunId: "sub" } },
];
