import type { JSX } from "react";

export interface Integration {
  id: string;
  name: string;
  icon: string;
  connected: boolean;
  connectUrl: string;
}

export interface SetupStep {
  id: string;
  title: string;
  description: string;
  completed: boolean;
  action?: () => void;
  link?: string;
}

interface SetupGuide {
  title: string;
  steps: string[];
  link: string;
  envVars: string[];
  category: string;
}

export interface TokenStorageStatus {
  mode: "memory" | "database" | "kv" | "redis" | "custom";
  encrypted: boolean;
  autoGenerated?: boolean;
}

export type TokenStorageStyles = {
  container: string;
  iconWrapper: string;
  title: string;
  text: string;
  isMemory: boolean;
};

export const CATEGORIES = [
  { id: "google", name: "Google Services", icon: "google" },
  { id: "microsoft", name: "Microsoft Services", icon: "microsoft" },
  { id: "atlassian", name: "Atlassian", icon: "atlassian" },
  { id: "communication", name: "Communication", icon: "chat" },
  { id: "development", name: "Development", icon: "code" },
  { id: "productivity", name: "Productivity", icon: "tasks" },
  { id: "storage", name: "Storage", icon: "folder" },
  { id: "design", name: "Design", icon: "palette" },
] as const;

export const OAUTH_SETUP_GUIDES: Record<string, SetupGuide> = {
  gmail: {
    title: "Google OAuth Setup (Gmail)",
    category: "google",
    steps: [
      "Go to Google Cloud Console",
      "Enable Gmail API",
      "Create OAuth 2.0 credentials",
      "Add redirect URI: http://localhost:3000/api/auth/gmail/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://console.cloud.google.com/apis/credentials",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  calendar: {
    title: "Google Calendar Setup",
    category: "google",
    steps: ["Enable Calendar API", "Add redirect URI: http://localhost:3000/api/auth/calendar/callback"],
    link: "https://console.cloud.google.com/apis/library/calendar-json.googleapis.com",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  drive: {
    title: "Google Drive Setup",
    category: "google",
    steps: ["Enable Drive API", "Add redirect URI: http://localhost:3000/api/auth/drive/callback"],
    link: "https://console.cloud.google.com/apis/library/drive.googleapis.com",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  sheets: {
    title: "Google Sheets Setup",
    category: "google",
    steps: ["Enable Sheets API", "Add redirect URI: http://localhost:3000/api/auth/sheets/callback"],
    link: "https://console.cloud.google.com/apis/library/sheets.googleapis.com",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  "docs-google": {
    title: "Google Docs Setup",
    category: "google",
    steps: ["Enable Docs API", "Add redirect URI: http://localhost:3000/api/auth/docs-google/callback"],
    link: "https://console.cloud.google.com/apis/library/docs.googleapis.com",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  outlook: {
    title: "Microsoft Outlook Setup",
    category: "microsoft",
    steps: ["Create Azure app registration", "Add redirect URI: http://localhost:3000/api/auth/outlook/callback", "Add Microsoft Graph Mail permissions"],
    link: "https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade",
    envVars: ["MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET"],
  },
  teams: {
    title: "Microsoft Teams Setup",
    category: "microsoft",
    steps: ["Use the same Azure app registration", "Add redirect URI: http://localhost:3000/api/auth/teams/callback", "Add Microsoft Graph Teams permissions"],
    link: "https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade",
    envVars: ["MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET"],
  },
  sharepoint: {
    title: "SharePoint Setup",
    category: "microsoft",
    steps: ["Use the same Azure app registration", "Add redirect URI: http://localhost:3000/api/auth/sharepoint/callback", "Add Microsoft Graph Sites permissions"],
    link: "https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade",
    envVars: ["MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET"],
  },
  onedrive: {
    title: "OneDrive Setup",
    category: "microsoft",
    steps: ["Use the same Azure app registration", "Add redirect URI: http://localhost:3000/api/auth/onedrive/callback", "Add Microsoft Graph Files permissions"],
    link: "https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade",
    envVars: ["MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET"],
  },
  jira: {
    title: "Jira OAuth Setup",
    category: "atlassian",
    steps: ["Create Atlassian OAuth 2.0 integration", "Add redirect URI: http://localhost:3000/api/auth/jira/callback", "Add Jira scopes"],
    link: "https://developer.atlassian.com/console/myapps/",
    envVars: ["ATLASSIAN_CLIENT_ID", "ATLASSIAN_CLIENT_SECRET", "ATLASSIAN_CLOUD_ID"],
  },
  confluence: {
    title: "Confluence OAuth Setup",
    category: "atlassian",
    steps: ["Create Atlassian OAuth 2.0 integration", "Add redirect URI: http://localhost:3000/api/auth/confluence/callback", "Add Confluence scopes"],
    link: "https://developer.atlassian.com/console/myapps/",
    envVars: ["ATLASSIAN_CLIENT_ID", "ATLASSIAN_CLIENT_SECRET", "ATLASSIAN_CLOUD_ID"],
  },
  slack: {
    title: "Slack App Setup",
    category: "communication",
    steps: [
      "Go to Slack API Apps",
      "Create a new app",
      "Add redirect URL: http://localhost:3000/api/auth/slack/callback",
      "Add scopes: channels:history, channels:read, chat:write, groups:history, groups:read, im:history, im:read, mpim:history, mpim:read, users:read",
      "Install to Workspace",
    ],
    link: "https://api.slack.com/apps",
    envVars: ["SLACK_CLIENT_ID", "SLACK_CLIENT_SECRET"],
  },
  github: {
    title: "GitHub OAuth App Setup",
    category: "development",
    steps: ["Go to GitHub Developer Settings", "Create an OAuth app", "Add callback URL: http://localhost:3000/api/auth/github/callback"],
    link: "https://github.com/settings/developers",
    envVars: ["GITHUB_CLIENT_ID", "GITHUB_CLIENT_SECRET"],
  },
  gitlab: {
    title: "GitLab OAuth Setup",
    category: "development",
    steps: ["Go to GitLab Preferences > Applications", "Create an OAuth application", "Add callback URL: http://localhost:3000/api/auth/gitlab/callback"],
    link: "https://gitlab.com/-/profile/applications",
    envVars: ["GITLAB_CLIENT_ID", "GITLAB_CLIENT_SECRET"],
  },
  asana: {
    title: "Asana OAuth Setup",
    category: "productivity",
    steps: ["Go to Asana Developer Console", "Create an app", "Add callback URL: http://localhost:3000/api/auth/asana/callback"],
    link: "https://app.asana.com/0/developer-console",
    envVars: ["ASANA_CLIENT_ID", "ASANA_CLIENT_SECRET"],
  },
  linear: {
    title: "Linear OAuth Setup",
    category: "productivity",
    steps: ["Go to Linear Settings > API", "Create OAuth application", "Add callback URL: http://localhost:3000/api/auth/linear/callback"],
    link: "https://linear.app/settings/api",
    envVars: ["LINEAR_CLIENT_ID", "LINEAR_CLIENT_SECRET"],
  },
  notion: {
    title: "Notion OAuth Setup",
    category: "productivity",
    steps: ["Go to Notion Integrations", "Create public OAuth integration", "Add callback URL: http://localhost:3000/api/auth/notion/callback"],
    link: "https://www.notion.so/my-integrations",
    envVars: ["NOTION_CLIENT_ID", "NOTION_CLIENT_SECRET"],
  },
  airtable: {
    title: "Airtable OAuth Setup",
    category: "storage",
    steps: ["Go to Airtable Developer Hub", "Create an OAuth integration", "Add callback URL: http://localhost:3000/api/auth/airtable/callback"],
    link: "https://airtable.com/developers/web",
    envVars: ["AIRTABLE_CLIENT_ID", "AIRTABLE_CLIENT_SECRET"],
  },
  figma: {
    title: "Figma OAuth Setup",
    category: "design",
    steps: ["Go to Figma Developer Settings", "Create an OAuth app", "Add redirect URI: http://localhost:3000/api/auth/figma/callback", "Request the file_read scope"],
    link: "https://www.figma.com/developers/apps",
    envVars: ["FIGMA_CLIENT_ID", "FIGMA_CLIENT_SECRET"],
  },
};

export function filterIntegrations(
  integrations: Integration[],
  searchQuery: string,
  selectedCategory: string | null,
): Integration[] {
  const query = searchQuery.toLowerCase();

  return integrations.filter((integration) => {
    const guide = OAUTH_SETUP_GUIDES[integration.id];

    const matchesSearch =
      query === "" ||
      integration.name.toLowerCase().includes(query) ||
      integration.id.toLowerCase().includes(query);

    const matchesCategory = selectedCategory === null || guide?.category === selectedCategory;

    return matchesSearch && matchesCategory;
  });
}

export function groupIntegrationsByCategory(
  integrations: Integration[],
): Record<string, Integration[]> {
  const groups: Record<string, Integration[]> = {};

  for (const integration of integrations) {
    const category = OAUTH_SETUP_GUIDES[integration.id]?.category ?? "other";
    (groups[category] ??= []).push(integration);
  }

  return groups;
}

export function buildSetupSteps(
  envChecked: boolean,
  allConnected: boolean,
  markEnvChecked: () => void,
): SetupStep[] {
  return [
    {
      id: "env",
      title: "Configure Environment Variables",
      description: "Add your OAuth credentials to the .env file",
      completed: envChecked,
      action: markEnvChecked,
    },
    {
      id: "oauth",
      title: "Create OAuth Apps",
      description: "Set up OAuth applications for each service",
      completed: false,
    },
    {
      id: "connect",
      title: "Connect Services",
      description: "Authorize your app to access each service",
      completed: allConnected,
    },
  ];
}

export function getTokenStorageStyles(
  tokenStorage: TokenStorageStatus | null,
): TokenStorageStyles | null {
  if (!tokenStorage) return null;

  const isMemory = tokenStorage.mode === "memory";

  return {
    container: `rounded-2xl p-6 shadow-sm border mb-8 ${
      isMemory
        ? "bg-amber-50 dark:bg-amber-900/20 border-amber-200 dark:border-amber-800"
        : "bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800"
    }`,
    iconWrapper: `w-10 h-10 rounded-full flex items-center justify-center ${
      isMemory ? "bg-amber-100 dark:bg-amber-900" : "bg-green-100 dark:bg-green-900"
    }`,
    title: `font-semibold ${
      isMemory ? "text-amber-800 dark:text-amber-200" : "text-green-800 dark:text-green-200"
    }`,
    text: `text-sm mt-1 ${
      isMemory ? "text-amber-700 dark:text-amber-300" : "text-green-700 dark:text-green-300"
    }`,
    isMemory,
  };
}

export function ServiceIcon({ name }: { name: string }): JSX.Element {
  const iconMap: Record<string, JSX.Element> = {
    mail: (
      <svg className="w-6 h-6 text-red-500" fill="currentColor" viewBox="0 0 24 24">
        <path
          d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
          stroke="currentColor"
          strokeWidth="2"
          fill="none"
        />
      </svg>
    ),
    slack: (
      <svg className="w-6 h-6" viewBox="0 0 24 24" fill="none">
        <path
          d="M5.042 15.165a2.528 2.528 0 0 1-2.52 2.523A2.528 2.528 0 0 1 0 15.165a2.527 2.527 0 0 1 2.522-2.52h2.52v2.52zM6.313 15.165a2.527 2.527 0 0 1 2.521-2.52 2.527 2.527 0 0 1 2.521 2.52v6.313A2.528 2.528 0 0 1 8.834 24a2.528 2.528 0 0 1-2.521-2.522v-6.313z"
          fill="#E01E5A"
        />
        <path
          d="M8.834 5.042a2.528 2.528 0 0 1-2.521-2.52A2.528 2.528 0 0 1 8.834 0a2.528 2.528 0 0 1 2.521 2.522v2.52H8.834zM8.834 6.313a2.528 2.528 0 0 1 2.521 2.521 2.528 2.528 0 0 1-2.521 2.521H2.522A2.528 2.528 0 0 1 0 8.834a2.528 2.528 0 0 1 2.522-2.521h6.312z"
          fill="#36C5F0"
        />
        <path
          d="M18.956 8.834a2.528 2.528 0 0 1 2.522-2.521A2.528 2.528 0 0 1 24 8.834a2.528 2.528 0 0 1-2.522 2.521h-2.522V8.834zM17.688 8.834a2.528 2.528 0 0 1-2.523 2.521 2.527 2.527 0 0 1-2.52-2.521V2.522A2.527 2.527 0 0 1 15.165 0a2.528 2.528 0 0 1 2.523 2.522v6.312z"
          fill="#2EB67D"
        />
        <path
          d="M15.165 18.956a2.528 2.528 0 0 1 2.523 2.522A2.528 2.528 0 0 1 15.165 24a2.527 2.527 0 0 1-2.52-2.522v-2.522h2.52zM15.165 17.688a2.527 2.527 0 0 1-2.52-2.523 2.526 2.526 0 0 1 2.52-2.52h6.313A2.527 2.527 0 0 1 24 15.165a2.528 2.528 0 0 1-2.522 2.523h-6.313z"
          fill="#ECB22E"
        />
      </svg>
    ),
    calendar: (
      <svg
        className="w-6 h-6 text-blue-500"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
        />
      </svg>
    ),
    github: (
      <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
        <path
          fillRule="evenodd"
          d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
          clipRule="evenodd"
        />
      </svg>
    ),
    jira: (
      <svg className="w-6 h-6" viewBox="0 0 24 24">
        <defs>
          <linearGradient id="jira-gradient" x1="98.031%" x2="58.888%" y1=".161%" y2="40.766%">
            <stop offset="0%" stopColor="#0052CC" />
            <stop offset="100%" stopColor="#2684FF" />
          </linearGradient>
        </defs>
        <path
          fill="url(#jira-gradient)"
          d="M11.571 11.513H0a5.218 5.218 0 005.232 5.215h2.13v2.057A5.215 5.215 0 0012.575 24V12.518a1.005 1.005 0 00-1.005-1.005z"
        />
        <path
          fill="#2684FF"
          d="M17.151 5.97H5.58a5.215 5.215 0 005.215 5.214h2.129v2.058a5.218 5.218 0 005.232 5.215V6.975a1.005 1.005 0 00-1.005-1.005z"
        />
        <path
          fill="#2684FF"
          d="M22.723.426H11.152a5.215 5.215 0 005.215 5.215h2.129v2.057a5.218 5.218 0 005.232 5.215V1.431a1.005 1.005 0 00-1.005-1.005z"
        />
      </svg>
    ),
    notion: (
      <svg className="w-6 h-6" viewBox="0 0 24 24" fill="currentColor">
        <path d="M4.459 4.208c.746.606 1.026.56 2.428.466l13.215-.793c.28 0 .047-.28-.046-.326L17.86 1.968c-.42-.326-.98-.7-2.055-.607L3.01 2.295c-.466.046-.56.28-.374.466l1.823 1.447zm.793 3.08v13.904c0 .747.373 1.027 1.214.98l14.523-.84c.84-.046.933-.56.933-1.167V6.354c0-.606-.233-.933-.746-.886l-15.177.887c-.56.046-.747.326-.747.933zm14.337.745c.093.42 0 .84-.42.888l-.7.14v10.264c-.608.327-1.168.514-1.635.514-.746 0-.933-.234-1.495-.933l-4.577-7.186v6.952L12.21 19s0 .84-1.168.84l-3.222.186c-.093-.186 0-.653.327-.746l.84-.233V9.854L7.822 9.76c-.094-.42.14-1.026.793-1.073l3.456-.233 4.764 7.279v-6.44l-1.215-.14c-.093-.514.28-.886.747-.933l3.222-.186zM1.936 1.035l13.31-.98c1.634-.14 2.055-.047 3.082.7l4.249 2.986c.7.513.933.653.933 1.213v16.378c0 1.026-.373 1.634-1.68 1.726l-15.458.934c-.98.047-1.448-.093-1.962-.747l-3.129-4.06c-.56-.747-.793-1.306-.793-1.96V2.667c0-.839.374-1.54 1.448-1.632z" />
      </svg>
    ),
    default: (
      <svg
        className="w-6 h-6 text-neutral-400"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M13 10V3L4 14h7v7l9-11h-7z"
        />
      </svg>
    ),
  };

  return iconMap[name] ?? iconMap.default;
}
