import type { JSX } from "react";

export interface Integration {
  id: string;
  name: string;
  icon: string;
  connected: boolean;
  connectUrl: string;
}

export interface SetupStep {
  id: string;
  title: string;
  description: string;
  completed: boolean;
  action?: () => void;
  link?: string;
}

interface SetupGuide {
  title: string;
  steps: string[];
  link: string;
  envVars: string[];
  category: string;
}

export interface TokenStorageStatus {
  mode: "memory" | "database" | "kv" | "redis" | "custom";
  encrypted: boolean;
  autoGenerated?: boolean;
}

export type TokenStorageStyles = {
  container: string;
  iconWrapper: string;
  title: string;
  text: string;
  isMemory: boolean;
};

export const CATEGORIES = [
  { id: "google", name: "Google Services", icon: "google" },
  { id: "microsoft", name: "Microsoft Services", icon: "microsoft" },
  { id: "atlassian", name: "Atlassian", icon: "atlassian" },
  { id: "communication", name: "Communication", icon: "chat" },
  { id: "development", name: "Development", icon: "code" },
  { id: "productivity", name: "Productivity", icon: "tasks" },
  { id: "storage", name: "Storage", icon: "folder" },
  { id: "infrastructure", name: "Infrastructure", icon: "server" },
  { id: "sales", name: "Sales & CRM", icon: "users" },
  { id: "support", name: "Support", icon: "headset" },
  { id: "finance", name: "Finance", icon: "dollar" },
  { id: "marketing", name: "Marketing", icon: "megaphone" },
  { id: "design", name: "Design", icon: "palette" },
  { id: "ai", name: "AI Providers", icon: "brain" },
] as const;

export const OAUTH_SETUP_GUIDES: Record<string, SetupGuide> = {
  gmail: {
    title: "Google OAuth Setup (Gmail)",
    category: "google",
    steps: [
      "Go to Google Cloud Console",
      "Create a new project or select existing one",
      "Enable Gmail API in APIs & Services > Library",
      "Go to APIs & Services > Credentials",
      "Create OAuth 2.0 credentials (Web application)",
      "Add redirect URI: http://localhost:3000/api/auth/gmail/callback",
      "Copy Client ID and Secret to your .env file",
    ],
    link: "https://console.cloud.google.com/apis/credentials",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  calendar: {
    title: "Google Calendar Setup",
    category: "google",
    steps: [
      "Uses same Google OAuth credentials as Gmail",
      "Enable Calendar API in Google Cloud Console",
      "Add redirect URI: http://localhost:3000/api/auth/calendar/callback",
    ],
    link: "https://console.cloud.google.com/apis/library/calendar-json.googleapis.com",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  drive: {
    title: "Google Drive Setup",
    category: "google",
    steps: [
      "Uses same Google OAuth credentials",
      "Enable Drive API in Google Cloud Console",
      "Add redirect URI: http://localhost:3000/api/auth/drive/callback",
    ],
    link: "https://console.cloud.google.com/apis/library/drive.googleapis.com",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  sheets: {
    title: "Google Sheets Setup",
    category: "google",
    steps: [
      "Uses same Google OAuth credentials",
      "Enable Sheets API in Google Cloud Console",
      "Add redirect URI: http://localhost:3000/api/auth/sheets/callback",
    ],
    link: "https://console.cloud.google.com/apis/library/sheets.googleapis.com",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  "docs-google": {
    title: "Google Docs Setup",
    category: "google",
    steps: [
      "Uses same Google OAuth credentials",
      "Enable Docs API in Google Cloud Console",
      "Add redirect URI: http://localhost:3000/api/auth/docs-google/callback",
    ],
    link: "https://console.cloud.google.com/apis/library/docs.googleapis.com",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  outlook: {
    title: "Microsoft Outlook Setup",
    category: "microsoft",
    steps: [
      "Go to Azure Portal > Azure Active Directory",
      "Click App registrations > New registration",
      "Set redirect URI: http://localhost:3000/api/auth/outlook/callback",
      "Go to API permissions > Add Microsoft Graph permissions",
      "Add: Mail.Read, Mail.Send, Mail.ReadWrite",
      "Go to Certificates & secrets > New client secret",
      "Copy Application ID and Secret to .env",
    ],
    link: "https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade",
    envVars: ["MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET"],
  },
  teams: {
    title: "Microsoft Teams Setup",
    category: "microsoft",
    steps: [
      "Uses same Microsoft OAuth credentials as Outlook",
      "Add Teams permissions: Chat.Read, Chat.ReadWrite, Channel.ReadBasic.All",
      "Add redirect URI: http://localhost:3000/api/auth/teams/callback",
    ],
    link: "https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade",
    envVars: ["MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET"],
  },
  onedrive: {
    title: "Microsoft OneDrive Setup",
    category: "microsoft",
    steps: [
      "Uses same Microsoft OAuth credentials",
      "Add permissions: Files.Read, Files.ReadWrite",
      "Add redirect URI: http://localhost:3000/api/auth/onedrive/callback",
    ],
    link: "https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade",
    envVars: ["MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET"],
  },
  sharepoint: {
    title: "Microsoft SharePoint Setup",
    category: "microsoft",
    steps: [
      "Uses same Microsoft OAuth credentials",
      "Add permissions: Sites.Read.All, Sites.ReadWrite.All",
      "Add redirect URI: http://localhost:3000/api/auth/sharepoint/callback",
    ],
    link: "https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade",
    envVars: ["MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET"],
  },
  jira: {
    title: "Atlassian Jira Setup",
    category: "atlassian",
    steps: [
      "Go to Atlassian Developer Console",
      "Click Create > OAuth 2.0 integration",
      "Add Jira API scopes: read:jira-work, write:jira-work",
      "Set callback URL: http://localhost:3000/api/auth/jira/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://developer.atlassian.com/console/myapps/",
    envVars: ["ATLASSIAN_CLIENT_ID", "ATLASSIAN_CLIENT_SECRET"],
  },
  confluence: {
    title: "Atlassian Confluence Setup",
    category: "atlassian",
    steps: [
      "Uses same Atlassian OAuth credentials as Jira",
      "Add Confluence scopes: read:confluence-content.all, write:confluence-content",
      "Add callback URL: http://localhost:3000/api/auth/confluence/callback",
    ],
    link: "https://developer.atlassian.com/console/myapps/",
    envVars: ["ATLASSIAN_CLIENT_ID", "ATLASSIAN_CLIENT_SECRET"],
  },
  bitbucket: {
    title: "Atlassian Bitbucket Setup",
    category: "atlassian",
    steps: [
      "Go to Bitbucket Settings > OAuth consumers",
      "Click Add consumer",
      "Set callback URL: http://localhost:3000/api/auth/bitbucket/callback",
      "Add permissions: repository:read, repository:write",
      "Copy Key and Secret to .env",
    ],
    link: "https://bitbucket.org/account/settings/app-passwords/",
    envVars: ["BITBUCKET_CLIENT_ID", "BITBUCKET_CLIENT_SECRET"],
  },
  slack: {
    title: "Slack App Setup",
    category: "communication",
    steps: [
      "Go to Slack API Apps page",
      "Click Create New App > From scratch",
      "Go to OAuth & Permissions",
      "Add scopes: channels:history, channels:read, chat:write, groups:history, groups:read, im:history, im:read, mpim:history, mpim:read, users:read",
      "Add redirect URL: http://localhost:3000/api/auth/slack/callback",
      "Install to Workspace",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://api.slack.com/apps",
    envVars: ["SLACK_CLIENT_ID", "SLACK_CLIENT_SECRET"],
  },
  zoom: {
    title: "Zoom App Setup",
    category: "communication",
    steps: [
      "Go to Zoom App Marketplace",
      "Click Develop > Build App",
      "Choose OAuth app type",
      "Add redirect URL: http://localhost:3000/api/auth/zoom/callback",
      "Add scopes: meeting:read, meeting:write, user:read",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://marketplace.zoom.us/develop/create",
    envVars: ["ZOOM_CLIENT_ID", "ZOOM_CLIENT_SECRET"],
  },
  webex: {
    title: "Webex Integration Setup",
    category: "communication",
    steps: [
      "Go to Webex Developer Portal",
      "Create a new integration",
      "Add redirect URI: http://localhost:3000/api/auth/webex/callback",
      "Select required scopes",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://developer.webex.com/my-apps",
    envVars: ["WEBEX_CLIENT_ID", "WEBEX_CLIENT_SECRET"],
  },
  twilio: {
    title: "Twilio Setup",
    category: "communication",
    steps: [
      "Go to Twilio Console",
      "Copy Account SID and Auth Token",
      "Get a phone number for SMS",
      "Add credentials to .env",
    ],
    link: "https://console.twilio.com/",
    envVars: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "TWILIO_PHONE_NUMBER"],
  },
  github: {
    title: "GitHub OAuth App Setup",
    category: "development",
    steps: [
      "Go to GitHub Developer Settings",
      "Click OAuth Apps > New OAuth App",
      "Set Homepage URL: http://localhost:3000",
      "Set callback URL: http://localhost:3000/api/auth/github/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://github.com/settings/developers",
    envVars: ["GITHUB_CLIENT_ID", "GITHUB_CLIENT_SECRET"],
  },
  gitlab: {
    title: "GitLab OAuth Setup",
    category: "development",
    steps: [
      "Go to GitLab User Settings > Applications",
      "Create new application",
      "Add redirect URI: http://localhost:3000/api/auth/gitlab/callback",
      "Select scopes: api, read_user, read_repository",
      "Copy Application ID and Secret to .env",
    ],
    link: "https://gitlab.com/-/profile/applications",
    envVars: ["GITLAB_CLIENT_ID", "GITLAB_CLIENT_SECRET"],
  },
  sentry: {
    title: "Sentry Setup",
    category: "development",
    steps: [
      "Go to Sentry Settings > Developer Settings",
      "Create new integration",
      "Add redirect URL: http://localhost:3000/api/auth/sentry/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://sentry.io/settings/developer-settings/",
    envVars: ["SENTRY_CLIENT_ID", "SENTRY_CLIENT_SECRET"],
  },
  posthog: {
    title: "PostHog Setup",
    category: "development",
    steps: ["Go to PostHog Project Settings", "Copy your Project API Key", "Add to .env file"],
    link: "https://app.posthog.com/project/settings",
    envVars: ["POSTHOG_API_KEY", "POSTHOG_HOST"],
  },
  mixpanel: {
    title: "Mixpanel Setup",
    category: "development",
    steps: [
      "Go to Mixpanel Project Settings",
      "Copy your Project Token",
      "For API access, create a Service Account",
      "Add credentials to .env",
    ],
    link: "https://mixpanel.com/settings/project",
    envVars: ["MIXPANEL_TOKEN", "MIXPANEL_API_SECRET"],
  },
  notion: {
    title: "Notion Integration Setup",
    category: "productivity",
    steps: [
      "Go to Notion Integrations page",
      "Click New integration",
      "Name your integration and select workspace",
      "Copy the Internal Integration Token",
      "Share desired pages/databases with your integration",
      "Add token to .env",
    ],
    link: "https://www.notion.so/my-integrations",
    envVars: ["NOTION_API_KEY"],
  },
  linear: {
    title: "Linear OAuth Setup",
    category: "productivity",
    steps: [
      "Go to Linear Settings > API",
      "Create new OAuth application",
      "Add redirect URI: http://localhost:3000/api/auth/linear/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://linear.app/settings/api",
    envVars: ["LINEAR_CLIENT_ID", "LINEAR_CLIENT_SECRET"],
  },
  asana: {
    title: "Asana OAuth Setup",
    category: "productivity",
    steps: [
      "Go to Asana Developer Console",
      "Create new app",
      "Add redirect URI: http://localhost:3000/api/auth/asana/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://app.asana.com/0/developer-console",
    envVars: ["ASANA_CLIENT_ID", "ASANA_CLIENT_SECRET"],
  },
  trello: {
    title: "Trello Power-Up Setup",
    category: "productivity",
    steps: [
      "Go to Trello Power-Ups Admin",
      "Create new Power-Up",
      "Add redirect URI: http://localhost:3000/api/auth/trello/callback",
      "Copy API Key and Secret to .env",
    ],
    link: "https://trello.com/power-ups/admin",
    envVars: ["TRELLO_API_KEY", "TRELLO_API_SECRET"],
  },
  monday: {
    title: "Monday.com App Setup",
    category: "productivity",
    steps: [
      "Go to monday.com Developers",
      "Create new app",
      "Add OAuth redirect: http://localhost:3000/api/auth/monday/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://monday.com/developers/apps",
    envVars: ["MONDAY_CLIENT_ID", "MONDAY_CLIENT_SECRET"],
  },
  clickup: {
    title: "ClickUp OAuth Setup",
    category: "productivity",
    steps: [
      "Go to ClickUp Settings > Apps",
      "Create new app",
      "Add redirect URI: http://localhost:3000/api/auth/clickup/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://app.clickup.com/settings/apps",
    envVars: ["CLICKUP_CLIENT_ID", "CLICKUP_CLIENT_SECRET"],
  },
  box: {
    title: "Box App Setup",
    category: "storage",
    steps: [
      "Go to Box Developer Console",
      "Create new app with OAuth 2.0",
      "Add redirect URI: http://localhost:3000/api/auth/box/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://app.box.com/developers/console",
    envVars: ["BOX_CLIENT_ID", "BOX_CLIENT_SECRET"],
  },
  airtable: {
    title: "Airtable OAuth Setup",
    category: "storage",
    steps: [
      "Go to Airtable Developer Hub",
      "Create new OAuth integration",
      "Add redirect URI: http://localhost:3000/api/auth/airtable/callback",
      "Select required scopes",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://airtable.com/create/oauth",
    envVars: ["AIRTABLE_CLIENT_ID", "AIRTABLE_CLIENT_SECRET"],
  },
  supabase: {
    title: "Supabase Setup",
    category: "infrastructure",
    steps: [
      "Go to Supabase Dashboard",
      "Create new project or select existing",
      "Go to Settings > API",
      "Copy Project URL and anon/service_role keys",
      "Add to .env file",
    ],
    link: "https://supabase.com/dashboard",
    envVars: ["SUPABASE_URL", "SUPABASE_ANON_KEY", "SUPABASE_SERVICE_ROLE_KEY"],
  },
  neon: {
    title: "Neon Database Setup",
    category: "infrastructure",
    steps: [
      "Go to Neon Console",
      "Create new project",
      "Copy connection string from Dashboard",
      "Add to .env file",
    ],
    link: "https://console.neon.tech/",
    envVars: ["DATABASE_URL"],
  },
  snowflake: {
    title: "Snowflake Setup",
    category: "infrastructure",
    steps: [
      "Go to Snowflake Console",
      "Create a service account or use existing credentials",
      "Note your account identifier, warehouse, database",
      "Add credentials to .env",
    ],
    link: "https://app.snowflake.com/",
    envVars: ["SNOWFLAKE_ACCOUNT", "SNOWFLAKE_USER", "SNOWFLAKE_PASSWORD", "SNOWFLAKE_WAREHOUSE"],
  },
  aws: {
    title: "AWS Setup",
    category: "infrastructure",
    steps: [
      "Go to AWS IAM Console",
      "Create new IAM user with programmatic access",
      "Attach required policies (S3, Lambda, DynamoDB)",
      "Copy Access Key ID and Secret",
      "Add to .env file",
    ],
    link: "https://console.aws.amazon.com/iam/",
    envVars: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION"],
  },
  salesforce: {
    title: "Salesforce Connected App Setup",
    category: "sales",
    steps: [
      "Go to Salesforce Setup > App Manager",
      "Create new Connected App",
      "Enable OAuth Settings",
      "Add callback URL: http://localhost:3000/api/auth/salesforce/callback",
      "Select OAuth scopes: api, refresh_token",
      "Copy Consumer Key and Secret to .env",
    ],
    link: "https://login.salesforce.com/",
    envVars: ["SALESFORCE_CLIENT_ID", "SALESFORCE_CLIENT_SECRET"],
  },
  pipedrive: {
    title: "Pipedrive OAuth Setup",
    category: "sales",
    steps: [
      "Go to Pipedrive Developer Hub",
      "Create new app",
      "Add redirect URI: http://localhost:3000/api/auth/pipedrive/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://developers.pipedrive.com/",
    envVars: ["PIPEDRIVE_CLIENT_ID", "PIPEDRIVE_CLIENT_SECRET"],
  },
  zendesk: {
    title: "Zendesk OAuth Setup",
    category: "support",
    steps: [
      "Go to Zendesk Admin > API > OAuth Clients",
      "Add new OAuth client",
      "Set redirect URI: http://localhost:3000/api/auth/zendesk/callback",
      "Copy Client ID and Secret to .env",
      "Add your Zendesk subdomain",
    ],
    link: "https://support.zendesk.com/hc/en-us/articles/4408845965210",
    envVars: ["ZENDESK_CLIENT_ID", "ZENDESK_CLIENT_SECRET", "ZENDESK_SUBDOMAIN"],
  },
  intercom: {
    title: "Intercom OAuth Setup",
    category: "support",
    steps: [
      "Go to Intercom Developer Hub",
      "Create new app",
      "Add redirect URI: http://localhost:3000/api/auth/intercom/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://developers.intercom.com/",
    envVars: ["INTERCOM_CLIENT_ID", "INTERCOM_CLIENT_SECRET"],
  },
  freshdesk: {
    title: "Freshdesk OAuth Setup",
    category: "support",
    steps: [
      "Go to Freshdesk Admin > Apps > Custom Apps",
      "Create new OAuth application",
      "Add redirect URI: http://localhost:3000/api/auth/freshdesk/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://developers.freshdesk.com/",
    envVars: ["FRESHDESK_CLIENT_ID", "FRESHDESK_CLIENT_SECRET", "FRESHDESK_DOMAIN"],
  },
  servicenow: {
    title: "ServiceNow OAuth Setup",
    category: "support",
    steps: [
      "Go to ServiceNow System OAuth > Application Registry",
      "Create OAuth API endpoint for external clients",
      "Add redirect URL: http://localhost:3000/api/auth/servicenow/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://docs.servicenow.com/",
    envVars: ["SERVICENOW_CLIENT_ID", "SERVICENOW_CLIENT_SECRET", "SERVICENOW_INSTANCE"],
  },
  stripe: {
    title: "Stripe Setup",
    category: "finance",
    steps: [
      "Go to Stripe Dashboard",
      "Go to Developers > API keys",
      "Copy Publishable and Secret keys",
      "For Connect, set up OAuth in Connect settings",
      "Add to .env file",
    ],
    link: "https://dashboard.stripe.com/apikeys",
    envVars: ["STRIPE_SECRET_KEY", "STRIPE_PUBLISHABLE_KEY"],
  },
  quickbooks: {
    title: "QuickBooks OAuth Setup",
    category: "finance",
    steps: [
      "Go to Intuit Developer Portal",
      "Create new app",
      "Add redirect URI: http://localhost:3000/api/auth/quickbooks/callback",
      "Select Accounting scope",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://developer.intuit.com/app/developer/dashboard",
    envVars: ["QUICKBOOKS_CLIENT_ID", "QUICKBOOKS_CLIENT_SECRET"],
  },
  xero: {
    title: "Xero OAuth Setup",
    category: "finance",
    steps: [
      "Go to Xero Developer Portal",
      "Create new app",
      "Add redirect URI: http://localhost:3000/api/auth/xero/callback",
      "Select required scopes",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://developer.xero.com/app/manage",
    envVars: ["XERO_CLIENT_ID", "XERO_CLIENT_SECRET"],
  },
  mailchimp: {
    title: "Mailchimp OAuth Setup",
    category: "marketing",
    steps: [
      "Go to Mailchimp Developer Portal",
      "Register new app",
      "Add redirect URI: http://localhost:3000/api/auth/mailchimp/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://admin.mailchimp.com/account/oauth2/",
    envVars: ["MAILCHIMP_CLIENT_ID", "MAILCHIMP_CLIENT_SECRET"],
  },
  shopify: {
    title: "Shopify App Setup",
    category: "marketing",
    steps: [
      "Go to Shopify Partners Dashboard",
      "Create new app",
      "Add redirect URI: http://localhost:3000/api/auth/shopify/callback",
      "Copy API Key and Secret to .env",
    ],
    link: "https://partners.shopify.com/",
    envVars: ["SHOPIFY_API_KEY", "SHOPIFY_API_SECRET"],
  },
  twitter: {
    title: "Twitter/X OAuth Setup",
    category: "marketing",
    steps: [
      "Go to Twitter Developer Portal",
      "Create new project and app",
      "Enable OAuth 2.0",
      "Add redirect URI: http://localhost:3000/api/auth/twitter/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://developer.twitter.com/en/portal/dashboard",
    envVars: ["TWITTER_CLIENT_ID", "TWITTER_CLIENT_SECRET"],
  },
  figma: {
    title: "Figma OAuth Setup",
    category: "design",
    steps: [
      "Go to Figma Developer Settings",
      "Create new app",
      "Add redirect URI: http://localhost:3000/api/auth/figma/callback",
      "Copy Client ID and Secret to .env",
    ],
    link: "https://www.figma.com/developers/apps",
    envVars: ["FIGMA_CLIENT_ID", "FIGMA_CLIENT_SECRET"],
  },
  anthropic: {
    title: "Anthropic API Setup",
    category: "ai",
    steps: ["Go to Anthropic Console", "Create new API key", "Copy API key to .env"],
    link: "https://console.anthropic.com/",
    envVars: ["ANTHROPIC_API_KEY"],
  },
};

export function filterIntegrations(
  integrations: Integration[],
  searchQuery: string,
  selectedCategory: string | null,
): Integration[] {
  const query = searchQuery.toLowerCase();

  return integrations.filter((integration) => {
    const guide = OAUTH_SETUP_GUIDES[integration.id];

    const matchesSearch =
      query === "" ||
      integration.name.toLowerCase().includes(query) ||
      integration.id.toLowerCase().includes(query);

    const matchesCategory = selectedCategory === null || guide?.category === selectedCategory;

    return matchesSearch && matchesCategory;
  });
}

export function groupIntegrationsByCategory(
  integrations: Integration[],
): Record<string, Integration[]> {
  const groups: Record<string, Integration[]> = {};

  for (const integration of integrations) {
    const category = OAUTH_SETUP_GUIDES[integration.id]?.category ?? "other";
    (groups[category] ??= []).push(integration);
  }

  return groups;
}

export function buildSetupSteps(
  envChecked: boolean,
  allConnected: boolean,
  markEnvChecked: () => void,
): SetupStep[] {
  return [
    {
      id: "env",
      title: "Configure Environment Variables",
      description: "Add your OAuth credentials to the .env file",
      completed: envChecked,
      action: markEnvChecked,
    },
    {
      id: "oauth",
      title: "Create OAuth Apps",
      description: "Set up OAuth applications for each service",
      completed: false,
    },
    {
      id: "connect",
      title: "Connect Services",
      description: "Authorize your app to access each service",
      completed: allConnected,
    },
  ];
}

export function getTokenStorageStyles(
  tokenStorage: TokenStorageStatus | null,
): TokenStorageStyles | null {
  if (!tokenStorage) return null;

  const isMemory = tokenStorage.mode === "memory";

  return {
    container: `rounded-2xl p-6 shadow-sm border mb-8 ${
      isMemory
        ? "bg-amber-50 dark:bg-amber-900/20 border-amber-200 dark:border-amber-800"
        : "bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800"
    }`,
    iconWrapper: `w-10 h-10 rounded-full flex items-center justify-center ${
      isMemory ? "bg-amber-100 dark:bg-amber-900" : "bg-green-100 dark:bg-green-900"
    }`,
    title: `font-semibold ${
      isMemory ? "text-amber-800 dark:text-amber-200" : "text-green-800 dark:text-green-200"
    }`,
    text: `text-sm mt-1 ${
      isMemory ? "text-amber-700 dark:text-amber-300" : "text-green-700 dark:text-green-300"
    }`,
    isMemory,
  };
}

export function ServiceIcon({ name }: { name: string }): React.JSX.Element {
  const iconMap: Record<string, React.JSX.Element> = {
    mail: (
      <svg className="w-6 h-6 text-red-500" fill="currentColor" viewBox="0 0 24 24">
        <path
          d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
          stroke="currentColor"
          strokeWidth="2"
          fill="none"
        />
      </svg>
    ),
    slack: (
      <svg className="w-6 h-6" viewBox="0 0 24 24" fill="none">
        <path
          d="M5.042 15.165a2.528 2.528 0 0 1-2.52 2.523A2.528 2.528 0 0 1 0 15.165a2.527 2.527 0 0 1 2.522-2.52h2.52v2.52zM6.313 15.165a2.527 2.527 0 0 1 2.521-2.52 2.527 2.527 0 0 1 2.521 2.52v6.313A2.528 2.528 0 0 1 8.834 24a2.528 2.528 0 0 1-2.521-2.522v-6.313z"
          fill="#E01E5A"
        />
        <path
          d="M8.834 5.042a2.528 2.528 0 0 1-2.521-2.52A2.528 2.528 0 0 1 8.834 0a2.528 2.528 0 0 1 2.521 2.522v2.52H8.834zM8.834 6.313a2.528 2.528 0 0 1 2.521 2.521 2.528 2.528 0 0 1-2.521 2.521H2.522A2.528 2.528 0 0 1 0 8.834a2.528 2.528 0 0 1 2.522-2.521h6.312z"
          fill="#36C5F0"
        />
        <path
          d="M18.956 8.834a2.528 2.528 0 0 1 2.522-2.521A2.528 2.528 0 0 1 24 8.834a2.528 2.528 0 0 1-2.522 2.521h-2.522V8.834zM17.688 8.834a2.528 2.528 0 0 1-2.523 2.521 2.527 2.527 0 0 1-2.52-2.521V2.522A2.527 2.527 0 0 1 15.165 0a2.528 2.528 0 0 1 2.523 2.522v6.312z"
          fill="#2EB67D"
        />
        <path
          d="M15.165 18.956a2.528 2.528 0 0 1 2.523 2.522A2.528 2.528 0 0 1 15.165 24a2.527 2.527 0 0 1-2.52-2.522v-2.522h2.52zM15.165 17.688a2.527 2.527 0 0 1-2.52-2.523 2.526 2.526 0 0 1 2.52-2.52h6.313A2.527 2.527 0 0 1 24 15.165a2.528 2.528 0 0 1-2.522 2.523h-6.313z"
          fill="#ECB22E"
        />
      </svg>
    ),
    calendar: (
      <svg
        className="w-6 h-6 text-blue-500"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
        />
      </svg>
    ),
    github: (
      <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
        <path
          fillRule="evenodd"
          d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
          clipRule="evenodd"
        />
      </svg>
    ),
    jira: (
      <svg className="w-6 h-6" viewBox="0 0 24 24">
        <defs>
          <linearGradient id="jira-gradient" x1="98.031%" x2="58.888%" y1=".161%" y2="40.766%">
            <stop offset="0%" stopColor="#0052CC" />
            <stop offset="100%" stopColor="#2684FF" />
          </linearGradient>
        </defs>
        <path
          fill="url(#jira-gradient)"
          d="M11.571 11.513H0a5.218 5.218 0 005.232 5.215h2.13v2.057A5.215 5.215 0 0012.575 24V12.518a1.005 1.005 0 00-1.005-1.005z"
        />
        <path
          fill="#2684FF"
          d="M17.151 5.97H5.58a5.215 5.215 0 005.215 5.214h2.129v2.058a5.218 5.218 0 005.232 5.215V6.975a1.005 1.005 0 00-1.005-1.005z"
        />
        <path
          fill="#2684FF"
          d="M22.723.426H11.152a5.215 5.215 0 005.215 5.215h2.129v2.057a5.218 5.218 0 005.232 5.215V1.431a1.005 1.005 0 00-1.005-1.005z"
        />
      </svg>
    ),
    notion: (
      <svg className="w-6 h-6" viewBox="0 0 24 24" fill="currentColor">
        <path d="M4.459 4.208c.746.606 1.026.56 2.428.466l13.215-.793c.28 0 .047-.28-.046-.326L17.86 1.968c-.42-.326-.98-.7-2.055-.607L3.01 2.295c-.466.046-.56.28-.374.466l1.823 1.447zm.793 3.08v13.904c0 .747.373 1.027 1.214.98l14.523-.84c.84-.046.933-.56.933-1.167V6.354c0-.606-.233-.933-.746-.886l-15.177.887c-.56.046-.747.326-.747.933zm14.337.745c.093.42 0 .84-.42.888l-.7.14v10.264c-.608.327-1.168.514-1.635.514-.746 0-.933-.234-1.495-.933l-4.577-7.186v6.952L12.21 19s0 .84-1.168.84l-3.222.186c-.093-.186 0-.653.327-.746l.84-.233V9.854L7.822 9.76c-.094-.42.14-1.026.793-1.073l3.456-.233 4.764 7.279v-6.44l-1.215-.14c-.093-.514.28-.886.747-.933l3.222-.186zM1.936 1.035l13.31-.98c1.634-.14 2.055-.047 3.082.7l4.249 2.986c.7.513.933.653.933 1.213v16.378c0 1.026-.373 1.634-1.68 1.726l-15.458.934c-.98.047-1.448-.093-1.962-.747l-3.129-4.06c-.56-.747-.793-1.306-.793-1.96V2.667c0-.839.374-1.54 1.448-1.632z" />
      </svg>
    ),
    default: (
      <svg
        className="w-6 h-6 text-neutral-400"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M13 10V3L4 14h7v7l9-11h-7z"
        />
      </svg>
    ),
  };

  return iconMap[name] ?? iconMap.default;
}
