export declare const DEFAULT_DEV_PORT = 3000;
export declare const DEFAULT_PROXY_PORT = 8080;
export declare const SPINNER_INTERVAL_MS = 80;
export declare const RENDER_INTERVAL_MS = 100;
export declare const SHUTDOWN_TIMEOUT_MS = 3000;
export declare const TYPEWRITER_CHAR_DELAY_MS = 30;
export declare const TYPEWRITER_WORD_DELAY_MS = 100;
export declare const DEFAULT_PADDING_X = 2;
export declare const DEFAULT_PADDING_Y = 1;
export declare const DEFAULT_PROGRESS_BAR_WIDTH = 20;
export declare const DEFAULT_TERMINAL_WIDTH = 80;
export declare const DEFAULT_TERMINAL_HEIGHT = 24;
export declare const DURATION_SECONDS_THRESHOLD_MS = 1000;
export declare const DURATION_MINUTES_THRESHOLD_MS = 60000;
//# sourceMappingURL=constants.d.ts.map