/**
 * Agent Index Generator
 *
 * Generates a TypeScript file that exports all discovered agents
 * for runtime lookup.
 */

import { agentLogger } from "#veryfront/utils/logger/logger.ts";
import { getTrackedAgentPaths } from "./discovery-utils.ts";

/**
 * Generate an index file for all discovered agents
 */
export async function generateAgentIndex(baseDir: string): Promise<void> {
  const generatedDir = `${baseDir}/.generated`;
  const indexPath = `${generatedDir}/agents.ts`;
  const discoveredAgentPaths = getTrackedAgentPaths();

  try {
    const [fsModule, pathModule] = await Promise.all([import("node:fs"), import("node:path")]);

    if (!fsModule.existsSync(generatedDir)) {
      fsModule.mkdirSync(generatedDir, { recursive: true });
    }

    const lines: string[] = [
      "/**",
      " * Auto-generated by veryfront",
      " * Do not edit manually - this file is regenerated on each dev server start",
      " */",
      "",
    ];

    for (const [id, filePath] of discoveredAgentPaths) {
      const cleanPath = filePath.replace("file://", "");
      const relativePath = pathModule.relative(generatedDir, cleanPath).replace(
        /\.(ts|tsx|js|jsx)$/,
        "",
      );
      lines.push(`export { default as ${id} } from '${relativePath}';`);
    }

    lines.push("");
    lines.push("// Runtime lookup object");

    const agentIds = Array.from(discoveredAgentPaths.keys());
    if (agentIds.length) {
      lines.push(`import { ${agentIds.join(", ")} } from './agents';`);
      lines.push("");
      lines.push("export const agents = {");
      for (const id of agentIds) lines.push(`  ${id},`);
      lines.push("} as const;");
    } else {
      lines.push("export const agents = {} as const;");
    }

    lines.push("");

    fsModule.writeFileSync(indexPath, lines.join("\n"));
    agentLogger.debug(`[Discovery] Generated agent index: ${indexPath}`);
  } catch (error) {
    agentLogger.debug(`[Discovery] Could not generate agent index: ${error}`);
  }
}
