/**
 * Public extension API surface.
 *
 * Types used when authoring extensions (the scaffold template generated by
 * `veryfront extension init` imports from this module).
 *
 * @module extensions
 */

export type {
  Capability,
  Extension,
  ExtensionConfigEntry,
  ExtensionContext,
  ExtensionFactory,
  ExtensionLogger,
  ExtensionSource,
  ResolvedExtension,
} from "./types.ts";
