/**
 * Public extension API surface.
 *
 * Types used when authoring extensions (the scaffold template generated by
 * `veryfront extension init` imports from this module), plus the runtime
 * helpers consumers need to load, validate, and orchestrate extensions.
 *
 * @module extensions
 */

// Core types
export type {
  Capability,
  Extension,
  ExtensionConfigEntry,
  ExtensionContext,
  ExtensionFactory,
  ExtensionLogger,
  ExtensionSource,
  ResolvedExtension,
} from "./types.ts";

// Contract registry — resolve/tryResolve are the consumer-facing API.
// register()/reset() are internal primitives (used by ExtensionLoader and
// tests) and are intentionally not exported here.
export { resolve, tryResolve } from "./contracts.ts";

// Discovery
export type { PackageMetadata } from "./discovery.ts";
export {
  discoverLocalExtensions,
  discoverPackageExtensions,
  discoverProjectExtensions,
  mergeExtensions,
  parsePackageMetadata,
} from "./discovery.ts";

// Loader
export { ExtensionLoader } from "./loader.ts";

// Validation
export type { ConflictInfo } from "./validation.ts";
export { detectConflicts, validateExtension } from "./validation.ts";

// Capabilities
export { auditCapabilities, formatCapabilities, mapToDenoPermissions } from "./capabilities.ts";

// Recommendations
export { getRecommendation } from "./recommendations.ts";

// Errors
export {
  CIRCULAR_DEPENDENCY_ERROR,
  EXTENSION_CONFLICT_ERROR,
  EXTENSION_VALIDATION_ERROR,
  MISSING_EXTENSION_ERROR,
} from "./errors.ts";
