export interface RuntimeEnv {
    nodeEnv: "development" | "production" | "test" | string;
    veryfrontEnv: string;
    veryfrontMode: string;
    debug: boolean;
    ci: boolean;
    denoTesting: boolean;
    perfEnabled: boolean;
    apiBaseUrl: string;
    apiUrl: string | undefined;
    apiToken: string | undefined;
    projectSlug: string | undefined;
    homeDir: string | undefined;
    xdgConfigHome: string | undefined;
    continuousIntegration: boolean;
    sshClient: string | undefined;
    sshTty: string | undefined;
    display: string | undefined;
    waylandDisplay: string | undefined;
    cursorSession: string | undefined;
    serverStartTime: string | undefined;
    vcr: string | undefined;
    experimentalRsc: boolean;
    redisUrl: string | undefined;
    cacheDir: string | undefined;
    disableLruInterval: boolean;
    appUrl: string | undefined;
    port: number;
    requestTimeoutMs: number | undefined;
    httpFetchTimeoutMs: number | undefined;
    ssrMaxConcurrentTransforms: number;
    otelEnabled: boolean;
    otelServiceName: string | undefined;
    otelEndpoint: string | undefined;
    otelTracesEndpoint: string | undefined;
    otelMetricsEndpoint: string | undefined;
    otelTracesExporter: string | undefined;
    otelMetricsExporter: string | undefined;
    otelHeaders: string | undefined;
    otelMetricsEnabled: boolean;
    openaiApiKey: string | undefined;
    openaiBaseUrl: string | undefined;
    anthropicApiKey: string | undefined;
    anthropicBaseUrl: string | undefined;
    googleApiKey: string | undefined;
    githubToken: string | undefined;
    githubOwner: string | undefined;
    githubRepo: string | undefined;
    githubRef: string | undefined;
    noColor: boolean;
    forceColor: boolean;
    denoV8Flags: string;
    v8MaxOldSpaceSize: number | undefined;
    veryfrontVersion: string | undefined;
}
export declare function initRuntimeEnv(): RuntimeEnv;
export declare function getRuntimeEnv(): RuntimeEnv;
export declare function isRuntimeEnvInitialized(): boolean;
export declare function createTestRuntimeEnv(overrides?: Partial<RuntimeEnv>): RuntimeEnv;
export declare function _setRuntimeEnvForTesting(env: Partial<RuntimeEnv>): void;
export declare function _resetRuntimeEnv(): void;
//# sourceMappingURL=runtime-env.d.ts.map