/**
 * Path Validation Types
 * @module security/path-validation/types
 */
export const PathValidationError = {
    NULL_BYTE: "NULL_BYTE",
    PATH_TOO_LONG: "PATH_TOO_LONG",
    EXCESSIVE_TRAVERSAL: "EXCESSIVE_TRAVERSAL",
    FORBIDDEN_PATTERN: "FORBIDDEN_PATTERN",
    OUTSIDE_BASE: "OUTSIDE_BASE",
    NOT_IN_ALLOWLIST: "NOT_IN_ALLOWLIST",
    FILE_NOT_FOUND: "FILE_NOT_FOUND",
    SYMLINK_DETECTED: "SYMLINK_DETECTED",
    INVALID_PATH: "INVALID_PATH",
    ABSOLUTE_PATH_DENIED: "ABSOLUTE_PATH_DENIED",
};
