declare namespace _default {
    let name: string;
    let version: string;
    let nodeModulesDir: string;
    let exclude: string[];
    let exports: {
        ".": string;
        "./cli": string;
        "./server": string;
        "./middleware": string;
        "./head": string;
        "./router": string;
        "./context": string;
        "./fonts": string;
        "./react": string;
        "./react/components": string;
        "./react/components/ai": string;
        "./react/primitives": string;
        "./react/context": string;
        "./react/router": string;
        "./react/fonts": string;
        "./react/head": string;
        "./data": string;
        "./config": string;
        "./platform": string;
        "./tool": string;
        "./tool/schema": string;
        "./tool/testing": string;
        "./provider": string;
        "./provider/adapters": string;
        "./agent": string;
        "./agent/react": string;
        "./agent/react/client": string;
        "./agent/memory": string;
        "./agent/composition": string;
        "./agent/middleware": string;
        "./agent/testing": string;
        "./agent/debug": string;
        "./workflow": string;
        "./workflow/react": string;
        "./prompt": string;
        "./resource": string;
        "./mcp": string;
        "./oauth": string;
        "./oauth/providers": string;
        "./oauth/handlers": string;
        "./oauth/token-store": string;
        "./embeddings": string;
    };
    let imports: {
        "veryfront/head": string;
        "veryfront/router": string;
        "veryfront/context": string;
        "veryfront/fonts": string;
        "veryfront/react/head": string;
        "veryfront/react/router": string;
        "veryfront/react/context": string;
        "veryfront/react/fonts": string;
        "veryfront/react/components/ai": string;
        "veryfront/agent/react": string;
        "veryfront/workflow/react": string;
        "#veryfront": string;
        "#veryfront/agent": string;
        "#veryfront/agent/react": string;
        "#veryfront/build": string;
        "#veryfront/cache": string;
        "#veryfront/cli/ui": string;
        "#veryfront/config": string;
        "#veryfront/data": string;
        "#veryfront/errors": string;
        "#veryfront/html": string;
        "#veryfront/mcp": string;
        "#veryfront/middleware": string;
        "#veryfront/modules": string;
        "#veryfront/observability": string;
        "#veryfront/platform": string;
        "#veryfront/prompt": string;
        "#veryfront/provider": string;
        "#veryfront/react": string;
        "#veryfront/rendering": string;
        "#veryfront/resource": string;
        "#veryfront/routing": string;
        "#veryfront/security": string;
        "#veryfront/server": string;
        "#veryfront/testing": string;
        "#veryfront/tool": string;
        "#veryfront/tool/schema": string;
        "#veryfront/transforms": string;
        "#veryfront/types": string;
        "#veryfront/utils": string;
        "#veryfront/workflow": string;
        "#veryfront/workflow/react": string;
        "#veryfront/embeddings": string;
        "#veryfront/http/responses": string;
        "#veryfront/compat/console": string;
        "#veryfront/compat/http": string;
        "#veryfront/compat/kv": string;
        "#veryfront/compat/path": string;
        "#veryfront/compat/": string;
        "#veryfront/http/": string;
        "#veryfront/platform/": string;
        "#veryfront/components": string;
        "#veryfront/": string;
        "@veryfront": string;
        "@veryfront/": string;
        "@veryfront/agent": string;
        "@veryfront/agent/react": string;
        "@veryfront/agent/middleware": string;
        "@veryfront/agent/memory": string;
        "@veryfront/agent/composition": string;
        "@veryfront/agent/testing": string;
        "@veryfront/agent/debug": string;
        "@veryfront/build": string;
        "@veryfront/cache": string;
        "@veryfront/cli/ui": string;
        "@veryfront/compat/": string;
        "@veryfront/compat/console": string;
        "@veryfront/compat/path": string;
        "@veryfront/components": string;
        "@veryfront/config": string;
        "@veryfront/data": string;
        "@veryfront/errors": string;
        "@veryfront/html": string;
        "@veryfront/http/responses": string;
        "@veryfront/mcp": string;
        "@veryfront/middleware": string;
        "@veryfront/modules": string;
        "@veryfront/oauth": string;
        "@veryfront/observability": string;
        "@veryfront/platform": string;
        "@veryfront/prompt": string;
        "@veryfront/provider": string;
        "@veryfront/react": string;
        "@veryfront/rendering": string;
        "@veryfront/resource": string;
        "@veryfront/routing": string;
        "@veryfront/security": string;
        "@veryfront/server": string;
        "@veryfront/tool": string;
        "@veryfront/tool/schema": string;
        "@veryfront/transforms": string;
        "@veryfront/types": string;
        "@veryfront/utils": string;
        "@veryfront/workflow": string;
        "@veryfront/workflow/react": string;
        "@veryfront/testing": string;
        "@veryfront/testing/assert": string;
        "@veryfront/testing/bdd": string;
        "@veryfront/testing/deno-compat": string;
        "@veryfront/testing/utils": string;
        "std/": string;
        "#std/path": string;
        "#std/path.ts": string;
        "#std/assert": string;
        "#std/assert.ts": string;
        "#std/dotenv": string;
        "#std/dotenv.ts": string;
        "#std/flags": string;
        "#std/flags.ts": string;
        "#std/fmt/colors": string;
        "#std/fmt/colors.ts": string;
        "#std/testing": string;
        "#std/testing.ts": string;
        "#std/testing/bdd": string;
        "#std/testing/bdd.ts": string;
        "#std/expect": string;
        "#std/expect.ts": string;
        "#std/fs": string;
        "#std/fs.ts": string;
        "#std/async": string;
        "#std/async.ts": string;
        "#std/front-matter/yaml": string;
        "#std/front-matter/yaml.ts": string;
        "@std/path": string;
        "@std/assert": string;
        "@std/dotenv": string;
        "@std/flags": string;
        "@std/fmt/colors": string;
        "@std/testing": string;
        "@std/testing/bdd": string;
        "@std/expect": string;
        "@std/fs": string;
        "@std/async": string;
        "@std/front-matter/yaml": string;
        csstype: string;
        "@types/react": string;
        "@types/react-dom": string;
        react: string;
        "react-dom": string;
        "react-dom/server": string;
        "react-dom/client": string;
        "react/jsx-runtime": string;
        "react/jsx-dev-runtime": string;
        "@mdx-js/mdx": string;
        "@mdx-js/react": string;
        "unist-util-visit": string;
        "mdast-util-to-string": string;
        "github-slugger": string;
        "remark-parse": string;
        "remark-gfm": string;
        "remark-frontmatter": string;
        "remark-rehype": string;
        "rehype-highlight": string;
        "rehype-starry-night": string;
        "rehype-slug": string;
        "rehype-stringify": string;
        esbuild: string;
        "esbuild/mod.js": string;
        "es-module-lexer": string;
        "gray-matter": string;
        zod: string;
        "mime-types": string;
        mdast: string;
        hast: string;
        unist: string;
        unified: string;
        vfile: string;
        ai: string;
        "ai/react": string;
        "@ai-sdk/react": string;
        "@ai-sdk/openai": string;
        "@ai-sdk/anthropic": string;
        tailwindcss: string;
        redis: string;
        pg: string;
        "@opentelemetry/api": string;
        "@opentelemetry/core": string;
        "@opentelemetry/context-async-hooks": string;
        "@opentelemetry/sdk-trace-base": string;
        "@opentelemetry/exporter-trace-otlp-http": string;
        "@opentelemetry/resources": string;
        "@opentelemetry/semantic-conventions": string;
        "@babel/parser": string;
        "@babel/traverse": string;
        "@babel/generator": string;
        "@babel/types": string;
    };
    namespace compilerOptions {
        let jsx: string;
        let jsxImportSource: string;
        let strict: boolean;
        let noImplicitAny: boolean;
        let noUncheckedIndexedAccess: boolean;
        let types: string[];
        let lib: string[];
    }
    let tasks: {
        setup: string;
        start: string;
        "start:headless": string;
        proxy: string;
        renderer: string;
        build: string;
        "build:npm": string;
        release: string;
        test: string;
        "test:unit": string;
        "test:integration": string;
        "test:integration:cli": string;
        "test:record": string;
        "test:coverage": string;
        "test:coverage:unit": string;
        "test:coverage:integration": string;
        "coverage:report": string;
        "coverage:html": string;
        clean: string;
        lint: string;
        fmt: string;
        "fmt:check": string;
        typecheck: string;
        verify: string;
        "verify:quick": string;
        "docs:check-links": string;
        "lint:ban-console": string;
        "lint:ban-deep-imports": string;
        "lint:ban-internal-root-imports": string;
        "lint:check-awaits": string;
        "lint:platform": string;
        "test:smoke": string;
        "test:cross-runtime": string;
        "test:node": string;
        "test:bun": string;
        "test:all-runtimes": string;
        "test:e2e": string;
        "check:circular": string;
        cli: string;
        mcp: string;
        "batch:estimate": string;
        "batch:prepare": string;
        "batch:submit": string;
        "batch:status": string;
        "batch:errors": string;
        "batch:download": string;
        "batch:apply": string;
        "rlm:example": string;
        "rlm:explore": string;
        "rlm:audit": string;
    };
    namespace lint {
        export let include: string[];
        let exclude_1: string[];
        export { exclude_1 as exclude };
        export namespace rules {
            export let tags: string[];
            let include_1: string[];
            export { include_1 as include };
            let exclude_2: string[];
            export { exclude_2 as exclude };
        }
    }
    namespace fmt {
        let include_2: string[];
        export { include_2 as include };
        let exclude_3: string[];
        export { exclude_3 as exclude };
        export let useTabs: boolean;
        export let lineWidth: number;
        export let indentWidth: number;
        export let semiColons: boolean;
        export let singleQuote: boolean;
        export let proseWrap: string;
    }
}
export default _default;
//# sourceMappingURL=deno.d.ts.map