// Compile the browser barrels used by getDefaultImportMap. The runtime mapping
// is tested separately because the repository import map reserves
// veryfront/react for the server-capable development barrel.
import {
  Reasoning as ReactReasoning,
  ToolCall as ReactToolCall,
  useReasoning as useReactReasoning,
  useToolCall as useReactToolCall,
} from "./public.ts";
import type {
  ReasoningContextValue as ReactReasoningContextValue,
  ReasoningProps as ReactReasoningProps,
  ReasoningTriggerProps as ReactReasoningTriggerProps,
  ToolCallContextValue as ReactToolCallContextValue,
  ToolCallProps as ReactToolCallProps,
  ToolCallTriggerProps as ReactToolCallTriggerProps,
} from "./public.ts";
import {
  CONVERSATION_STORAGE_LIMITS as ReactConversationStorageLimits,
  ConversationsContextProvider as ReactConversationsContextProvider,
  ConversationsProvider as ReactConversationsProvider,
  ConversationStoreError as ReactConversationStoreError,
  localConversationStore as ReactLocalConversationStore,
  memoryConversationStore as ReactMemoryConversationStore,
  useConversation as ReactUseConversation,
  useConversationChat as ReactUseConversationChat,
  useConversations as ReactUseConversations,
  useConversationsContext as ReactUseConversationsContext,
  useConversationsContextOptional as ReactUseConversationsContextOptional,
} from "./public.ts";
import type {
  ActiveConversationLoadFailure as ReactActiveConversationLoadFailure,
  Conversation as ReactConversation,
  ConversationPatch as ReactConversationPatch,
  ConversationsContextValue as ReactConversationsContextValue,
  ConversationsProviderProps as ReactConversationsProviderProps,
  ConversationStorageLimits as ReactConversationStorageLimitsType,
  ConversationStore as ReactConversationStore,
  ConversationStoreOperation as ReactConversationStoreOperation,
  ConversationSummary as ReactConversationSummary,
  StorageLike as ReactStorageLike,
  UseConversationChatOptions as ReactUseConversationChatOptions,
  UseConversationChatResult as ReactUseConversationChatResult,
  UseConversationOptions as ReactUseConversationOptions,
  UseConversationPersistenceState as ReactUseConversationPersistenceState,
  UseConversationResult as ReactUseConversationResult,
  UseConversationsActiveLoadState as ReactUseConversationsActiveLoadState,
  UseConversationsOptions as ReactUseConversationsOptions,
  UseConversationsPersistenceState as ReactUseConversationsPersistenceState,
  UseConversationsResult as ReactUseConversationsResult,
} from "./public.ts";
import {
  Reasoning as ChatReasoning,
  ToolCall as ChatToolCall,
  useReasoning as useChatReasoning,
  useToolCall as useChatToolCall,
} from "./components/chat/index.ts";
import type {
  ReasoningContextValue as ChatReasoningContextValue,
  ReasoningProps as ChatReasoningProps,
  ReasoningTriggerProps as ChatReasoningTriggerProps,
  ToolCallContextValue as ChatToolCallContextValue,
  ToolCallProps as ChatToolCallProps,
  ToolCallTriggerProps as ChatToolCallTriggerProps,
} from "./components/chat/index.ts";
import {
  CONVERSATION_STORAGE_LIMITS as ChatConversationStorageLimits,
  ConversationsContextProvider as ChatConversationsContextProvider,
  ConversationsProvider as ChatConversationsProvider,
  ConversationStoreError as ChatConversationStoreError,
  localConversationStore as ChatLocalConversationStore,
  memoryConversationStore as ChatMemoryConversationStore,
  useConversation as ChatUseConversation,
  useConversationChat as ChatUseConversationChat,
  useConversations as ChatUseConversations,
  useConversationsContext as ChatUseConversationsContext,
  useConversationsContextOptional as ChatUseConversationsContextOptional,
} from "./components/chat/index.ts";
import type {
  ActiveConversationLoadFailure as ChatActiveConversationLoadFailure,
  Conversation as ChatConversation,
  ConversationPatch as ChatConversationPatch,
  ConversationsContextValue as ChatConversationsContextValue,
  ConversationsProviderProps as ChatConversationsProviderProps,
  ConversationStorageLimits as ChatConversationStorageLimitsType,
  ConversationStore as ChatConversationStore,
  ConversationStoreOperation as ChatConversationStoreOperation,
  ConversationSummary as ChatConversationSummary,
  StorageLike as ChatStorageLike,
  UseConversationChatOptions as ChatUseConversationChatOptions,
  UseConversationChatResult as ChatUseConversationChatResult,
  UseConversationOptions as ChatUseConversationOptions,
  UseConversationPersistenceState as ChatUseConversationPersistenceState,
  UseConversationResult as ChatUseConversationResult,
  UseConversationsActiveLoadState as ChatUseConversationsActiveLoadState,
  UseConversationsOptions as ChatUseConversationsOptions,
  UseConversationsPersistenceState as ChatUseConversationsPersistenceState,
  UseConversationsResult as ChatUseConversationsResult,
} from "./components/chat/index.ts";

void [
  ReactReasoning,
  ReactToolCall,
  useReactReasoning,
  useReactToolCall,
  ChatReasoning,
  ChatToolCall,
  useChatReasoning,
  useChatToolCall,
  ReactConversationStorageLimits,
  ReactConversationsContextProvider,
  ReactConversationsProvider,
  ReactConversationStoreError,
  ReactLocalConversationStore,
  ReactMemoryConversationStore,
  ReactUseConversation,
  ReactUseConversationChat,
  ReactUseConversations,
  ReactUseConversationsContext,
  ReactUseConversationsContextOptional,
  ChatConversationStorageLimits,
  ChatConversationsContextProvider,
  ChatConversationsProvider,
  ChatConversationStoreError,
  ChatLocalConversationStore,
  ChatMemoryConversationStore,
  ChatUseConversation,
  ChatUseConversationChat,
  ChatUseConversations,
  ChatUseConversationsContext,
  ChatUseConversationsContextOptional,
];

export type ChatReactBarrelContracts = [
  ReactReasoningContextValue,
  ReactReasoningProps,
  ReactReasoningTriggerProps,
  ReactToolCallContextValue,
  ReactToolCallProps,
  ReactToolCallTriggerProps,
  ChatReasoningContextValue,
  ChatReasoningProps,
  ChatReasoningTriggerProps,
  ChatToolCallContextValue,
  ChatToolCallProps,
  ChatToolCallTriggerProps,
  ReactActiveConversationLoadFailure,
  ReactConversation,
  ReactConversationPatch,
  ReactConversationsContextValue,
  ReactConversationsProviderProps,
  ReactConversationStorageLimitsType,
  ReactConversationStore,
  ReactConversationStoreOperation,
  ReactConversationSummary,
  ReactStorageLike,
  ReactUseConversationChatOptions,
  ReactUseConversationChatResult,
  ReactUseConversationOptions,
  ReactUseConversationPersistenceState,
  ReactUseConversationResult,
  ReactUseConversationsOptions,
  ReactUseConversationsActiveLoadState,
  ReactUseConversationsPersistenceState,
  ReactUseConversationsResult,
  ChatActiveConversationLoadFailure,
  ChatConversation,
  ChatConversationPatch,
  ChatConversationsContextValue,
  ChatConversationsProviderProps,
  ChatConversationStorageLimitsType,
  ChatConversationStore,
  ChatConversationStoreOperation,
  ChatConversationSummary,
  ChatStorageLike,
  ChatUseConversationChatOptions,
  ChatUseConversationChatResult,
  ChatUseConversationOptions,
  ChatUseConversationPersistenceState,
  ChatUseConversationResult,
  ChatUseConversationsOptions,
  ChatUseConversationsActiveLoadState,
  ChatUseConversationsPersistenceState,
  ChatUseConversationsResult,
];
