export const TEST_TIMEOUTS = {
  UNIT: 5_000,
  INTEGRATION: 30_000,
  E2E: 60_000,
  BUILD: 120_000,
  SERVER_STARTUP: 10_000,
  HMR: 15_000,
} as const;

export const PORT_RANGE = {
  MIN: 9000,
  MAX: 12000,
} as const;

export const SERVER_CONFIG = {
  MAX_READY_ATTEMPTS: 20,
  READY_CHECK_DELAY: 100,
  MAX_READY_DELAY: 2000,
  FETCH_TIMEOUT: 2000,
} as const;

export const CLEANUP_CONFIG = {
  GRACEFUL_TIMEOUT: 5000,
  FORCE_TIMEOUT: 1000,
  CLEANUP_RETRY_DELAY: 50,
} as const;

export const DATA_LIMITS = {
  MAX_FIXTURE_SIZE: 1024 * 1024,
  MAX_BULK_ITEMS: 1000,
  MAX_STRING_LENGTH: 10_000,
} as const;

export const PERFORMANCE_BUDGETS = {
  SSR_RENDER: 100,
  API_RESPONSE: 50,
  CACHE_HIT: 10,
  FILE_READ: 20,
  BUILD_PER_COMPONENT: 500,
} as const;

export const RETRY_CONFIG = {
  DEFAULT_RETRIES: 3,
  RETRY_DELAY: 100,
  MAX_RETRY_TIME: 10_000,
} as const;

export const WEBSOCKET_CONFIG = {
  CONNECTION_TIMEOUT: 5000,
  MESSAGE_TIMEOUT: 2000,
  HEALTH_CHECK_CYCLES: 3,
} as const;

export const TEST_ENV_VARS = {
  DEBUG: "DEBUG_TESTS",
  DISABLE_LRU: "VF_DISABLE_LRU_INTERVAL",
  FORCE_ADAPTER: "VF_FORCE_ADAPTER",
  VERBOSE: "VF_TEST_VERBOSE",
} as const;

export const ISOLATION_MARKERS = {
  TEMP_DIR_PREFIX: "veryfront_test_",
  PORT_LOG_PREFIX: "[TEST-PORT]",
  CONTEXT_LOG_PREFIX: "[TEST-CONTEXT]",
} as const;
