
export async function GET() {
  const env = process.env;
  let mode: "memory" | "database" | "kv" | "redis" = "memory";

  if (env.DATABASE_URL) {
    mode = "database";
  } else if (env.KV_REST_API_URL) {
    mode = "kv";
  } else if (env.REDIS_URL) {
    mode = "redis";
  }

  const encryptionKey = env.TOKEN_ENCRYPTION_KEY;
  const hasExplicitKey = typeof encryptionKey === "string" && encryptionKey.length === 64;

  const encrypted = true;
  const autoGenerated = !hasExplicitKey;

  return Response.json({ mode, encrypted, autoGenerated });
}
