/** Pattern to match framework bundle imports: file://...framework/vfmod-... */
const FRAMEWORK_BUNDLE_PATTERN = /file:\/\/[^"'\s]+\/framework\/vfmod-[^"'\s]+\.mjs/g;

/**
 * Extract framework bundle file:// paths from code.
 * These are generated by the SSR VF modules transform.
 */
export function extractFrameworkBundlePaths(code: string): string[] {
  const matches = code.match(FRAMEWORK_BUNDLE_PATTERN);
  if (!matches) return [];
  return [...new Set(matches.map((match) => match.replace(/^file:\/\//, "")))];
}

type FrameworkBundleExists = (path: string) => boolean | Promise<boolean>;

interface FindMissingFrameworkBundlePathsOptions {
  onError?: (path: string, error: unknown) => void;
}

/** Return framework bundle paths referenced by code that are missing locally. */
export async function findMissingFrameworkBundlePaths(
  code: string,
  exists: FrameworkBundleExists,
  options: FindMissingFrameworkBundlePathsOptions = {},
): Promise<string[]> {
  const bundlePaths = extractFrameworkBundlePaths(code);
  const missing: string[] = [];

  for (const path of bundlePaths) {
    try {
      if (!(await exists(path))) {
        missing.push(path);
      }
    } catch (error) {
      options.onError?.(path, error);
      missing.push(path);
    }
  }

  return missing;
}
