/** Pattern to match framework bundle imports: file://...framework/vfmod-... */
const FRAMEWORK_BUNDLE_PATTERN = /file:\/\/[^"'\s]+\/framework\/vfmod-[^"'\s]+\.mjs/g;

/**
 * Extract framework bundle file:// paths from code.
 * These are generated by the SSR VF modules transform.
 */
export function extractFrameworkBundlePaths(code: string): string[] {
  const matches = code.match(FRAMEWORK_BUNDLE_PATTERN);
  if (!matches) return [];
  return [...new Set(matches.map((match) => match.replace(/^file:\/\//, "")))];
}
