#!/usr/bin/env -S deno run -A

import { dirname, fromFileUrl, join } from "../../../src/platform/compat/path/index.ts";

const scriptDirectory = dirname(fromFileUrl(import.meta.url));
const extensionRoot = join(scriptDirectory, "..");
const repositoryRoot = join(extensionRoot, "..", "..");
const sourcePath = join(extensionRoot, "src", "worker-renderer-source.ts");
const outputPath = join(
  extensionRoot,
  "src",
  "worker-renderer-bundle.generated.ts",
);
const checkOnly = Deno.args.length === 1 && Deno.args[0] === "--check";
if (Deno.args.length > (checkOnly ? 1 : 0)) {
  throw new TypeError("Usage: prebundle.ts [--check]");
}

const command = new Deno.Command(Deno.execPath(), {
  args: [
    "bundle",
    "--quiet",
    "--frozen",
    "--platform=browser",
    sourcePath,
  ],
  cwd: repositoryRoot,
  stdout: "piped",
  stderr: "piped",
});
const result = await command.output();
if (!result.success) {
  const diagnostic = new TextDecoder().decode(result.stderr).trim();
  throw new Error(diagnostic || "Failed to build the offline React SSR renderer bundle");
}

const bundle = new TextDecoder().decode(result.stdout);
const bundleBytes = new TextEncoder().encode(bundle);
const digest = new Uint8Array(
  await crypto.subtle.digest("SHA-256", bundleBytes),
).toHex();
const bundleBase64 = bundleBytes.toBase64();
const generated = `/**
 * Extension-owned offline React SSR renderer bundle.
 *
 * AUTO-GENERATED by extensions/ext-react-ssr/scripts/prebundle.ts.
 * Do not edit manually.
 */

// deno-fmt-ignore - preserve the generated JavaScript as one base64 string.
export const REACT_SSR_RENDERER_BUNDLE_BASE64: string = ${JSON.stringify(bundleBase64)};
export const REACT_SSR_RENDERER_BUNDLE_SHA256 =
  ${JSON.stringify(digest)};
`;

if (checkOnly) {
  const current = await Deno.readTextFile(outputPath);
  if (current !== generated) {
    throw new Error(
      "Offline React SSR renderer bundle is stale; run deno task generate:renderer",
    );
  }
} else {
  await Deno.writeTextFile(outputPath, generated);
  console.log(
    `[ext-react-ssr] Wrote ${outputPath} (${bundle.length} bytes, sha256:${digest})`,
  );
}
